#!/bin/sh
# For each table file DIR/inE given on the command line, write
#   Data_N.v  its lines, verbatim (genraw.py)
#   Run_N.v   the run of the checker on them (needs ExpCheck.v and
#             ExpParse.v only)
# where N is the file name with '-' written 'm' after "in" and '_' elsewhere
# (in-1074 -> inm1074, in0-0 -> in0_0).
# Usage: ./mksample.sh DIR/in1024 DIR/in-1074 ...   then: make -jJ sample
set -e
[ $# -gt 0 ] || { echo "usage: $0 table-files..."; exit 1; }

# Write stdin to $1 only if the content changes, so make does not redo
# a run whose file is the same.
put() {
  cat > "$1.new"
  if cmp -s "$1.new" "$1"; then rm "$1.new"; else mv "$1.new" "$1"; fi
}

for F in "$@"; do
  B=$(basename "$F")
  N=$(echo "$B" | sed 's/^in-/inm/; s/-/_/g')
  L=$(wc -l < "$F")
  python3 genraw.py "$F" 0 "$L" Data_$N.v.new
  if cmp -s Data_$N.v.new Data_$N.v; then rm Data_$N.v.new
  else mv Data_$N.v.new Data_$N.v; fi
  put Run_$N.v <<EOT
(* Generated by mksample.sh: the $L lines of the table file $B. *)

From ExpTable9 Require Import ExpCheck ExpParse Data_$N.

(* The lines are evaluated once, when the kernel checks the cast. *)
Lemma check_$N : check_raw Data_$N.lines = true.
Proof.
Time native_cast_no_check (eq_refl true).
Time Qed.
EOT
  echo "$B -> Run_$N.v ($L lines)"
done
