#!/bin/sh
# For each table file DIR/inE given on the command line, write
#   Data_N.v  its lines, verbatim (genraw.py)
#   Run_N.v   the run of the checker on them (needs ExpCheck.v and
#             ExpParse.v only)
# and SampleAll.v, which gives for every line of every file the six
# conditions on what its text says.
# where N is the file name with '-' written 'm' after "in" and '_' elsewhere
# (in-1074 -> inm1074, in0-0 -> in0_0).
# Usage: ./mksample.sh DIR/in1024 DIR/in-1074 ...
#        then: make -jJ sample; make sample-all
set -e
[ $# -gt 0 ] || { echo "usage: $0 table-files..."; exit 1; }

# Write stdin to $1 only if the content changes, so make does not redo
# a run whose file is the same.
put() {
  cat > "$1.new"
  if cmp -s "$1.new" "$1"; then rm "$1.new"; else mv "$1.new" "$1"; fi
}

for F in "$@"; do
  B=$(basename "$F")
  N=$(echo "$B" | sed 's/^in-/inm/; s/-/_/g')
  L=$(wc -l < "$F")
  python3 genraw.py "$F" 0 "$L" Data_$N.v.new
  if cmp -s Data_$N.v.new Data_$N.v; then rm Data_$N.v.new
  else mv Data_$N.v.new Data_$N.v; fi
  put Run_$N.v <<EOT
(* Generated by mksample.sh: the $L lines of the table file $B. *)

From ExpTable9 Require Import ExpCheck ExpParse Data_$N.

(* The lines are evaluated once, when the kernel checks the cast. *)
Lemma check_$N : check_raw Data_$N.lines = true.
Proof.
Time native_cast_no_check (eq_refl true).
Time Qed.
EOT
  echo "$B -> Run_$N.v ($L lines)"
done

# SampleAll.v: the theorem for every file given.
{
  echo "(* Generated by mksample.sh: every line of each table file reads,"
  echo "   by its text, as a line that satisfies the six conditions. *)"
  echo
  echo "From Stdlib Require Import ZArith List PrimStringAxioms."
  echo "From ExpTable9 Require Import ExpCheck ExpParse ExpProof ExpParseSpec."
  for F in "$@"; do
    N=$(basename "$F" | sed 's/^in-/inm/; s/-/_/g')
    echo "From ExpTable9 Require Data_$N Run_$N."
  done
  echo
  echo "Open Scope Z_scope."
  for F in "$@"; do
    B=$(basename "$F")
    N=$(echo "$B" | sed 's/^in-/inm/; s/-/_/g')
    echo
    echo "(* The table file $B. *)"
    echo "Lemma lines_ok_$N : forall s, In s Data_$N.lines ->"
    echo "  exists S0 ex n B, line_text (to_list s) S0 ex n B /\\"
    echo "    line_ok S0 ex n B."
    echo "Proof."
    echo "intros s hin."
    echo "destruct (proj2 (check_rawP _ Run_$N.check_$N) s hin)"
    echo "  as [S0 [ex [n [B [hp hok]]]]]."
    echo "exists S0, ex, n, B; split; [exact (parse_sound _ _ _ _ _ hp)|exact hok]."
    echo "Qed."
  done
} | put SampleAll.v

