#!/usr/bin/env python3
"""Copy lines of a table file verbatim into a Rocq file, as primitive strings.

Usage: genraw.py FILE FIRST COUNT OUT
The lines FIRST+1 .. FIRST+COUNT become the list [lines]; they are read by
ExpParse.parse, in Rocq."""
import sys

def main(path, first, count, out):
    rows = []
    with open(path) as f:
        for i, line in enumerate(f):
            if i < first:
                continue
            if len(rows) == count:
                break
            s = line.rstrip('\n')
            assert '"' not in s
            rows.append(s)
    with open(out, 'w') as g:
        g.write('(* Generated by genraw.py from %s, lines %d to %d. *)\n\n'
                % (path.split('/')[-1], first + 1, first + len(rows)))
        g.write('From Stdlib Require Import List PrimString.\n')
        g.write('Import ListNotations.\nOpen Scope pstring_scope.\n\n')
        g.write('Definition lines : list string := [\n')
        g.write(';\n'.join('  "%s"' % s for s in rows))
        g.write('].\n')

if __name__ == '__main__':
    main(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4])
