#!/bin/sh
# For each table file DIR/inE given on the command line, write
#   Data_N.v  its lines, verbatim (genraw.py)
#   Run_N.v   the run of the checker on them (needs ExpCheck.v and
#             ExpParse.v only)
#   Cover_N.v the check that its lines follow each other (ExpCover.v)
# and SampleAll.v, which gives for every line of every file the six
# conditions on what its text says, and AllCover.v, which gives, for each
# maximal run of files that follow each other in the order of x, every
# double of the run in a line that satisfies the six conditions.
# where N is the file name with '-' written 'm' after "in" and '_' elsewhere
# (in-1074 -> inm1074, in0-0 -> in0_0).
# Usage: ./mksample.sh DIR/in1024 DIR/in-1074 ...
#        then: make -jJ sample; make sample-all
# The files that do not join, or whose lines do not follow each other,
# are reported on stderr.
set -e
[ $# -gt 0 ] || { echo "usage: $0 table-files..."; exit 1; }

# Write stdin to $1 only if the content changes, so make does not redo
# a run whose file is the same.
put() {
  cat > "$1.new"
  if cmp -s "$1.new" "$1"; then rm "$1.new"; else mv "$1.new" "$1"; fi
}

for F in "$@"; do
  B=$(basename "$F")
  N=$(echo "$B" | sed 's/^in-/inm/; s/-/_/g')
  L=$(wc -l < "$F")
  python3 genraw.py "$F" 0 "$L" Data_$N.v.new
  if cmp -s Data_$N.v.new Data_$N.v; then rm Data_$N.v.new
  else mv Data_$N.v.new Data_$N.v; fi
  put Run_$N.v <<EOT
(* Generated by mksample.sh: the $L lines of the table file $B. *)

From ExpTableKL Require Import ExpCheck ExpParse Data_$N.

(* The lines are evaluated once, when the kernel checks the cast. *)
Lemma check_$N : check_raw Data_$N.lines = true.
Proof.
Time native_cast_no_check (eq_refl true).
Time Qed.
EOT
  put Cover_$N.v <<EOT
(* Generated by mksample.sh: the lines of the table file $B follow each
   other. *)

From ExpTableKL Require Import ExpCover Data_$N.

(* Parsing only, no exp. *)
Lemma contig_$N : contig Data_$N.lines = true.
Proof.
Time native_cast_no_check (eq_refl true).
Time Qed.
EOT
  echo "$B -> Run_$N.v, Cover_$N.v ($L lines)"
done

# SampleAll.v: the theorem for every file given.
{
  echo "(* Generated by mksample.sh: every line of each table file reads,"
  echo "   by its text, as a line that satisfies the six conditions. *)"
  echo
  echo "From Stdlib Require Import ZArith List PrimStringAxioms."
  echo "From ExpTableKL Require Import ExpCheck ExpParse ExpProof ExpParseSpec."
  for F in "$@"; do
    N=$(basename "$F" | sed 's/^in-/inm/; s/-/_/g')
    echo "From ExpTableKL Require Data_$N Run_$N."
  done
  echo
  echo "Open Scope Z_scope."
  for F in "$@"; do
    B=$(basename "$F")
    N=$(echo "$B" | sed 's/^in-/inm/; s/-/_/g')
    echo
    echo "(* The table file $B. *)"
    echo "Lemma lines_ok_$N : forall s, In s Data_$N.lines ->"
    echo "  exists S0 ex n k l B, line_text (to_list s) S0 ex n k l B /\\"
    echo "    line_ok S0 ex n k l B."
    echo "Proof."
    echo "intros s hin."
    echo "destruct (check_rawP _ Run_$N.check_$N s hin)"
    echo "  as [S0 [ex [n [k [l [B [hp hok]]]]]]]."
    echo "exists S0, ex, n, k, l, B."
    echo "split; [exact (parse_sound _ _ _ _ _ _ _ hp)|exact hok]."
    echo "Qed."
  done
} | put SampleAll.v


# The files in the order of their first x0, cut into maximal runs: in a
# run, each file starts at the double after the last one of the previous
# file.  One line per run: its files (by N), then the first double
# (S, ex) and the last one.
# The parameter closed of ExpCheck.v: a line ends at x0 + (n - DROP) u.
case $(sed -n 's/^Definition closed : bool := \([a-z]*\)\..*/\1/p' ExpCheck.v)
in
  true) DROP=0 ;;
  false) DROP=1 ;;
  *) echo "closed not found in ExpCheck.v"; exit 1 ;;
esac
RUNS=$(DROP=$DROP python3 - "$@" <<'EOP'
import sys, os
from fractions import Fraction

DROP = int(os.environ["DROP"])

def name(f):
    b = os.path.basename(f)
    if b.startswith('in-'):
        b = 'inm' + b[3:]
    return b.replace('-', '_')

# The double [-]0x1.Fp+-E as (S, ex), x = S 2^(ex - 52).
def x0(tok):
    neg = tok.startswith('-')
    mant, e = tok[3 if neg else 2:].split('p')
    ip, fp = (mant.split('.') + [''])[:2]
    S = int(ip + fp.ljust(13, '0'), 16)
    return (-S if neg else S), int(e)

# The next double upwards, as in ExpCover.next.
def nxt(S, e):
    if S == -2 ** 52:
        return (-(2 ** 53 - 1), e - 1)
    if S + 1 == 2 ** 53:
        return (2 ** 52, e + 1)
    return (S + 1, e)

def val(p):
    return Fraction(p[0]) * Fraction(2) ** (p[1] - 52)

files = []
for f in sys.argv[1:]:
    ls = [l.split() for l in open(f).read().split('\n') if l]
    ok, prev = True, None
    for t in ls:
        S, e = x0(t[0])
        if prev is not None and nxt(*prev) != (S, e):
            ok = False
        prev = (S + int(t[1]) - DROP, e)
    if not ok:
        print('NOT CONTIGUOUS: %s (left out of the runs)' % f,
              file=sys.stderr)
        continue
    files.append((val(x0(ls[0][0])), name(f), x0(ls[0][0]), prev, f))
files.sort()
runs = []
for x in files:
    if runs and nxt(*runs[-1][-1][3]) == x[2]:
        runs[-1].append(x)
    else:
        if runs:
            print('NO JOIN: %s ends at (%d, %d), %s starts at (%d, %d)'
                  % (runs[-1][-1][4], *runs[-1][-1][3], x[4], *x[2]),
                  file=sys.stderr)
        runs.append([x])
for r in runs:
    print(' '.join(x[1] for x in r), '|', *r[0][2], *r[-1][3])
EOP
)

# AllCover.v: for each run, every normal double from its first x0 to its
# last double is in a line that satisfies the six conditions.
{
  echo "(* Generated by mksample.sh: for each maximal run of table files that"
  echo "   follow each other, every normal double from its first x0 to its"
  echo "   last double is x0 + j u in a line whose text satisfies the six"
  echo "   conditions. *)"
  echo
  echo "From Stdlib Require Import ZArith Reals List PrimString."
  echo "From Stdlib Require Import PrimStringAxioms."
  echo "From ExpTableKL Require Import ExpCheck ExpParse ExpProof ExpParseSpec."
  echo "From ExpTableKL Require Import ExpCover."
  echo "Import ListNotations."
  echo "Open Scope Z_scope."
  for F in "$@"; do
    N=$(basename "$F" | sed 's/^in-/inm/; s/-/_/g')
    echo "From ExpTableKL Require Data_$N Run_$N Cover_$N."
  done
  K=0
  echo "$RUNS" | while read -r LINE; do
    [ -n "$LINE" ] || continue
    K=$((K + 1))
    NS=${LINE%|*}
    set -- ${LINE#*|}
    SF=$1; EF=$2; SL=$3; EL=$4
    set -- $NS
    N0=$1; shift
    REST=""
    for N in "$@"; do
      [ -n "$REST" ] && REST="$REST; "
      REST="${REST}Data_$N.lines"
    done
    echo
    echo "(* Run $K: $N0 $* *)"
    echo
    echo "(* The files of run $K after the first one. *)"
    echo "Definition rest$K : list (list string) := [$REST]."
    echo
    echo "(* Each file starts right after the end of the previous one. *)"
    echo "Lemma joins$K : joins (Data_$N0.lines :: rest$K) = true."
    echo "Proof. vm_cast_no_check (eq_refl true). Qed."
    echo
    echo "(* The first double of the run, x0 = $SF * 2^($EF - 52). *)"
    echo "Lemma first$K : firstX Data_$N0.lines = ($SF, $EF)."
    echo "Proof. vm_cast_no_check (@eq_refl (Z * Z) ($SF, $EF)). Qed."
    echo
    echo "(* The last double of the run, $SL * 2^($EL - 52). *)"
    echo "Lemma last$K : lastX (last rest$K Data_$N0.lines) = ($SL, $EL)."
    echo "Proof. vm_cast_no_check (@eq_refl (Z * Z) ($SL, $EL)). Qed."
    echo
    echo "(* Every normal double y = S 2^(ex - 52) of the run is x0 + j u,"
    echo "   j = S - S0, in a line of the table whose text says x0 = S0 u,"
    echo "   u = 2^(ex - 52), n, k, l and B, and S0, ex, n, k, l, B satisfy"
    echo "   the six conditions. *)"
    echo "Theorem cover$K S ex : normal S ->"
    echo "  (IZR ($SF) * bp (uexp ($EF)) <= IZR S * bp (uexp ex) <="
    echo "   IZR ($SL) * bp (uexp ($EL)))%R ->"
    echo "  exists s S0 n k l B, In s (concat (Data_$N0.lines :: rest$K)) /\\"
    echo "    line_text (to_list s) S0 ex n k l B /\\ line_ok S0 ex n k l B /\\"
    echo "    S0 <= S <= S0 + n - drop /\\"
    echo "    (IZR S0 * bp (uexp ex) <= IZR S * bp (uexp ex) <="
    echo "     IZR (S0 + n - drop) * bp (uexp ex))%R."
    echo "Proof."
    echo "intros hS hy."
    echo "assert (hc : Forall (fun l => contig l = true)"
    echo "  (Data_$N0.lines :: rest$K))."
    echo "{ unfold rest$K."
    for N in $N0 "$@"; do
      echo "  constructor; [exact Cover_$N.contig_$N|]."
    done
    echo "  constructor. }"
    echo "assert (hg : Forall lines_good (Data_$N0.lines :: rest$K))."
    echo "{ unfold rest$K."
    for N in $N0 "$@"; do
      echo "  constructor; [exact (check_rawP _ Run_$N.check_$N)|]."
    done
    echo "  constructor. }"
    echo "assert (hy' : (val (fst (firstX Data_$N0.lines))"
    echo "  (snd (firstX Data_$N0.lines)) <= val S ex <="
    echo "  val (fst (lastX (last rest$K Data_$N0.lines)))"
    echo "  (snd (lastX (last rest$K Data_$N0.lines))))%R)"
    echo "  by (rewrite first$K, last$K; exact hy)."
    echo "destruct (cover_ok _ _ hc hg joins$K S ex hS hy')"
    echo "  as [s [S0 [n [k [l [B [hin [hp [hok hr]]]]]]]]]."
    echo "exists s, S0, n, k, l, B; split; [exact hin|]."
    echo "split; [exact (parse_sound _ _ _ _ _ _ _ hp)|]."
    echo "split; [exact hok|exact hr]."
    echo "Qed."
  done
} | put AllCover.v
echo "$RUNS" | awk -F'|' '{ n = split($1, a, " ")
  print "AllCover.v run " NR ": " n " files, " a[1] " .. " a[n] }'
