// Produces fix_table.h, the constants of eval_fix.c, with MPFR.
// The producer is not trusted: each constant is to be certified in Rocq.

#include <stdio.h>
#include <gmp.h>
#include <mpfr.h>
#include "fix.h"

// print z, 0 <= z < 2^(32 FIX_NL), as FIX_NL limbs of 32 bits, lowest first
static void
print_limbs (mpz_t z)
{
  mpz_t q;
  mpz_init_set (q, z);
  printf ("{");
  for (int k = 0; k < FIX_NL; k++) {
    printf ("0x%08lx%s", mpz_get_ui (q) & 0xffffffffUL,
            k < FIX_NL - 1 ? ", " : "");
    mpz_fdiv_q_2exp (q, q, 32);
  }
  printf ("}");
  mpz_clear (q);
}

int
main (void)
{
  mpfr_t t;
  mpz_t z;
  mpfr_init2 (t, 2 * FIX_P);
  mpz_init (z);
  printf ("// generated by gen_fix.c, do not edit\n");
  // T[j] = 2^(j/256), with FIX_P bits after the point, rounded to nearest
  printf ("static const uint32_t fix_T[FIX_TAB][FIX_NL] = {\n");
  for (int j = 0; j < FIX_TAB; j++) {
    mpfr_set_ui (t, j, MPFR_RNDN);
    mpfr_div_ui (t, t, FIX_TAB, MPFR_RNDN);
    mpfr_exp2 (t, t, MPFR_RNDN);
    mpfr_mul_2ui (t, t, FIX_P, MPFR_RNDN);
    mpfr_get_z (z, t, MPFR_RNDN);
    printf ("  ");
    print_limbs (z);
    printf (",\n");
  }
  printf ("};\n");
  // ln 2 / 256, with FIX_P + FIX_LG bits after the point
  mpfr_const_log2 (t, MPFR_RNDN);
  mpfr_div_ui (t, t, FIX_TAB, MPFR_RNDN);
  mpfr_mul_2ui (t, t, FIX_P + FIX_LG, MPFR_RNDN);
  mpfr_get_z (z, t, MPFR_RNDN);
  printf ("static const uint32_t fix_ln2[FIX_NL] = ");
  print_limbs (z);
  printf (";\n");
  // 256 / ln 2, with FIX_LG bits after the point
  mpfr_const_log2 (t, MPFR_RNDN);
  mpfr_ui_div (t, FIX_TAB, t, MPFR_RNDN);
  mpfr_mul_2ui (t, t, FIX_LG, MPFR_RNDN);
  mpfr_get_z (z, t, MPFR_RNDN);
  printf ("static const uint32_t fix_inv[FIX_NL] = ");
  print_limbs (z);
  printf (";\n");
  mpfr_clear (t);
  mpz_clear (z);
  return 0;
}
