// Produces fix_table.h, the constants of eval_fix.c, with MPFR.
// The producer is not trusted: each constant is to be certified in Rocq.

#include <stdio.h>
#include <mpfr.h>
#include "fix.h"

int
main (void)
{
  mpfr_t t;
  mpz_t z;
  mpfr_init2 (t, 2 * FIX_P);
  mpz_init (z);
  printf ("// generated by gen_fix.c, do not edit\n");
  // T[j] = 2^(j/256), with FIX_P bits after the point, rounded to nearest
  printf ("static const char *fix_T[FIX_TAB] = {\n");
  for (int j = 0; j < FIX_TAB; j++) {
    mpfr_set_ui (t, j, MPFR_RNDN);
    mpfr_div_ui (t, t, FIX_TAB, MPFR_RNDN);
    mpfr_exp2 (t, t, MPFR_RNDN);
    mpfr_mul_2ui (t, t, FIX_P, MPFR_RNDN);
    mpfr_get_z (z, t, MPFR_RNDN);
    gmp_printf ("  \"%Zx\",\n", z);
  }
  printf ("};\n");
  // ln 2 / 256, with FIX_P + FIX_LG bits after the point
  mpfr_const_log2 (t, MPFR_RNDN);
  mpfr_div_ui (t, t, FIX_TAB, MPFR_RNDN);
  mpfr_mul_2ui (t, t, FIX_P + FIX_LG, MPFR_RNDN);
  mpfr_get_z (z, t, MPFR_RNDN);
  gmp_printf ("static const char *fix_ln2 = \"%Zx\";\n", z);
  mpfr_clear (t);
  mpz_clear (z);
  return 0;
}
