#!/usr/bin/env python3
"""Turn lines of in_lt into the Rocq table ExpData.v.

Usage: gen.py in_lt FIRST COUNT K L OUT

Each line: x0 in hex, n, then K coefficients of L 64-bit words each,
least significant word first.  K and L must match ncoef and nwords in
ExpCheck.v; if they do not, check_line fails on the length test.  We keep the significand M0 of x0
(x0 = M0 * 2^-43 on [2^9, 2^10)), n, and each coefficient A_i as one integer."""
import sys

def parse_x0(s):
    # 0x1.hhhhhhhhhhhhhp+9
    mant, exp = s[2:].split('p')
    ip, fp = mant.split('.')
    assert ip == '1' and len(fp) <= 13 and int(exp) == 9, s
    fp = fp.ljust(13, '0')
    return int(ip + fp, 16)

def main(path, first, count, K, L, out):
    rows = []
    with open(path) as f:
        for i, line in enumerate(f):
            if i < first:
                continue
            if len(rows) == count:
                break
            w = line.split()
            assert len(w) == 2 + K * L, (i + 1, len(w))
            m = parse_x0(w[0])
            words = [int(x, 16) for x in w[2:]]
            cs = [sum(words[L * k + j] << (64 * j) for j in range(L))
                  for k in range(K)]
            rows.append((m, int(w[1]), cs))
    with open(out, 'w') as g:
        g.write('(* Generated by gen.py from in_lt, lines %d to %d. *)\n\n'
                % (first + 1, first + len(rows)))
        g.write('From Stdlib Require Import ZArith List.\n')
        g.write('Import ListNotations.\nOpen Scope Z_scope.\n\n')
        g.write('Definition table : list (Z * Z * list Z) := [\n')
        g.write(';\n'.join('  (%d, %d, [%s])' % (m, n, '; '.join(map(str, cs)))
                           for m, n, cs in rows))
        g.write('].\n')

if __name__ == '__main__':
    main(sys.argv[1], int(sys.argv[2]), int(sys.argv[3]),
         int(sys.argv[4]), int(sys.argv[5]), sys.argv[6])
