#!/bin/sh
# Cut the table into NS slices and write, for each slice NN,
#   ExpDataNN.v  the lines of the slice (gen.py)
#   ExpRunNN.v   the run of the checker on it (needs ExpCheck.v only)
# and ExpAll.v, which gives table_ok for every slice.
# Usage: ./mkslices.sh IN_LT [NS]
#        then: make -jNS slices; make all-slices
set -e
IN=$1
NS=${2:-15}
[ -f "$IN" ] || { echo "usage: $0 in_lt [nslices]"; exit 1; }

# k and l are read from ExpCheck.v, where they are defined.
K=$(sed -n 's/^Definition k : nat := \([0-9]*\)\..*/\1/p' ExpCheck.v)
L=$(sed -n 's/^Definition l : Z := \([0-9]*\)\..*/\1/p' ExpCheck.v)
TOTAL=$(wc -l < "$IN")
SIZE=$(( (TOTAL + NS - 1) / NS ))
echo "$TOTAL lines, $NS slices of $SIZE, k = $K, l = $L"

s=0
while [ $s -lt $NS ]; do
  NN=$(printf %02d $s)
  FIRST=$((s * SIZE))
  LAST=$((FIRST + SIZE))
  [ $LAST -gt $TOTAL ] && LAST=$TOTAL
  if [ ! -f ExpData$NN.v ]; then
    python3 gen.py "$IN" $FIRST $SIZE $K $L ExpData$NN.v
  fi
  cat > ExpRun$NN.v <<EOT
(* Generated by mkslices.sh: slice $NN of $NS, lines $((FIRST + 1)) to $LAST
   of the table. *)

From ExpTable Require Import ExpCheck ExpData$NN.

(* The table is evaluated once, when the kernel checks the cast. *)
Lemma check$NN : check_table ExpData$NN.table = true.
Proof.
Time native_cast_no_check (eq_refl true).
Time Qed.
EOT
  s=$((s + 1))
done

# ExpAll.v: the six conditions on every slice.
{
  echo "(* Generated by mkslices.sh: every slice of the table is table_ok. *)"
  echo
  echo "From ExpTable Require Import ExpCheck ExpProof."
  s=0
  while [ $s -lt $NS ]; do
    NN=$(printf %02d $s)
    echo "From ExpTable Require ExpData$NN ExpRun$NN."
    s=$((s + 1))
  done
  echo
  s=0
  while [ $s -lt $NS ]; do
    NN=$(printf %02d $s)
    echo "Lemma table_ok$NN : table_ok ExpData$NN.table."
    echo "Proof. exact (check_tableP _ ExpRun$NN.check$NN). Qed."
    s=$((s + 1))
  done
} > ExpAll.v
