#!/bin/sh
# Cut the table into NS slices and write, for each slice NN,
#   ExpDataNN.v  the lines of the slice, verbatim (genraw.py)
#   ExpRunNN.v   the run of the checker on it (needs ExpCheck.v and
#                ExpParse.v only)
# and ExpAll.v, which gives the six conditions for every line.
# Usage: ./mkslices.sh IN_LT [NS]
#        then: make -jNS slices; make all-slices
set -e
IN=$1
NS=${2:-15}
[ -f "$IN" ] || { echo "usage: $0 in_lt [nslices]"; exit 1; }

TOTAL=$(wc -l < "$IN")
SIZE=$(( (TOTAL + NS - 1) / NS ))
echo "$TOTAL lines, $NS slices of $SIZE"

s=0
while [ $s -lt $NS ]; do
  NN=$(printf %02d $s)
  FIRST=$((s * SIZE))
  LAST=$((FIRST + SIZE))
  [ $LAST -gt $TOTAL ] && LAST=$TOTAL
  if [ ! -f ExpData$NN.v ]; then
    python3 genraw.py "$IN" $FIRST $SIZE ExpData$NN.v
  fi
  cat > ExpRun$NN.v <<EOT
(* Generated by mkslices.sh: slice $NN of $NS, lines $((FIRST + 1)) to $LAST
   of the table. *)

From ExpTable Require Import ExpCheck ExpParse ExpData$NN.

(* The lines are evaluated once, when the kernel checks the cast. *)
Lemma check$NN : check_raw ExpData$NN.lines = true.
Proof.
Time native_cast_no_check (eq_refl true).
Time Qed.
EOT
  s=$((s + 1))
done

# ExpAll.v: the six conditions on every line of every slice.
{
  echo "(* Generated by mkslices.sh: every line of the table reads as a line"
  echo "   that satisfies the six conditions. *)"
  echo
  echo "From Stdlib Require Import ZArith List."
  echo "From ExpTable Require Import ExpCheck ExpParse ExpProof."
  s=0
  while [ $s -lt $NS ]; do
    NN=$(printf %02d $s)
    echo "From ExpTable Require ExpData$NN ExpRun$NN."
    s=$((s + 1))
  done
  echo
  s=0
  while [ $s -lt $NS ]; do
    NN=$(printf %02d $s)
    echo "Lemma lines_ok$NN : forall s, In s ExpData$NN.lines ->"
    echo "  exists M0 n B, parse s = Some (M0, n, B) /\\ line_ok M0 n B."
    echo "Proof. exact (proj2 (check_rawP _ ExpRun$NN.check$NN)). Qed."
    s=$((s + 1))
  done
} > ExpAll.v
