#!/bin/sh
# Cut the table into NS slices and write, for each slice NN,
#   ExpDataNN.v  the lines of the slice, verbatim (genraw.py)
#   ExpRunNN.v   the run of the checker on it (needs ExpCheck.v and
#                ExpParse.v only)
#   ExpCoverNN.v the check that its lines follow each other
# and ExpAll.v, which gives the six conditions for every line.
# Usage: ./mkslices.sh IN_LT [NS]
#        then: make -jNS slices; make all-slices
set -e

# Write stdin to $1 only if the content changes, so make does not redo
# a run whose file is the same.
put() {
  cat > "$1.new"
  if cmp -s "$1.new" "$1"; then rm "$1.new"; else mv "$1.new" "$1"; fi
}

IN=$1
NS=${2:-15}
[ -f "$IN" ] || { echo "usage: $0 in_lt [nslices]"; exit 1; }

TOTAL=$(wc -l < "$IN")
SIZE=$(( (TOTAL + NS - 1) / NS ))
echo "$TOTAL lines, $NS slices of $SIZE"

s=0
while [ $s -lt $NS ]; do
  NN=$(printf %02d $s)
  FIRST=$((s * SIZE))
  LAST=$((FIRST + SIZE))
  [ $LAST -gt $TOTAL ] && LAST=$TOTAL
  if [ ! -f ExpData$NN.v ]; then
    python3 genraw.py "$IN" $FIRST $SIZE ExpData$NN.v
  fi
  put ExpRun$NN.v <<EOT
(* Generated by mkslices.sh: slice $NN of $NS, lines $((FIRST + 1)) to $LAST
   of the table. *)

From ExpTable Require Import ExpCheck ExpParse ExpData$NN.

(* The lines are evaluated once, when the kernel checks the cast. *)
Lemma check$NN : check_raw ExpData$NN.lines = true.
Proof.
Time native_cast_no_check (eq_refl true).
Time Qed.
EOT
  put ExpCover$NN.v <<EOT
(* Generated by mkslices.sh: the lines of slice $NN follow each other. *)

From ExpTable Require Import ExpCover ExpData$NN.

(* Parsing only, no exp. *)
Lemma contig$NN : contig ExpData$NN.lines = true.
Proof.
Time native_cast_no_check (eq_refl true).
Time Qed.
EOT
  s=$((s + 1))
done

# The first significand of the table and the last one it covers.
RANGE=$(python3 - "$IN" <<'EOP'
import sys
ls = open(sys.argv[1]).read().split('\n')
ls = [l for l in ls if l]
def m0(l):
    mant = l.split()[0][2:].split('p')[0]
    ip, fp = mant.split('.')
    return int(ip + fp.ljust(13, '0'), 16)
print(m0(ls[0]), m0(ls[-1]) + int(ls[-1].split()[1]))
EOP
)
FIRSTM=${RANGE% *}
LASTM=${RANGE#* }

# ExpAll.v: the six conditions on every line of every slice, and every
# significand from FIRSTM to LASTM in the range of such a line.
{
  echo "(* Generated by mkslices.sh: every line of the table reads as a line"
  echo "   that satisfies the six conditions, and the lines cover every"
  echo "   significand from the first M0 to the last M0 + n. *)"
  echo
  echo "From Stdlib Require Import ZArith List."
  echo "From Stdlib Require Import PrimStringAxioms."
  echo "From ExpTable Require Import ExpCheck ExpParse ExpProof ExpCover."
  echo "From ExpTable Require Import ExpParseSpec."
  echo "Import ListNotations."
  echo "Open Scope Z_scope."
  s=0
  while [ $s -lt $NS ]; do
    NN=$(printf %02d $s)
    echo "From ExpTable Require ExpData$NN ExpRun$NN ExpCover$NN."
    s=$((s + 1))
  done
  echo
  s=0
  while [ $s -lt $NS ]; do
    NN=$(printf %02d $s)
    echo "Lemma lines_ok$NN : forall s, In s ExpData$NN.lines ->"
    echo "  exists M0 n B, parse s = Some (M0, n, B) /\\ line_ok M0 n B."
    echo "Proof. exact (proj2 (check_rawP _ ExpRun$NN.check$NN)). Qed."
    echo
    s=$((s + 1))
  done
  REST=""
  s=1
  while [ $s -lt $NS ]; do
    NN=$(printf %02d $s)
    [ -n "$REST" ] && REST="$REST; "
    REST="${REST}ExpData$NN.lines"
    s=$((s + 1))
  done
  LAST=$(printf %02d $((NS - 1)))
  echo "(* All the slices, the first one apart. *)"
  echo "Definition rest : list (list PrimString.string) := [$REST]."
  echo
  echo "(* Each slice starts right after the end of the previous one. *)"
  echo "Lemma joins_all : joins (ExpData00.lines :: rest) = true."
  echo "Proof. vm_cast_no_check (eq_refl true). Qed."
  echo
  echo "(* The range of significands, x from $FIRSTM * 2^uexp"
  echo "   to $LASTM * 2^uexp. *)"
  echo "Lemma range_all :"
  echo "  firstM ExpData00.lines = $FIRSTM /\\"
  echo "  lastM ExpData$LAST.lines = $LASTM."
  echo "Proof."
  echo "split; [vm_cast_no_check (@eq_refl Z $FIRSTM)|"
  echo "        vm_cast_no_check (@eq_refl Z $LASTM)]."
  echo "Qed."
  echo
  echo "(* Every significand M of the range is in [M0, M0 + n] of a line"
  echo "   that satisfies the six conditions. *)"
  echo "Theorem table_cover M :"
  echo "  firstM ExpData00.lines <= M <= lastM ExpData$LAST.lines ->"
  echo "  exists s M0 n B, In s (concat (ExpData00.lines :: rest)) /\\"
  echo "    parse s = Some (M0, n, B) /\\ line_ok M0 n B /\\ M0 <= M <= M0 + n."
  echo "Proof."
  echo "intros hM; apply (cover_ok ExpData00.lines rest);"
  echo "  [| |exact joins_all|exact hM]."
  printf '%s' '- '
  s=0
  while [ $s -lt $NS ]; do
    printf "constructor; [exact ExpCover%02d.contig%02d|]. " $s $s
    s=$((s + 1))
  done
  echo "constructor."
  printf '%s' '- '
  s=0
  while [ $s -lt $NS ]; do
    printf "constructor; [exact lines_ok%02d|]. " $s
    s=$((s + 1))
  done
  echo "constructor."
  echo "Qed."
  echo
  echo "(* The same, on the text: every significand M of the range is in"
  echo "   [M0, M0 + n] of a line of the table whose text says x0 = M0 2^uexp,"
  echo "   n and B, and M0, n, B satisfy the six conditions. *)"
  echo "Theorem table_cover_text M :"
  echo "  firstM ExpData00.lines <= M <= lastM ExpData$LAST.lines ->"
  echo "  exists s M0 n B, In s (concat (ExpData00.lines :: rest)) /\\"
  echo "    line_text (to_list s) M0 n B /\\ line_ok M0 n B /\\"
  echo "    M0 <= M <= M0 + n."
  echo "Proof."
  echo "intros hM."
  echo "destruct (table_cover M hM) as [s [M0 [n [B [hin [hp [hok hr]]]]]]]."
  echo "exists s, M0, n, B; split; [exact hin|]."
  echo "split; [exact (parse_sound _ _ _ _ hp)|split; [exact hok|exact hr]]."
  echo "Qed."
} | put ExpAll.v
