// Produces exp100_table.h, the constants of exp100.c, with MPFR; with the
// argument "budget", prints the error budget of exp100.c instead.  The
// producer is not trusted: each constant is to be certified in Rocq.

#include <stdio.h>
#include <string.h>
#include <gmp.h>
#include <mpfr.h>
#include "exp100.h"

#define WP 1000       // working precision of MPFR

// print 0 <= z < 2^(32 NL) as NL limbs of 32 bits, least significant first
static void print_limbs(mpz_t z) {
  mpz_t q;
  mpz_init_set(q, z);
  printf("{");
  for (int k = 0; k < NL; k++) {
    printf("0x%08lx%s", mpz_get_ui(q) & 0xffffffffUL, k < NL - 1 ? ", " : "");
    mpz_fdiv_q_2exp(q, q, 32);
  }
  printf("}");
  if (mpz_sgn(q) != 0) fprintf(stderr, "constant too large\n");
  mpz_clear(q);
}

// z = round (t 2^e), rounding rnd
static void scaled(mpz_t z, mpfr_t t, int e, mpfr_rnd_t rnd) {
  mpfr_t u;
  mpfr_init2(u, WP);
  mpfr_mul_2si(u, t, e, MPFR_RNDN);
  mpfr_get_z(z, u, rnd);
  mpfr_clear(u);
}

static void table(void) {
  mpfr_t t, l;
  mpz_t z;
  mpfr_inits2(WP, t, l, (mpfr_ptr) 0);
  mpz_init(z);
  mpfr_const_log2(l, MPFR_RNDN);
  printf("// generated by gen_table.c, do not edit\n\n");
  // T[j] = 2^(j/64) 2^P, to nearest
  printf("// T[j] = 2^(j/64) 2^%d, to nearest\n", P);
  printf("static const uint64_t T[TAB][NL] = {\n");
  for (int j = 0; j < TAB; j++) {
    mpfr_set_ui(t, j, MPFR_RNDN);
    mpfr_div_ui(t, t, TAB, MPFR_RNDN);
    mpfr_exp2(t, t, MPFR_RNDN);
    scaled(z, t, P, MPFR_RNDN);
    printf("  ");
    print_limbs(z);
    printf(",\n");
  }
  printf("};\n\n");
  // C[i] = 2^P / i!, rounded down
  printf("// C[i] = 2^%d / i!, rounded down\n", P);
  printf("static const uint64_t C[DEG + 1][NL] = {\n");
  for (int i = 0; i <= DEG; i++) {
    mpfr_set_ui(t, 1, MPFR_RNDN);
    for (int k = 2; k <= i; k++) mpfr_div_ui(t, t, k, MPFR_RNDN);
    scaled(z, t, P, MPFR_RNDD);
    printf("  ");
    print_limbs(z);
    printf(",\n");
  }
  printf("};\n\n");
  // LN2 = ln2/64 2^(P+32), to nearest
  mpfr_div_ui(t, l, TAB, MPFR_RNDN);
  scaled(z, t, P + LIMB, MPFR_RNDN);
  printf("// LN2 = ln2/64 2^%d, to nearest\n", P + LIMB);
  printf("static const uint64_t LN2[NL] = ");
  print_limbs(z);
  printf(";\n\n");
  // RMAX = ceil(ln2/64 2^P) + 3
  scaled(z, t, P, MPFR_RNDU);
  mpz_add_ui(z, z, 3);
  printf("// RMAX = ceil(ln2/64 2^%d) + 3, the bound on r\n", P);
  printf("static const uint64_t RMAX[NL] = ");
  print_limbs(z);
  printf(";\n\n");
  // INV = 64/ln2 2^25, rounded down
  mpfr_ui_div(t, TAB, l, MPFR_RNDN);
  scaled(z, t, 25, MPFR_RNDD);
  printf("// INV = 64/ln2 2^25, rounded down\n");
  printf("static const uint64_t INV = 0x%lxUL;\n", mpz_get_ui(z));
  mpfr_clears(t, l, (mpfr_ptr) 0);
  mpz_clear(z);
}

// The budget, in units of u = 2^-P (README gives the derivation):
//   er: |r - r*| for r* = x - N ln2/64 and r the computed reduced argument
//   eh: 0 <= p(r) - h, h the Horner value, p the Taylor polynomial
//   R:  0 <= exp(r) - p(r), the Taylor remainder
// and |y u - 2^(j/64) exp(r*)| is at most the sum of
//   2 exp(rmax) (exp(er u) - 1) / u     (the reduced argument)
//   exp(rmax) / 2                       (the table, T_j to nearest)
//   2 (eh + R)                          (Horner and Taylor, T_j u < 2)
//   1                                   (the last product, rounded down)

// print a (in units of u) and its base-2 logarithm relative to 1
static void show(const char *what, mpfr_t a) {
  mpfr_t l;
  mpfr_init2(l, 53);
  mpfr_log2(l, a, MPFR_RNDU);
  printf("%-34s %9.4f u = 2^%.2f\n", what, mpfr_get_d(a, MPFR_RNDU),
         mpfr_get_d(l, MPFR_RNDU) - P);
  mpfr_clear(l);
}

static void budget(void) {
  mpfr_t u, rmax, er, eh, R, a, b, tot;
  mpfr_inits2(WP, u, rmax, er, eh, R, a, b, tot, (mpfr_ptr) 0);
  mpfr_set_ui_2exp(u, 1, -P, MPFR_RNDN);
  // rmax = ln2/64 + 3 u, the bound checked on r
  mpfr_const_log2(rmax, MPFR_RNDU);
  mpfr_div_ui(rmax, rmax, TAB, MPFR_RNDU);
  mpfr_mul_ui(a, u, 3, MPFR_RNDU);
  mpfr_add(rmax, rmax, a, MPFR_RNDU);
  // er = 1 (x truncated) + 1 (floor of n LN2) + n 2^-(P+33) / u, n < 2^17
  mpfr_set_ui_2exp(er, 1, 17 - 33, MPFR_RNDU);
  mpfr_add_ui(er, er, 2, MPFR_RNDU);
  // eh: e_DEG = 1, e_i = e_(i+1) rmax + 2 (the floor and C_i)
  mpfr_set_ui(eh, 1, MPFR_RNDU);
  for (int i = DEG - 1; i >= 0; i--) {
    mpfr_mul(eh, eh, rmax, MPFR_RNDU);
    mpfr_add_ui(eh, eh, 2, MPFR_RNDU);
  }
  // R = rmax^(DEG+1)/(DEG+1)! exp(rmax) / u
  mpfr_pow_ui(R, rmax, DEG + 1, MPFR_RNDU);
  for (int k = 2; k <= DEG + 1; k++) mpfr_div_ui(R, R, k, MPFR_RNDU);
  mpfr_exp(b, rmax, MPFR_RNDU);
  mpfr_mul(R, R, b, MPFR_RNDU);
  mpfr_div(R, R, u, MPFR_RNDU);
  printf("u = 2^-%d, r <= rmax = ln2/64 + 3u = %.6f, DEG = %d\n", P,
         mpfr_get_d(rmax, MPFR_RNDU), DEG);
  show("reduced argument |r - r*|", er);
  show("Horner truncations p(r) - h", eh);
  show("Taylor remainder exp(r) - p(r)", R);
  printf("contributions to |y u - 2^(j/64) exp(r*)|:\n");
  mpfr_mul(a, er, u, MPFR_RNDU);                 // 2 exp(rmax) expm1(er u)/u
  mpfr_expm1(a, a, MPFR_RNDU);
  mpfr_div(a, a, u, MPFR_RNDU);
  mpfr_mul(a, a, b, MPFR_RNDU);
  mpfr_mul_ui(a, a, 2, MPFR_RNDU);
  show("  reduced argument", a);
  mpfr_set(tot, a, MPFR_RNDU);
  mpfr_div_ui(a, b, 2, MPFR_RNDU);               // exp(rmax)/2
  show("  table T_j", a);
  mpfr_add(tot, tot, a, MPFR_RNDU);
  mpfr_add(a, eh, R, MPFR_RNDU);                 // 2 (eh + R)
  mpfr_mul_ui(a, a, 2, MPFR_RNDU);
  show("  Horner and Taylor", a);
  mpfr_add(tot, tot, a, MPFR_RNDU);
  mpfr_set_ui(a, 1, MPFR_RNDU);
  show("  last product", a);
  mpfr_add(tot, tot, a, MPFR_RNDU);
  show("total (relative: y >= 2^P)", tot);
  printf("EXP100_D = %d: %s\n", EXP100_D,
         mpfr_cmp_ui(tot, EXP100_D) <= 0 ? "covers the total" : "TOO SMALL");
  mpfr_clears(u, rmax, er, eh, R, a, b, tot, (mpfr_ptr) 0);
}

int main(int argc, char **argv) {
  if (argc > 1 && !strcmp(argv[1], "budget")) budget();
  else table();
  return 0;
}
