#!/usr/bin/env python3
"""Index the Rocq sources and emit the typst link table doc/lefevre-links.typ.

Every top-level statement and every record field of the files listed in FILES
gets an entry mapping its name to a GitHub URL pointing at its declaration
line.  doc/lefevre-proof.typ imports the table and turns each #name("...")
into a link when the name is found.

Run from anywhere:  python3 doc/mklinks.py [--rev main] [--check]

--check exits non-zero without writing if the table is out of date, and lists
the #name(...) arguments of the document that resolve to nothing.
"""

import argparse
import os
import re
import sys

REPO = "https://github.com/thery/DoubleCover/blob"
SRCDIR = "code/APaul/rocq"

# scanned in this order; on a name collision the first file wins
FILES = ["Dist.v", "Config.v", "AlgFGG.v", "AlgLefevre.v"]

DOC = "doc/lefevre-proof.typ"
OUT = "doc/lefevre-links.typ"

# "Lemma foo p q :", "Record inv (p q : nat) := Inv {", ...
DECL = re.compile(
    r"^(?:Lemma|Theorem|Corollary|Definition|Fixpoint|Record|Example|Fact|"
    r"Proposition|Remark|Inductive)\s+(\w+)")
# a record field, indented, as in "  invx_p1  : forall z, ..."
FIELD = re.compile(r"^\s+(\w+)\s*:(?!=)")


def index(root):
    """name -> (file, line), for every declaration and record field."""
    out, dup = {}, []
    for f in FILES:
        path = os.path.join(root, SRCDIR, f)
        in_record = False
        for lineno, line in enumerate(open(path), 1):
            m = DECL.match(line)
            if m:
                in_record = line.startswith("Record")
                name = m.group(1)
            elif in_record:
                m = FIELD.match(line)
                if not m:
                    if line.rstrip().endswith("}."):
                        in_record = False
                    continue
                name = m.group(1)
            else:
                continue
            if name in out:
                dup.append((name, out[name][0], f))
            else:
                out[name] = (f, lineno)
    return out, dup


def wanted(root):
    """The #name(...) arguments the document actually uses, in order."""
    text = open(os.path.join(root, DOC)).read()
    return re.findall(r'#name\("([^"]*)"\)', text)


# "foo", "step p q d u v", "lefevre1_sound : 2 < N -> ..." link; a formula
# such as "u * p + v * q = M" or "(y < u) = (d < p)" does not.
HEAD = re.compile(r"^(\w+)(?:\s+\w+)*$")


def resolve(arg, idx):
    """The name a #name(...) argument links to, or None if it is a formula."""
    m = HEAD.match(arg.split(":")[0].strip())
    if m and m.group(1) in idx:
        return m.group(1)
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rev", default="main", help="branch, tag or commit")
    ap.add_argument("--check", action="store_true", help="do not write")
    args = ap.parse_args()

    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    idx, dup = index(root)
    for name, first, second in dup:
        print(f"warning: {name} declared in both {first} and {second},"
              f" linking to {first}", file=sys.stderr)

    # a formula is meant to stay unlinked; an identifier that resolves to
    # nothing is a name the sources no longer have, and worth reporting
    used, missing = {}, []
    for arg in wanted(root):
        key = resolve(arg, idx)
        if key is None:
            if HEAD.match(arg.split(":")[0].strip()) and arg not in missing:
                missing.append(arg)
        else:
            used[arg] = idx[key]

    lines = ["// Generated by doc/mklinks.py -- do not edit.",
             f"// Source revision: {args.rev}", "", "#let srclinks = ("]
    for arg in sorted(used):
        f, lineno = used[arg]
        lines.append(f'  "{arg}": "{REPO}/{args.rev}/{SRCDIR}/{f}#L{lineno}",')
    lines += [")", ""]
    table = "\n".join(lines)

    out = os.path.join(root, OUT)
    old = open(out).read() if os.path.exists(out) else None
    if args.check:
        stale = old != table
        for arg in missing:
            print(f"unresolved: #name(\"{arg}\")")
        if stale:
            print(f"{OUT} is out of date")
        sys.exit(1 if stale else 0)

    open(out, "w").write(table)
    print(f"{OUT}: {len(used)} links, {len(missing)} names left unlinked")
    for arg in missing:
        print(f"  unlinked: {arg}")


if __name__ == "__main__":
    main()
