// Recorder: dump the first N triple-double values computed by dd_exp,
// exactly as search() computes them, as a Rocq array of PLAIN Z integers.
// Each field uses a fixed documented scale S: stored integer = value * 2^S.
//   x @ 2^-54   h @ 2^-52   l @ 2^-112   s @ 2^-170
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <mpfr.h>
#include <math.h>
#include <assert.h>

#define SX 54
#define SH 52
#define SL 112
#define SS 170

static void dd_exp (double *h, double *l, double *s, double x) {
  mpfr_t t; mpfr_init2 (t, 3*53+2);
  mpfr_set_d (t, x, MPFR_RNDN);
  mpfr_exp (t, t, MPFR_RNDN);
  *h = mpfr_get_d (t, MPFR_RNDN);
  mpfr_sub_d (t, t, *h, MPFR_RNDN);
  *l = mpfr_get_d (t, MPFR_RNDN);
  mpfr_sub_d (t, t, *l, MPFR_RNDN);
  *s = mpfr_get_d (t, MPFR_RNDN);
  mpfr_clear (t);
}

// exact integer  value * 2^S  (requires the shift e+S to be >= 0)
static long long scaled (double d, int S) {
  if (d == 0.0) return 0;
  int e2; double fr = frexp (d, &e2);        // d = fr*2^e2, 0.5<=|fr|<1
  long long m = (long long) llround (ldexp (fr, 53));  // fr*2^53 exact
  int e = e2 - 53;                            // d = m * 2^e
  int sh = e + S;
  assert (sh >= 0 && "scale too small for this field; increase it");
  return m << sh;                             // exact, fits in 63 bits here
}

#define N 100

int main (void) {
  double x0 = 0.25;
  int e0; frexp (x0, &e0);
  double ux = ldexp (1.0, e0 - 53);
  uint64_t n = 1ul << 20;
  double step = n * ux;                        // 2^-34

  printf ("(* Auto-generated by record.c: first %d dd_exp values of al.c's search\n", N);
  printf ("   over [0.25,0.25001), at x_k = 0.25 + k*2^-34.  All numbers are Z.\n");
  printf ("   Each field is an integer = value * 2^scale, with fixed scales:\n");
  printf ("     x @ 2^-%d   h @ 2^-%d   l @ 2^-%d   s @ 2^-%d\n", SX,SH,SL,SS);
  printf ("   so   x = X*2^-%d   and   exp(x) ~ H*2^-%d + L*2^-%d + S*2^-%d. *)\n\n", SX,SH,SL,SS);
  printf ("From Stdlib Require Import ZArith List.\nImport ListNotations.\nOpen Scope Z_scope.\n\n");
  printf ("Definition sx := %d.  Definition sh := %d.\n", SX, SH);
  printf ("Definition sl := %d.  Definition ss := %d.\n\n", SL, SS);
  printf ("Record entry := { x : Z; h : Z; l : Z; s : Z }.\n\n");
  printf ("Definition dd_data : list entry := [\n");

  double xx = x0;
  for (int k = 0; k < N; k++) {
    double h,l,s; dd_exp (&h,&l,&s,xx);
    printf ("  {| x := %lld; h := %lld; l := %lld; s := %lld |}%s  (* x=%.17g exp=%.17g *)\n",
            scaled(xx,SX), scaled(h,SH), scaled(l,SL), scaled(s,SS),
            (k==N-1?"":" ;"), xx, h+l+s);
    xx += step;
  }
  printf ("].\n");
  return 0;
}
