// Recorder: dump the first N triple-double values computed by dd_exp,
// exactly as search() computes them, as a Rocq array of PLAIN Z integers.
//
// Each field (x, h, l, s) is stored as a single integer = value * 2^scale,
// where the per-field scale is chosen from the recorded region itself: the
// negation of that field's minimum exponent, so every stored integer is
// EXACT and as small as possible.  (A fixed scale cannot work in general:
// a near-exact rounding can make l or s arbitrarily small.)  Integers are
// computed with GMP, so they can be any size.
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <limits.h>
#include <mpfr.h>
#include <gmp.h>
#include <math.h>
#include <assert.h>

// Shift the recorded region so a known hard-to-round case is one of the
// recorded rows.  The case 0x1.00006b1501522p-2 has mantissa HARD_M
// (value HARD_M*2^-54).  Chunk starts advance the mantissa by 2^20 each,
// so starting HIT_CHUNK chunks below HARD_M makes that case land exactly
// at chunk start HIT_CHUNK, i.e. table row HIT_CHUNK has x = HARD_M.
#define HARD_M    4503628371989794LL   // 0x1.00006b1501522p-2 (a hard case)
#define HIT_CHUNK 50LL                 // table row where the hard case sits
#define START_M   (HARD_M - HIT_CHUNK * (1LL << 20))

#define N 100

static void dd_exp (double *h, double *l, double *s, double x) {
  mpfr_t t; mpfr_init2 (t, 3*53+2);
  mpfr_set_d (t, x, MPFR_RNDN);
  mpfr_exp (t, t, MPFR_RNDN);
  *h = mpfr_get_d (t, MPFR_RNDN);
  mpfr_sub_d (t, t, *h, MPFR_RNDN);
  *l = mpfr_get_d (t, MPFR_RNDN);
  mpfr_sub_d (t, t, *l, MPFR_RNDN);
  *s = mpfr_get_d (t, MPFR_RNDN);
  mpfr_clear (t);
}

// exponent e such that d = m * 2^e with m a 53-bit integer (d != 0)
static int expo (double d) { int e2; frexp (d, &e2); return e2 - 53; }

// out = value * 2^S, exact (requires S >= -expo(d))
static void scaled_mpz (mpz_t out, double d, int S) {
  if (d == 0.0) { mpz_set_ui (out, 0); return; }
  int e2; double fr = frexp (d, &e2);
  long long m = (long long) llround (ldexp (fr, 53));  // fr*2^53 exact
  int sh = (e2 - 53) + S;
  assert (sh >= 0);
  mpz_set_si (out, m);
  mpz_mul_2exp (out, out, (unsigned) sh);              // out = m * 2^sh
}

int main (void) {
  double x0 = ldexp ((double) START_M, -54);   // x0 = START_M * 2^-54
  int e0; frexp (x0, &e0);
  double ux = ldexp (1.0, e0 - 53);
  uint64_t n = 1ul << 20;
  double step = n * ux;                        // 2^-34

  // ---- pass 1: compute all entries and each field's minimum exponent ----
  double xs[N], hs[N], ls[N], ss_[N];
  int minx = INT_MAX, minh = INT_MAX, minl = INT_MAX, mins = INT_MAX;
  double xx = x0;
  for (int k = 0; k < N; k++) {
    double h, l, s; dd_exp (&h, &l, &s, xx);
    xs[k] = xx; hs[k] = h; ls[k] = l; ss_[k] = s;
    if (expo (xx) < minx) minx = expo (xx);
    if (expo (h)  < minh) minh = expo (h);
    if (l != 0.0 && expo (l) < minl) minl = expo (l);
    if (s != 0.0 && expo (s) < mins) mins = expo (s);
    xx += step;
  }
  if (minl == INT_MAX) minl = 0;
  if (mins == INT_MAX) mins = 0;
  int SX = -minx, SH = -minh, SL = -minl, SS = -mins;

  // ---- pass 2: emit the Rocq file ----
  printf ("(* Auto-generated by record.c: first %d dd_exp values of al.c's search\n", N);
  printf ("   at chunk starts x_k = x0 + k*2^-34, with x0 = %lld * 2^-54.\n", (long long) START_M);
  printf ("   Region shifted so the hard case 0x1.00006b1501522p-2 (x = %lld*2^-54)\n", (long long) HARD_M);
  printf ("   is exactly table row %lld.  All numbers are Z.\n", (long long) HIT_CHUNK);
  printf ("   Each field is an integer = value * 2^scale, scales chosen per region:\n");
  printf ("     x @ 2^-%d   h @ 2^-%d   l @ 2^-%d   s @ 2^-%d\n", SX, SH, SL, SS);
  printf ("   so   x = X*2^-%d   and   exp(x) ~ H*2^-%d + L*2^-%d + S*2^-%d. *)\n\n", SX, SH, SL, SS);
  printf ("From Stdlib Require Import ZArith List.\nImport ListNotations.\nOpen Scope Z_scope.\n\n");
  printf ("Definition sx := %d.  Definition sh := %d.\n", SX, SH);
  printf ("Definition sl := %d.  Definition ss := %d.\n\n", SL, SS);
  printf ("Record entry := { x : Z; h : Z; l : Z; s : Z }.\n\n");
  printf ("Definition dd_data : list entry := [\n");

  mpz_t X, H, L, S; mpz_inits (X, H, L, S, NULL);
  for (int k = 0; k < N; k++) {
    scaled_mpz (X, xs[k], SX); scaled_mpz (H, hs[k], SH);
    scaled_mpz (L, ls[k], SL); scaled_mpz (S, ss_[k], SS);
    gmp_printf ("  {| x := %Zd; h := %Zd; l := %Zd; s := %Zd |}%s  (* x=%.17g exp=%.17g *)\n",
                X, H, L, S, (k == N-1 ? "" : " ;"), xs[k], hs[k] + ls[k] + ss_[k]);
  }
  mpz_clears (X, H, L, S, NULL);
  printf ("].\n");
  return 0;
}
