(* One row of the upper bound, the computation Rokicki's hcoset does.

   H is the group generated by U, D and the four half turns F2 B2 L2 R2.  It
   has 19 508 428 800 members and the cube splits into 2 217 093 120 rows,
   one for each way a position can look after the flips, the twists and the
   four middle edges are read off.

   A row is named by a move sequence.  Play it from solved and call the
   result p.  The row is every word w with p * w in H.  A word of length d
   is a member of the row solved in d moves, so when every member has been
   found by depth 20 the row needs no more than twenty moves.

   Every level does two things.  The search finds the words of that length
   whose last move is NOT in H.  The prepass takes everything found so far
   and plays each of the ten moves of H on all of it at once, which accounts
   for every word whose last move IS in H -- and that is nearly all of them.

   usage: rubik_row <cap> <maxdepth> "<moves>" [<maxsearch>]   one row
          rubik_row <cap> <maxdepth> build                    the table only
          rubik_row check                                     the checks
          rubik_row hball <n>                                 the prepass alone

   The search runs only while the depth is at most <maxsearch>; above that
   the prepass runs alone.  That is how hcoset reaches twenty: it searches to
   about sixteen and lets the prepass carry the rest.

   EVERY CUT HERE IS SAFE, which is the opposite of the lower bound searches.
   What is proved is that the map filled, not that the search was complete,
   so a cut that loses words can only make the row finish later or not at
   all.  It can never call a member covered when it is not.

   Moves are written the usual way, U R2 F', faces U R F D L B.  An empty
   move string is the row of H itself.

   The pruning table is the prototype's own, phase1_cap<K>.tbl, 2.2 GB, one
   byte a state, shared by every worker through the file system.  It is
   capped: everything at cap+1 or beyond reads cap+1.  Phase 1 distances go
   to 12, so cap 12 is the EXACT table and a cap below it prunes weaker but
   never lies.

   With cap 12 there is a second table worth building, phase1m12.tbl, which
   is what hcoset's phase1prune carries: beside the distance, WHICH MOVES GO
   CLOSER.  A node then tries only the moves the table names instead of all
   eighteen, which Rokicki says "eliminates almost all false paths".  Ours is
   a word a state -- five bits of distance, eighteen of the moves that drop
   it and eighteen of those that do not raise it -- so 17.7 GB against his
   650 MB, because he folds by the sixteen symmetries and we do not.  Build
   it with `mask' and the row uses it if it is there. *)

type cube = { cp : int array; co : int array; ep : int array; eo : int array }

let solved () =
  { cp = Array.init 8 (fun i -> i); co = Array.make 8 0;
    ep = Array.init 12 (fun i -> i); eo = Array.make 12 0 }

let mult a b =
  let r = solved () in
  for i = 0 to 7 do
    r.cp.(i) <- a.cp.(b.cp.(i));
    r.co.(i) <- (a.co.(b.cp.(i)) + b.co.(i)) mod 3
  done;
  for i = 0 to 11 do
    r.ep.(i) <- a.ep.(b.ep.(i));
    r.eo.(i) <- (a.eo.(b.ep.(i)) + b.eo.(i)) land 1
  done;
  r

let basic = [|
  { cp = [|3;0;1;2;4;5;6;7|]; co = Array.make 8 0;
    ep = [|3;0;1;2;4;5;6;7;8;9;10;11|]; eo = Array.make 12 0 };
  { cp = [|4;1;2;0;7;5;6;3|]; co = [|2;0;0;1;1;0;0;2|];
    ep = [|8;1;2;3;11;5;6;7;4;9;10;0|]; eo = Array.make 12 0 };
  { cp = [|1;5;2;3;0;4;6;7|]; co = [|1;2;0;0;2;1;0;0|];
    ep = [|0;9;2;3;4;8;6;7;1;5;10;11|]; eo = [|0;1;0;0;0;1;0;0;1;1;0;0|] };
  { cp = [|0;1;2;3;5;6;7;4|]; co = Array.make 8 0;
    ep = [|0;1;2;3;5;6;7;4;8;9;10;11|]; eo = Array.make 12 0 };
  { cp = [|0;2;6;3;4;1;5;7|]; co = [|0;1;2;0;0;2;1;0|];
    ep = [|0;1;10;3;4;5;9;7;8;2;6;11|]; eo = Array.make 12 0 };
  { cp = [|0;1;3;7;4;5;2;6|]; co = [|0;0;1;2;0;0;2;1|];
    ep = [|0;1;2;11;4;5;6;10;8;9;3;7|]; eo = [|0;0;0;1;0;0;0;1;0;0;1;1|] };
|]

let moves =
  Array.init 18 (fun m ->
    let b = basic.(m / 3) in
    match m mod 3 with
    | 0 -> b | 1 -> mult b b | _ -> mult (mult b b) b)

let n_twist = 2187 and n_flip = 2048 and n_slice = 495

let twist c = let s = ref 0 in for i = 6 downto 0 do s := 3 * !s + c.co.(i) done; !s
let flip  c = let s = ref 0 in for i = 10 downto 0 do s := 2 * !s + c.eo.(i) done; !s

let cnk = Array.make_matrix 13 5 0
let () =
  for n = 0 to 12 do
    cnk.(n).(0) <- 1;
    for k = 1 to 4 do
      cnk.(n).(k) <- (if n = 0 then 0 else cnk.(n-1).(k-1) + cnk.(n-1).(k))
    done
  done

let slice c =
  let a = ref 0 and x = ref 0 in
  for j = 11 downto 0 do
    if c.ep.(j) >= 8 then begin a := !a + cnk.(11 - j).(!x + 1); incr x end
  done;
  !a

let cube_of_twist t =
  let c = solved () and t = ref t and s = ref 0 in
  for i = 0 to 6 do c.co.(i) <- !t mod 3; s := !s + c.co.(i); t := !t / 3 done;
  c.co.(7) <- (3 - !s mod 3) mod 3; c

let cube_of_flip f =
  let c = solved () and f = ref f and s = ref 0 in
  for i = 0 to 10 do c.eo.(i) <- !f land 1; s := !s + c.eo.(i); f := !f lsr 1 done;
  c.eo.(11) <- !s land 1; c

let cube_of_slice s =
  let c = solved () in
  let a = ref s and x = ref 4 in
  let pos = Array.make 12 0 in
  for j = 0 to 11 do
    if !x > 0 && !a >= cnk.(11 - j).(!x) then begin
      a := !a - cnk.(11 - j).(!x); decr x; pos.(j) <- 1
    end
  done;
  let ns = ref 8 and no = ref 0 in
  for j = 0 to 11 do
    if pos.(j) = 1 then begin c.ep.(j) <- !ns; incr ns end
    else begin c.ep.(j) <- !no; incr no end
  done;
  c

let mk_move_table n of_coord coord =
  let t = Array.make_matrix n 18 0 in
  for i = 0 to n - 1 do
    let c = of_coord i in
    for m = 0 to 17 do t.(i).(m) <- coord (mult c moves.(m)) done
  done; t

(* ======================================================================== *)
(*  How a member of the row is written down                                 *)
(* ======================================================================== *)

(* A member of H is three permutations: the eight corners, the eight edges
   outside the middle layer, and the four inside it.  The three have to agree
   on parity, which is why the row has 8! * 8! * 4! / 2 members and not more.

   The bits are laid out the way hcoset does, because that is what makes the
   prepass fast.  A page is one corner permutation.  Inside a page, a GROUP
   of twenty-four bits is a pair of outer edge permutations, and the
   twenty-four bits are the twenty-four middle permutations: the twelve even
   ones in the low half and the twelve odd ones in the high half.  Which of
   the pair a bit means is settled by parity, so nothing is lost. *)

let fact8 = 40320
let fact4 = 24
let ngroup = fact8 / 2                          (* 20 160 *)
let npage = fact8
let mapsize = npage * ngroup                    (* groups in the whole map *)
let rowsize = mapsize * fact4                   (* 19 508 428 800 *)

(* The ten moves of H: the two faces turned any way, the four sides turned
   twice.  Faces are U R F D L B and a move is 3 * face + amount. *)
let hmoves = [| 0; 1; 2; 9; 10; 11; 4; 7; 13; 16 |]
let nh = Array.length hmoves
let f2 = 7

let rank a off n =
  let r = ref 0 in
  for i = 0 to n - 1 do
    let c = ref 0 in
    for j = i + 1 to n - 1 do if a.(off + j) < a.(off + i) then incr c done;
    r := !r * (n - i) + !c
  done; !r

let unrank r n =
  let c = Array.make n 0 and a = Array.make n 0 and r = ref r in
  for i = n - 1 downto 0 do
    c.(i) <- !r mod (n - i); r := !r / (n - i)
  done;
  let left = Array.init n (fun i -> i) and nleft = ref n in
  for i = 0 to n - 1 do
    let k = c.(i) in
    a.(i) <- left.(k);
    for j = k to !nleft - 2 do left.(j) <- left.(j + 1) done;
    decr nleft
  done; a

let parity a off n =
  let p = ref 0 in
  for i = 0 to n - 1 do
    for j = i + 1 to n - 1 do
      if a.(off + j) < a.(off + i) then p := !p lxor 1
    done
  done; !p

(* The outer edges are numbered in pairs that differ by exchanging the two
   cubies 0 and 1, and the low bit of the number is the parity.  Two things
   follow, and the prepass needs both: a move sends a pair to a pair, because
   exchanging two cubies before a move is the same as exchanging them after
   it; and the parity of the number tells which member of the pair is meant,
   so the pair may be stored as one group. *)
let e8num = Array.make fact8 0            (* rank -> number *)
let e8inv = Array.make fact8 0            (* number -> rank *)
let e8rep = Array.make ngroup 0           (* group -> rank of its even member *)

let () =
  let pairid = Array.make fact8 (-1) in
  let next = ref 0 in
  for r = 0 to fact8 - 1 do
    let a = unrank r 8 in
    let b = Array.copy a in
    for i = 0 to 7 do
      if a.(i) = 0 then b.(i) <- 1 else if a.(i) = 1 then b.(i) <- 0
    done;
    let rb = rank b 0 8 in
    let key = if r < rb then r else rb in
    if pairid.(key) < 0 then begin pairid.(key) <- !next; incr next end;
    let g = pairid.(key) in
    let p = parity a 0 8 in
    e8num.(r) <- 2 * g + p;
    e8inv.(2 * g + p) <- r;
    if p = 0 then e8rep.(g) <- r
  done;
  if !next <> ngroup then (prerr_endline "the outer pairs are wrong"; exit 1)

(* The middle four are numbered so that the even ones take the low twelve
   bits and the odd ones the high twelve, an odd one sitting at the place of
   the even one it comes from by F2.  That makes F2 an exchange of the two
   halves and nothing else. *)
let e4bit = Array.make fact4 0            (* rank -> bit, 0..23 *)
let e4of = Array.make fact4 0             (* bit -> rank *)

(* how a move acts on the four middle cubies, as a map of ranks *)
let e4move = Array.make_matrix fact4 18 0
let () =
  (* only the ten moves of H keep the four middle cubies among themselves *)
  for r = 0 to fact4 - 1 do
    let a = unrank r 4 in
    Array.iter (fun m ->
      let ep = moves.(m).ep in
      let b = Array.init 4 (fun i -> a.(ep.(8 + i) - 8)) in
      e4move.(r).(m) <- rank b 0 4) hmoves
  done;
  let i = ref 0 in
  for r = 0 to fact4 - 1 do
    if parity (unrank r 4) 0 4 = 0 then begin
      e4bit.(r) <- !i; e4of.(!i) <- r;
      let r' = e4move.(r).(f2) in
      e4bit.(r') <- 12 + !i; e4of.(12 + !i) <- r';
      incr i
    end
  done;
  if !i <> 12 then (prerr_endline "the middle halves are wrong"; exit 1)

(* where a move sends a page, a group, and the twelve bits of each half *)
let mpage = Array.make_matrix npage nh 0
let mgroup = Array.make_matrix ngroup nh 0
let mswap = Array.make nh 0
let mlo = Array.init nh (fun _ -> Array.make 4096 0)
let mhi = Array.init nh (fun _ -> Array.make 4096 0)

let () =
  for k = 0 to nh - 1 do
    let m = hmoves.(k) in
    let cp = moves.(m).cp and ep = moves.(m).ep in
    for r = 0 to npage - 1 do
      let a = unrank r 8 in
      mpage.(r).(k) <- rank (Array.init 8 (fun i -> a.(cp.(i)))) 0 8
    done;
    for g = 0 to ngroup - 1 do
      let a = unrank e8rep.(g) 8 in
      let b = Array.init 8 (fun i -> a.(ep.(i))) in
      mgroup.(g).(k) <- e8num.(rank b 0 8) lsr 1
    done;
    mswap.(k) <- (if e4bit.(e4move.(e4of.(0)).(m)) >= 12 then 1 else 0);
    for i = 0 to 11 do
      let b = e4bit.(e4move.(e4of.(i)).(m)) in
      mlo.(k).(1 lsl i) <- 1 lsl (b mod 12);
      let b = e4bit.(e4move.(e4of.(12 + i)).(m)) in
      mhi.(k).(1 lsl i) <- 1 lsl (b mod 12)
    done;
    for i = 1 to 4095 do
      let low = i land (-i) in
      mlo.(k).(i) <- mlo.(k).(low) lor mlo.(k).(i - low);
      mhi.(k).(i) <- mhi.(k).(low) lor mhi.(k).(i - low)
    done
  done

let popc = Array.make 4096 0
let () = for i = 1 to 4095 do popc.(i) <- popc.(i lsr 1) + (i land 1) done

(* ---- the moves, written the usual way ----------------------------------- *)

let faces = "URFDLB"

let parse_moves s =
  let l = ref [] and i = ref 0 and n = String.length s in
  while !i < n do
    if s.[!i] = ' ' then incr i
    else begin
      match String.index_opt faces s.[!i] with
      | None -> prerr_endline ("bad move at " ^ string_of_int !i); exit 1
      | Some f ->
        incr i;
        let t =
          if !i < n && s.[!i] = '2' then (incr i; 1)
          else if !i < n && (s.[!i] = '\'' || s.[!i] = '3') then (incr i; 2)
          else if !i < n && s.[!i] = '1' then (incr i; 0)
          else 0 in
        l := (3 * f + t) :: !l
    end
  done;
  List.rev !l

(* The position that undoes this one. *)
let inv c =
  let r = solved () in
  for i = 0 to 7 do
    r.cp.(c.cp.(i)) <- i;
    r.co.(c.cp.(i)) <- (3 - c.co.(i)) mod 3
  done;
  for i = 0 to 11 do
    r.ep.(c.ep.(i)) <- i;
    r.eo.(c.ep.(i)) <- c.eo.(i)
  done;
  r

(* A page, a group and a bit, read back as the member of H they stand for.
   The bit names the middle permutation and the group names a pair of outer
   ones; which of the pair is meant is settled by parity, and the numbering
   carries the parity in its low bit. *)
let unplace page group bit =
  let cp = unrank page 8 in
  let emp = unrank e4of.(bit) 4 in
  let num = 2 * group + (parity cp 0 8 lxor parity emp 0 4) in
  let ud = unrank e8inv.(num) 8 in
  let ep = Array.make 12 0 in
  for i = 0 to 7 do ep.(i) <- ud.(i) done;
  for i = 0 to 3 do ep.(8 + i) <- 8 + emp.(i) done;
  { cp; co = Array.make 8 0; ep; eo = Array.make 12 0 }

(* ======================================================================== *)
(*  Phase two: solving inside H, over its ten moves                         *)
(* ======================================================================== *)

(* A member of H is three permutations and nothing else, so the search is
   over three small coordinates.  Two tables bound the distance: the corners
   with the middle four, and the outer edges with the middle four.  Neither
   is the whole state, so each is a lower bound and the larger of the two is
   the one to use. *)

let p2c = Array.make_matrix fact8 nh 0
let p2u = Array.make_matrix fact8 nh 0
let p2s = Array.make_matrix fact4 nh 0

let () =
  for k = 0 to nh - 1 do
    let m = hmoves.(k) in
    let cp = moves.(m).cp and ep = moves.(m).ep in
    for r = 0 to fact8 - 1 do
      let a = unrank r 8 in
      p2c.(r).(k) <- rank (Array.init 8 (fun i -> a.(cp.(i)))) 0 8;
      p2u.(r).(k) <- rank (Array.init 8 (fun i -> a.(ep.(i)))) 0 8
    done;
    for r = 0 to fact4 - 1 do p2s.(r).(k) <- e4move.(r).(m) done
  done

let n2 = fact8 * fact4

let bfs2 mv =
  let d = Bytes.make n2 '\255' in
  Bytes.set d 0 '\000';
  let cur = ref 0 and go = ref true in
  while !go do
    go := false;
    for i = 0 to n2 - 1 do
      if Char.code (Bytes.get d i) = !cur then begin
        let a = i / fact4 and b = i mod fact4 in
        for k = 0 to nh - 1 do
          let j = mv.(a).(k) * fact4 + p2s.(b).(k) in
          if Char.code (Bytes.get d j) = 255 then begin
            Bytes.set d j (Char.chr (!cur + 1)); go := true end
        done
      end
    done;
    incr cur
  done; d

let pr2c = lazy (bfs2 p2c)
let pr2u = lazy (bfs2 p2u)

(* the H coordinates of a member of H *)
let h2coord q =
  (rank q.cp 0 8, rank q.ep 0 8, rank q.ep 8 4)

(* Deepening search inside H.  Returns the moves, innermost last. *)
let phase2 (c0, u0, s0) budget =
  let tc = Lazy.force pr2c and tu = Lazy.force pr2u in
  let h c u s =
    let a = Char.code (Bytes.unsafe_get tc (c * fact4 + s))
    and b = Char.code (Bytes.unsafe_get tu (u * fact4 + s)) in
    if a > b then a else b in
  let path = Array.make 32 0 in
  let out = ref None in
  let rec go c u s togo n prev =
    if c = 0 && u = 0 && s = 0 then begin
      out := Some (Array.to_list (Array.sub path 0 n)); true end
    else if togo = 0 || h c u s > togo then false
    else begin
      let k = ref 0 and found = ref false in
      while not !found && !k < nh do
        let m = hmoves.(!k) in
        let f = m / 3 in
        if f <> prev then begin
          path.(n) <- m;
          if go p2c.(c).(!k) p2u.(u).(!k) p2s.(s).(!k) (togo - 1) (n + 1) f
          then found := true
        end;
        incr k
      done;
      !found
    end in
  let rec deepen d =
    if d > budget then None
    else if go c0 u0 s0 d 0 (-1) then !out
    else deepen (d + 1) in
  deepen (h c0 u0 s0)

(* ======================================================================== *)
(*  The map, and the prepass                                                *)
(* ======================================================================== *)

(* Two maps, so that the prepass reads what was known at the end of the last
   level and writes what is known at the end of this one.  Playing a move on
   what a move has just reached would count it a level too soon.  Each map
   keeps the low halves apart from the high ones, sixteen bits at a time,
   which is what a machine word reads without unpacking. *)

type map = (int, Bigarray.int16_unsigned_elt, Bigarray.c_layout)
             Bigarray.Array1.t

let nomap : map = Bigarray.Array1.create Bigarray.int16_unsigned
    Bigarray.c_layout 0
let culo = ref nomap and cuhi = ref nomap
let nxlo = ref nomap and nxhi = ref nomap

let alloc () =
  let mk () =
    let a = Bigarray.Array1.create Bigarray.int16_unsigned
        Bigarray.c_layout mapsize in
    Bigarray.Array1.fill a 0; a in
  culo := mk (); cuhi := mk (); nxlo := mk (); nxhi := mk ()

(* where a member of H stands, written into the map being built, counting
   what is new so that a search can be stopped once it has found enough *)
let nset = ref 0

let mark_at cp ep =
  let pg = rank cp 0 8 in
  let gr = e8num.(rank ep 0 8) lsr 1 in
  let bt = e4bit.(rank ep 8 4) in
  let i = pg * ngroup + gr in
  if bt < 12 then begin
    let v = Bigarray.Array1.unsafe_get !nxlo i and m = 1 lsl bt in
    if v land m = 0 then begin
      Bigarray.Array1.unsafe_set !nxlo i (v lor m); incr nset end
  end else begin
    let v = Bigarray.Array1.unsafe_get !nxhi i and m = 1 lsl (bt - 12) in
    if v land m = 0 then begin
      Bigarray.Array1.unsafe_set !nxhi i (v lor m); incr nset end
  end

(* One move of H played on the whole map at once.  A page goes to a page, a
   group to a group, and the twenty-four bits of a group are rearranged by a
   table -- six of the ten moves leave the middle four alone and so leave the
   bits where they are. *)
let prepass k =
  let clo = !culo and chi = !cuhi and nlo = !nxlo and nhi = !nxhi in
  let tlo = mlo.(k) and thi = mhi.(k) and sw = mswap.(k) in
  let mg = Array.make ngroup 0 in
  for g = 0 to ngroup - 1 do mg.(g) <- mgroup.(g).(k) done;
  for pg = 0 to npage - 1 do
    let src = pg * ngroup and dst = mpage.(pg).(k) * ngroup in
    for g = 0 to ngroup - 1 do
      let lo = Bigarray.Array1.unsafe_get clo (src + g) in
      let hi = Bigarray.Array1.unsafe_get chi (src + g) in
      if lo lor hi <> 0 then begin
        let d = dst + Array.unsafe_get mg g in
        let a = Array.unsafe_get tlo lo and b = Array.unsafe_get thi hi in
        let dl, dh = if sw = 0 then a, b else b, a in
        if dl <> 0 then
          Bigarray.Array1.unsafe_set nlo d
            (Bigarray.Array1.unsafe_get nlo d lor dl);
        if dh <> 0 then
          Bigarray.Array1.unsafe_set nhi d
            (Bigarray.Array1.unsafe_get nhi d lor dh)
      end
    done
  done

let count () =
  let lo = !culo and hi = !cuhi in
  let n = ref 0 in
  for i = 0 to mapsize - 1 do
    n := !n + Array.unsafe_get popc (Bigarray.Array1.unsafe_get lo i)
           + Array.unsafe_get popc (Bigarray.Array1.unsafe_get hi i)
  done; !n

(* the whole level, and it is what the row does: carry over what was known,
   play the ten moves on all of it, then let the caller add the search *)
let carry () =
  Bigarray.Array1.blit !culo !nxlo;
  Bigarray.Array1.blit !cuhi !nxhi;
  for k = 0 to nh - 1 do prepass k done

let swapmaps () =
  let a = !culo and b = !cuhi in
  culo := !nxlo; cuhi := !nxhi; nxlo := a; nxhi := b

(* ======================================================================== *)
(*  The checks, which need no table                                         *)
(* ======================================================================== *)

let in_h c = twist c = 0 && flip c = 0 && slice c = 0

(* where a position of H stands: its page, its group, and its bit *)
let place c =
  let g = e8num.(rank c.ep 0 8) in
  let b = e4bit.(rank c.ep 8 4) in
  (rank c.cp 0 8, g lsr 1, b)

let check () =
  let bad = ref 0 in
  let fail s = incr bad; print_string ("FAILED: " ^ s ^ "\n") in

  (* the numbering of the outer edges, and of the middle four *)
  let seen = Array.make fact8 0 in
  Array.iter (fun x -> seen.(x) <- seen.(x) + 1) e8num;
  if Array.exists (fun x -> x <> 1) seen then fail "the outer numbers repeat";
  for r = 0 to fact8 - 1 do
    if e8num.(r) land 1 <> parity (unrank r 8) 0 8 then
      fail "an outer number does not carry its parity"
  done;
  let seen = Array.make fact4 0 in
  Array.iter (fun x -> seen.(x) <- seen.(x) + 1) e4bit;
  if Array.exists (fun x -> x <> 1) seen then fail "the middle bits repeat";
  for r = 0 to fact4 - 1 do
    if (e4bit.(r) >= 12) <> (parity (unrank r 4) 0 4 = 1) then
      fail "a middle bit is in the wrong half"
  done;

  (* the ten moves keep a position in H, and no other move does *)
  for m = 0 to 17 do
    let there = Array.exists (fun x -> x = m) hmoves in
    if in_h moves.(m) <> there then fail (Printf.sprintf "move %d in H" m)
  done;

  (* F2 is the exchange of the two halves and nothing else *)
  let kf2 = ref (-1) in
  Array.iteri (fun k m -> if m = f2 then kf2 := k) hmoves;
  let k = !kf2 in
  if mswap.(k) <> 1 then fail "F2 does not change half";
  for i = 0 to 4095 do
    if mlo.(k).(i) <> i || mhi.(k).(i) <> i then fail "F2 moves a bit"
  done;

  (* THE CHECK THAT MATTERS: where the prepass sends a bit is where the move
     sends the position.  Take a member of H, take a move of H, and compare
     the place of the product with the place the tables give. *)
  Random.self_init ();
  let places = Hashtbl.create 100003 in
  let c = ref (solved ()) in
  for _ = 1 to 200000 do
    c := mult !c moves.(hmoves.(Random.int nh));
    let p = !c in
    if not (in_h p) then fail "a word of H left H";
    let (pg, gr, bt) = place p in
    if pg < 0 || pg >= npage || gr < 0 || gr >= ngroup
       || bt < 0 || bt >= fact4 then fail "the place is out of range";
    let key = (pg * ngroup + gr) * fact4 + bt in
    let sg = (Array.to_list p.cp, Array.to_list p.ep) in
    (match Hashtbl.find_opt places key with
     | Some s when s <> sg -> fail "two members share a place"
     | _ -> Hashtbl.replace places key sg);
    for k = 0 to nh - 1 do
      let q = mult p moves.(hmoves.(k)) in
      let (pg', gr', bt') = place q in
      if mpage.(pg).(k) <> pg' then fail "the page table is wrong";
      if mgroup.(gr).(k) <> gr' then fail "the group table is wrong";
      let half = bt / 12 and j = bt mod 12 in
      let want = if half = 0 then mlo.(k).(1 lsl j) else mhi.(k).(1 lsl j) in
      let half' = if half = 0 then mswap.(k) else 1 - mswap.(k) in
      if want <> 1 lsl (bt' mod 12) || half' <> bt' / 12 then
        fail "the bit table is wrong"
    done
  done;

  (* reading a place back gives the member that was put there *)
  let c = ref (solved ()) in
  for _ = 1 to 20000 do
    c := mult !c moves.(hmoves.(Random.int nh));
    let p = !c in
    let (pg, gr, bt) = place p in
    let q = unplace pg gr bt in
    if q.cp <> p.cp || q.ep <> p.ep then fail "a place reads back wrong"
  done;

  (* phase two solves a member of H, and the word is checked by playing it *)
  let worst = ref 0 in
  for _ = 1 to 300 do
    c := mult !c moves.(hmoves.(Random.int nh));
    let p = !c in
    match phase2 (h2coord p) 20 with
    | None -> fail "phase two found no word"
    | Some w ->
      if List.length w > !worst then worst := List.length w;
      let q = ref p in
      List.iter (fun m ->
        if not (Array.exists (fun x -> x = m) hmoves) then
          fail "phase two used a move outside H";
        q := mult !q moves.(m)) w;
      for i = 0 to 7 do
        if (!q).cp.(i) <> i then fail "phase two did not solve the corners" done;
      for i = 0 to 11 do
        if (!q).ep.(i) <> i then fail "phase two did not solve the edges" done
  done;
  Printf.printf "phase two solved 300 members of H, longest %d moves\n" !worst;

  (* the move rule counts the canonical sequences, which Canseq.v proves are
     18, 243, 3240, 43254 and 577368 *)
  let opp f = (f + 3) mod 6 in
  let rec count d prev =
    if d = 0 then 1L
    else begin
      let n = ref 0L in
      for m = 0 to 17 do
        let f = m / 3 in
        if prev < 0 || not (f = prev || (f = opp prev && f > prev)) then
          n := Int64.add !n (count (d - 1) f)
      done; !n
    end in
  let want = [| 18L; 243L; 3240L; 43254L; 577368L |] in
  for d = 1 to 5 do
    let got = count d (-1) in
    if got <> want.(d - 1) then
      fail (Printf.sprintf "canonical sequences of %d: %Ld, not %Ld"
              d got want.(d - 1))
  done;

  Printf.printf "row %d members, %d pages of %d groups of 24 bits\n"
    rowsize npage ngroup;
  Printf.printf "%d distinct members of H sampled\n" (Hashtbl.length places);
  if !bad = 0 then print_string "all checks passed\n"
  else Printf.printf "%d checks FAILED\n" !bad;
  exit (if !bad = 0 then 0 else 1)

(* ======================================================================== *)

(* The prepass on its own, from the solved position: level n is every member
   of H that ten moves of H reach in n.  For the first levels the same thing
   is worked out one position at a time, with a table of what has been seen,
   and the two must agree. *)
let hball n =
  alloc ();
  mark_at (solved ()).cp (solved ()).ep;
  swapmaps ();
  let seen = Hashtbl.create 1000003 in
  let front = ref [ solved () ] in
  Hashtbl.replace seen (Array.to_list (solved ()).cp,
                        Array.to_list (solved ()).ep) ();
  Printf.printf "level  0 : %d\n%!" (count ());
  for d = 1 to n do
    let t0 = Unix.gettimeofday () in
    carry (); swapmaps ();
    let got = count () in
    let t1 = Unix.gettimeofday () in
    if d <= 5 then begin
      let nf = ref [] in
      List.iter (fun p ->
        Array.iter (fun m ->
          let q = mult p moves.(m) in
          let key = (Array.to_list q.cp, Array.to_list q.ep) in
          if not (Hashtbl.mem seen key) then begin
            Hashtbl.replace seen key (); nf := q :: !nf
          end) hmoves) !front;
      front := !nf;
      let want = Hashtbl.length seen in
      Printf.printf "level %2d : %d, one at a time %d, %s (%.1f s)\n%!"
        d got want (if got = want then "agree" else "DISAGREE") (t1 -. t0)
    end else
      Printf.printf "level %2d : %d (%.1f s)\n%!" d got (t1 -. t0)
  done;
  exit 0

let () =
  if Array.length Sys.argv > 1 && Sys.argv.(1) = "check" then check ();
  if Array.length Sys.argv > 2 && Sys.argv.(1) = "hball" then
    hball (int_of_string Sys.argv.(2));
  let cap = int_of_string Sys.argv.(1) in
  let maxdepth = int_of_string Sys.argv.(2) in
  let arg = if Array.length Sys.argv > 3 then Sys.argv.(3) else "" in
  let maxsearch =
    if Array.length Sys.argv > 4 then int_of_string Sys.argv.(4)
    else maxdepth in
  let build_only = (arg = "build") in

  let mt_twist = mk_move_table n_twist cube_of_twist twist in
  let mt_flip  = mk_move_table n_flip  cube_of_flip  flip  in
  let mt_slice = mk_move_table n_slice cube_of_slice slice in

  (* the pruning table, shared through the file system *)
  let n_all = n_twist * n_flip * n_slice in
  let path = Printf.sprintf "phase1_cap%d.tbl" cap in
  let fresh = not (Sys.file_exists path) in
  let fd = Unix.openfile path
      (if fresh then [Unix.O_RDWR; Unix.O_CREAT] else [Unix.O_RDONLY]) 0o644 in
  let p_all = Bigarray.array1_of_genarray
      (Unix.map_file fd Bigarray.char Bigarray.c_layout fresh [| n_all |]) in
  Unix.close fd;
  if fresh then begin
    Printf.printf "building phase-1 table (%d states, cap %d)...\n%!" n_all cap;
    let t0 = Unix.gettimeofday () in
    Bigarray.Array1.fill p_all (Char.chr (cap + 1));
    Bigarray.Array1.unsafe_set p_all 0 '\000';
    for cur = 0 to cap - 1 do
      let added = ref 0 in
      for t = 0 to n_twist - 1 do
        let mtt = mt_twist.(t) in
        for f = 0 to n_flip - 1 do
          let mtf = mt_flip.(f) in
          let base = (t * n_flip + f) * n_slice in
          for s = 0 to n_slice - 1 do
            if Char.code (Bigarray.Array1.unsafe_get p_all (base + s)) = cur then begin
              let mts = mt_slice.(s) in
              for m = 0 to 17 do
                let j = (mtt.(m) * n_flip + mtf.(m)) * n_slice + mts.(m) in
                if Char.code (Bigarray.Array1.unsafe_get p_all j) > cur + 1 then begin
                  Bigarray.Array1.unsafe_set p_all j (Char.chr (cur + 1)); incr added end
              done
            end
          done
        done
      done;
      Printf.printf "   depth %d -> %d states (%.0f s)\n%!" (cur + 1) !added
        (Unix.gettimeofday () -. t0)
    done
  end;
  (* THE MASK TABLE.  Sweeping it is fast because of how the index is laid
     out: for a twist and a flip held fixed, the eighteen children of all 495
     slice values sit in eighteen runs of 495 bytes, so the whole sweep works
     out of cache. *)
  let mpath = Printf.sprintf "phase1m%d.tbl" cap in
  let want_mask = (arg = "mask") in
  let has_mask = Sys.file_exists mpath in
  if want_mask && has_mask then begin
    Printf.printf "%s is already there\n%!" mpath; exit 0 end;
  (* Cap 12 is not a soundness matter -- the masks are right at any cap,
     because a capped table is still a lower bound and still moves by at most
     one a turn.  It is that the cap does not change the table's SIZE, so a
     lower one would cost the same 17.7 GB and prune worse. *)
  if want_mask && cap < 12 then begin
    prerr_endline "the cap does not change the size, so build it exact: 12";
    exit 1 end;
  let p_msk =
    if not (want_mask || has_mask) then
      Bigarray.Array1.create Bigarray.int Bigarray.c_layout 0
    else begin
      let fd = Unix.openfile mpath
          (if want_mask then [Unix.O_RDWR; Unix.O_CREAT] else [Unix.O_RDONLY])
          0o644 in
      let a = Bigarray.array1_of_genarray
          (Unix.map_file fd Bigarray.int Bigarray.c_layout want_mask
             [| n_all |]) in
      Unix.close fd; a
    end in
  if want_mask then begin
    Printf.printf "building the mask table (%d words, %.1f GB)...\n%!"
      n_all (float_of_int n_all *. 8.0 /. 1e9);
    let t0 = Unix.gettimeofday () in
    let base = Array.make 18 0 in
    for t = 0 to n_twist - 1 do
      let mtt = mt_twist.(t) in
      for f = 0 to n_flip - 1 do
        let mtf = mt_flip.(f) in
        let here = (t * n_flip + f) * n_slice in
        for m = 0 to 17 do
          base.(m) <- (mtt.(m) * n_flip + mtf.(m)) * n_slice done;
        for s = 0 to n_slice - 1 do
          let mts = mt_slice.(s) in
          let d = Char.code (Bigarray.Array1.unsafe_get p_all (here + s)) in
          let down = ref 0 and flat = ref 0 in
          for m = 0 to 17 do
            let dc = Char.code (Bigarray.Array1.unsafe_get p_all
                                  (Array.unsafe_get base m + mts.(m))) in
            if dc < d then down := !down lor (1 lsl m);
            if dc <= d then flat := !flat lor (1 lsl m)
          done;
          Bigarray.Array1.unsafe_set p_msk (here + s)
            (d lor (!down lsl 5) lor (!flat lsl 23))
        done
      done;
      if t land 255 = 0 then
        Printf.printf "   twist %d of %d (%.0f s)\n%!" t n_twist
          (Unix.gettimeofday () -. t0)
    done;
    Printf.printf "the mask table took %.0f s\n%!"
      (Unix.gettimeofday () -. t0);
    exit 0
  end;
  if build_only then exit 0;

  alloc ();
  let repseq = parse_moves arg in
  let rep = ref (solved ()) in
  List.iter (fun m -> rep := mult !rep moves.(m)) repseq;
  let rep = !rep in

  let maxd = 32 in
  let cps = Array.init maxd (fun _ -> Array.make 8 0) in
  let eps = Array.init maxd (fun _ -> Array.make 12 0) in
  let tw = Array.make maxd 0 in
  let fl = Array.make maxd 0 in
  let sl = Array.make maxd 0 in
  let nodes = ref 0L and probes = ref 0L in
  let ish = Array.make 18 false in
  Array.iter (fun m -> ish.(m) <- true) hmoves;

  let heur d =
    Char.code (Bigarray.Array1.unsafe_get p_all
                 ((tw.(d) * n_flip + fl.(d)) * n_slice + sl.(d))) in

  (* A word of the mask table: the distance, then the moves that drop it by
     one, then the moves that do not raise it.  A move changes the distance
     by at most one, so a node with s moves to spare beyond its distance may
     take: any move if s is two or more, a move that does not raise if s is
     one, and only a move that drops if s is nought. *)
  let allmv = (1 lsl 18) - 1 in
  let mdist w = w land 31 in
  let mmask w s =
    if s >= 2 then allmv
    else if s = 1 then (w lsr 23) land allmv
    else (w lsr 5) land allmv in

  let step d m =
    let d' = d + 1 in
    let mcp = moves.(m).cp and mep = moves.(m).ep in
    for i = 0 to 7 do cps.(d').(i) <- cps.(d).(mcp.(i)) done;
    for i = 0 to 11 do eps.(d').(i) <- eps.(d).(mep.(i)) done;
    tw.(d') <- mt_twist.(tw.(d)).(m);
    fl.(d') <- mt_flip.(fl.(d)).(m);
    sl.(d') <- mt_slice.(sl.(d)).(m) in

  let mark d = mark_at cps.(d) eps.(d) in

  (* ROW_NOPREPASS=1 turns the prepass and both cuts off, which is the plain
     search: every canonical word that reaches H, counted.  That is the only
     way to compare with hcoset's published 16 019 916 192 at depth 12. *)
  let nopre = Sys.getenv_opt "ROW_NOPREPASS" <> None in
  let cut = ref true in
  let rcut = 5 in
  (* hcoset's `enoughbits': the last search level need not be run out, only
     run until the map holds enough for the prepasses above it to finish the
     row.  Its own rule at depth 16 is 167 million plus a third of what the
     prepass left, and ROWENOUGH takes that number.  Safe like every other
     cut here -- what is proved is that the map filled. *)
  let enough = ref max_int in
  let rowenough =
    match Sys.getenv_opt "ROWENOUGH" with
    | Some v -> int_of_string v
    | None -> 0 in
  let opp f = (f + 3) mod 6 in
  let idx d = (tw.(d) * n_flip + fl.(d)) * n_slice + sl.(d) in

  (* The same search over the mask table.  A node is handed the moves worth
     trying, so it never builds a position the table has already ruled out --
     the eighteen tries and eighteen table reads a node become three or four
     of each. *)
  let rec dfsm d togo prev mask =
    nodes := Int64.add !nodes 1L;
    if !nset >= !enough then ()
    else if togo = 0 then begin
      probes := Int64.add !probes 1L;
      mark d
    end else begin
      let togo' = togo - 1 in
      for m = 0 to 17 do
        if mask land (1 lsl m) <> 0 then begin
          let f = m / 3 in
          if (togo > 1 || not !cut || not ish.(m))
             && (prev < 0 || not (f = prev || (f = opp prev && f > prev)))
          then begin
            step d m;
            let w = Bigarray.Array1.unsafe_get p_msk (idx (d + 1)) in
            let nd = mdist w in
            if nd <= togo'
               && (not !cut || togo' = nd || togo' + nd >= rcut) then
              dfsm (d + 1) togo' f (mmask w (togo' - nd))
          end
        end
      done
    end in

  (* When the prepass has run, the search looks only for words whose last
     move is not in H: every word that ends in H is a shorter one of the same
     row followed by moves of H, and the prepass has already played those.

     It also refuses, near the bottom, any move that does not go straight at
     H -- that is hcoset's rule, and it is empirical, not proved.  A word
     that wastes a move down there ends in moves of H, so the prepass catches
     it anyway.  Both cuts are off on a level with no prepass. *)
  let rec dfs d togo prev =
    nodes := Int64.add !nodes 1L;
    let nd = heur d in
    if nd <= togo
       && (not !cut || d = 0 || togo = nd || togo + nd >= rcut) then begin
      if togo = 0 then begin
        probes := Int64.add !probes 1L;
        mark d
      end else
        for m = 0 to 17 do
          let f = m / 3 in
          if (togo > 1 || not !cut || not ish.(m))
             && (prev < 0 || not (f = prev || (f = opp prev && f > prev)))
          then begin step d m; dfs (d + 1) (togo - 1) f end
        done
    end in

  for i = 0 to 7 do cps.(0).(i) <- rep.cp.(i) done;
  for i = 0 to 11 do eps.(0).(i) <- rep.ep.(i) done;
  tw.(0) <- twist rep; fl.(0) <- flip rep; sl.(0) <- slice rep;

  Printf.printf "row \"%s\", %d members, table cap %d, first depth %d\n%!"
    arg rowsize cap (heur 0);
  let t0 = Unix.gettimeofday () in
  let done_ = ref 0 in
  let d = ref (heur 0) in
  let d0 = heur 0 in
  while !done_ < rowsize && !d <= maxdepth do
    let before = !done_ in
    (* The prepass costs the same sweep whether the map is full or empty, so
       below some count searching is the cheaper way to the same members.
       hcoset puts it at six million and so do we.  Note what the two sides
       are: with the prepass ON the search is cut and the prepass makes up
       the difference; with it OFF the search is not cut, and an uncut level
       finds every word of that length, including the ones ending in H.  So
       either way the level is complete -- the threshold buys speed, and a
       LOWER one would buy speed at the price of completeness, which is the
       wrong trade when a row is finishing short. *)
    cut := not nopre && !d > d0 && (!done_ > 6000000 || !d > maxsearch);
    let t1 = Unix.gettimeofday () in
    if !cut then carry () else begin
      Bigarray.Array1.blit !culo !nxlo; Bigarray.Array1.blit !cuhi !nxhi
    end;
    let t2 = Unix.gettimeofday () in
    nodes := 0L; probes := 0L;
    (* the threshold is on the whole map, so what the prepass left has to be
       counted before the search starts; that costs a couple of seconds and
       only on the level the threshold applies to *)
    enough := max_int;
    if rowenough > 0 && !d = maxsearch then begin
      swapmaps (); nset := count (); swapmaps ();
      enough := rowenough
    end;
    if !d <= maxsearch then begin
      if has_mask then begin
        let w = Bigarray.Array1.unsafe_get p_msk (idx 0) in
        let nd = mdist w in
        if nd <= !d then dfsm 0 !d (-1) (mmask w (!d - nd))
      end else dfs 0 !d (-1)
    end;
    let t3 = Unix.gettimeofday () in
    swapmaps ();
    done_ := count ();
    Printf.printf
      "depth %2d : %Ld nodes, %Ld solutions, %d new, %d done, \
       prepass %.1f s, search %.1f s%s\n%!"
      !d !nodes !probes (!done_ - before) !done_ (t2 -. t1) (t3 -. t2)
      (if !enough < max_int && !nset >= !enough then " (stopped early)"
       else "");
    incr d
  done;
  Printf.printf "row \"%s\": %d of %d after depth %d, %.1f s\n%!"
    arg !done_ rowsize (!d - 1) (Unix.gettimeofday () -. t0);

  (* ---- what is left over ------------------------------------------------ *)
  (* A row that stops short leaves a few members unmarked, and each of those
     is settled on its own by a WORD: play it and the position is solved.
     hcoset does the same and hands them to Kociemba's two phase algorithm.
     Nothing here has to be trusted -- the word is checked by playing it. *)
  (* ROWLEFT is how many to settle, not a flag: these are the deepest members
     of the row, so phase one gets them into H with about ten moves to spare
     and a member of H often needs more than that.  Most phase one solutions
     therefore lead nowhere and the solver works through many of them.  A
     sample is what tells us the shape; ROWLEFT=0 means all of them. *)
  let rowleft =
    match Sys.getenv_opt "ROWLEFT" with
    | Some v -> (try int_of_string v with _ -> 1000)
    | None -> -1 in
  if rowleft >= 0 && !done_ < rowsize then begin
    let irep = inv rep in
    let mx = 22 in
    let cps = Array.init mx (fun _ -> Array.make 8 0) in
    let eps = Array.init mx (fun _ -> Array.make 12 0) in
    let tws = Array.make mx 0 and fls = Array.make mx 0
    and sls = Array.make mx 0 in
    let path = Array.make mx 0 in
    let ix d = (tws.(d) * n_flip + fls.(d)) * n_slice + sls.(d) in
    let step1 d m =
      let d' = d + 1 in
      let mcp = moves.(m).cp and mep = moves.(m).ep in
      for i = 0 to 7 do cps.(d').(i) <- cps.(d).(mcp.(i)) done;
      for i = 0 to 11 do eps.(d').(i) <- eps.(d).(mep.(i)) done;
      tws.(d') <- mt_twist.(tws.(d)).(m);
      fls.(d') <- mt_flip.(fls.(d)).(m);
      sls.(d') <- mt_slice.(sls.(d)).(m) in
    let out = ref None in
    (* A LEFTOVER IS A DEEP POSITION, so phase one reaches H with little to
       spare and most phase one solutions lead to an element of H that cannot
       be finished inside what is left.  The solver then works through
       millions of them.  So it gives up on a length after this many and goes
       to the next, and if the position itself will not go it is tried
       inverted, which is a different tree -- that is the cheap end of what
       Rokicki does on six axes. *)
    let p1cap = 200000 in
    let tried = ref 0 in
    (* phase one takes it into H, phase two the rest of the way *)
    let rec p1 d togo prev mask =
      if togo = 0 then begin
        if !tried >= p1cap then true          (* give up on this length *)
        else begin
          incr tried;
          let hq = { cp = cps.(d); co = Array.make 8 0;
                     ep = eps.(d); eo = Array.make 12 0 } in
          match phase2 (h2coord hq) (20 - d) with
          | Some w2 ->
            out := Some (Array.to_list (Array.sub path 0 d) @ w2); true
          | None -> false
        end
      end else begin
        let togo' = togo - 1 in
        let r = ref false and m = ref 0 in
        while not !r && !m < 18 do
          if mask land (1 lsl !m) <> 0 then begin
            let f = !m / 3 in
            if prev < 0 || not (f = prev || (f = opp prev && f > prev))
            then begin
              step1 d !m; path.(d) <- !m;
              let w = Bigarray.Array1.unsafe_get p_msk (ix (d + 1)) in
              let nd = mdist w in
              if nd <= togo' && p1 (d + 1) togo' f (mmask w (togo' - nd))
              then r := true
            end
          end;
          incr m
        done; !r
      end in
    let solve1 q =
      Array.blit q.cp 0 cps.(0) 0 8;
      Array.blit q.ep 0 eps.(0) 0 12;
      tws.(0) <- twist q; fls.(0) <- flip q; sls.(0) <- slice q;
      out := None;
      let w0 = Bigarray.Array1.unsafe_get p_msk (ix 0) in
      let nd0 = mdist w0 in
      let l = ref nd0 in
      while !out = None && !l <= 20 do
        tried := 0;
        ignore (p1 0 !l (-1) (mmask w0 (!l - nd0)));
        incr l
      done;
      !out in
    (* a move undone, and a word undone: play it backwards, each move the
       other way *)
    let invmv m = 3 * (m / 3) + (2 - m mod 3) in
    let solve20 q =
      match solve1 q with
      | Some w -> Some w
      | None ->
        (match solve1 (inv q) with
         | Some w -> Some (List.rev_map invmv w)
         | None -> None) in
    (* a move, written the usual way, so a witness can be read by eye        *)
    let mvname m =
      Printf.sprintf "%c%s" faces.[m / 3]
        (match m mod 3 with 0 -> "" | 1 -> "2" | _ -> "'") in
    let solves q w =
      let c = ref q in
      List.iter (fun m -> c := mult !c moves.(m)) w;
      let ok = ref true in
      for i = 0 to 7 do
        if (!c).cp.(i) <> i || (!c).co.(i) <> 0 then ok := false done;
      for i = 0 to 11 do
        if (!c).ep.(i) <> i || (!c).eo.(i) <> 0 then ok := false done;
      !ok in
    Printf.printf "the leftovers, one word each%s\n%!"
      (if rowleft = 0 then "" else Printf.sprintf " (the first %d)" rowleft);
    let t1 = Unix.gettimeofday () in
    let seen = ref 0 and bad = ref 0 and worst = ref 0 and hist = Array.make 25 0 in
    let clo = !culo and chi = !cuhi in
    (try
    for pg = 0 to npage - 1 do
      for g = 0 to ngroup - 1 do
        let i = pg * ngroup + g in
        let lo = Bigarray.Array1.unsafe_get clo i
        and hi = Bigarray.Array1.unsafe_get chi i in
        if lo <> 4095 || hi <> 4095 then
          for b = 0 to 23 do
            let set = if b < 12 then lo land (1 lsl b) <> 0
                      else hi land (1 lsl (b - 12)) <> 0 in
            if not set then begin
              incr seen;
              let q = mult irep (unplace pg g b) in
              (match solve20 q with
               | Some w when List.length w <= 20 && solves q w ->
                 let n = List.length w in
                 hist.(n) <- hist.(n) + 1;
                 if n > !worst then worst := n;
                 (* the witness itself: the place, then the word, as move
                    numbers for a machine and as moves for a reader *)
                 Printf.printf "LEFT %d %d %d %d%s   # %s\n"
                   pg g b n
                   (String.concat ""
                      (List.map (fun m -> " " ^ string_of_int m) w))
                   (String.concat " " (List.map mvname w))
               | _ ->
                 incr bad;
                 Printf.printf "LEFT %d %d %d NONE\n" pg g b);
              Printf.printf "   %d done, %d without a word, %.1f s\n%!"
                !seen !bad (Unix.gettimeofday () -. t1);
              if rowleft > 0 && !seen >= rowleft then raise Exit
            end
          done
      done
    done
    with Exit -> ());
    Printf.printf "%d settled, %d without a word of 20, longest %d, %.1f s\n%!"
      !seen !bad !worst (Unix.gettimeofday () -. t1);
    for n = 0 to 24 do
      if hist.(n) > 0 then Printf.printf "   %2d moves : %d\n" n hist.(n) done
  end
