(* One row of the upper bound, the computation Rokicki's hcoset does.

   H is the group generated by U, D and the four half turns F2 B2 L2 R2.  It
   has 19 508 428 800 members and the cube splits into 2 217 093 120 rows,
   one for each way a position can look after the flips, the twists and the
   four middle edges are read off.

   A row is named by a move sequence.  Play it from solved and call the
   result p.  The row is every word w with p * w in H.  A word of length d
   found by the search is a member of the row solved in d moves, so when
   every member has been found the row needs no more moves than the depth
   reached.  The search deepens until all 19 508 428 800 are marked.

   usage: rubik_row <cap> <maxdepth> "<moves>"    one row
          rubik_row <cap> <maxdepth> build        the pruning table only

   Moves are written the usual way, U R2 F', faces U R F D L B.  An empty
   move string is the row of H itself.

   The pruning table is the prototype's own, phase1_cap<K>.tbl, 2.2 GB, one
   byte a state, shared by every worker through the file system.  It is
   capped: everything at cap+1 or beyond reads cap+1.  Phase 1 distances go
   to 12, so a cap below 12 prunes weaker but never lies. *)

type cube = { cp : int array; co : int array; ep : int array; eo : int array }

let solved () =
  { cp = Array.init 8 (fun i -> i); co = Array.make 8 0;
    ep = Array.init 12 (fun i -> i); eo = Array.make 12 0 }

let mult a b =
  let r = solved () in
  for i = 0 to 7 do
    r.cp.(i) <- a.cp.(b.cp.(i));
    r.co.(i) <- (a.co.(b.cp.(i)) + b.co.(i)) mod 3
  done;
  for i = 0 to 11 do
    r.ep.(i) <- a.ep.(b.ep.(i));
    r.eo.(i) <- (a.eo.(b.ep.(i)) + b.eo.(i)) land 1
  done;
  r

let basic = [|
  { cp = [|3;0;1;2;4;5;6;7|]; co = Array.make 8 0;
    ep = [|3;0;1;2;4;5;6;7;8;9;10;11|]; eo = Array.make 12 0 };
  { cp = [|4;1;2;0;7;5;6;3|]; co = [|2;0;0;1;1;0;0;2|];
    ep = [|8;1;2;3;11;5;6;7;4;9;10;0|]; eo = Array.make 12 0 };
  { cp = [|1;5;2;3;0;4;6;7|]; co = [|1;2;0;0;2;1;0;0|];
    ep = [|0;9;2;3;4;8;6;7;1;5;10;11|]; eo = [|0;1;0;0;0;1;0;0;1;1;0;0|] };
  { cp = [|0;1;2;3;5;6;7;4|]; co = Array.make 8 0;
    ep = [|0;1;2;3;5;6;7;4;8;9;10;11|]; eo = Array.make 12 0 };
  { cp = [|0;2;6;3;4;1;5;7|]; co = [|0;1;2;0;0;2;1;0|];
    ep = [|0;1;10;3;4;5;9;7;8;2;6;11|]; eo = Array.make 12 0 };
  { cp = [|0;1;3;7;4;5;2;6|]; co = [|0;0;1;2;0;0;2;1|];
    ep = [|0;1;2;11;4;5;6;10;8;9;3;7|]; eo = [|0;0;0;1;0;0;0;1;0;0;1;1|] };
|]

let moves =
  Array.init 18 (fun m ->
    let b = basic.(m / 3) in
    match m mod 3 with
    | 0 -> b | 1 -> mult b b | _ -> mult (mult b b) b)

let n_twist = 2187 and n_flip = 2048 and n_slice = 495

let twist c = let s = ref 0 in for i = 6 downto 0 do s := 3 * !s + c.co.(i) done; !s
let flip  c = let s = ref 0 in for i = 10 downto 0 do s := 2 * !s + c.eo.(i) done; !s

let cnk = Array.make_matrix 13 5 0
let () =
  for n = 0 to 12 do
    cnk.(n).(0) <- 1;
    for k = 1 to 4 do
      cnk.(n).(k) <- (if n = 0 then 0 else cnk.(n-1).(k-1) + cnk.(n-1).(k))
    done
  done

let slice c =
  let a = ref 0 and x = ref 0 in
  for j = 11 downto 0 do
    if c.ep.(j) >= 8 then begin a := !a + cnk.(11 - j).(!x + 1); incr x end
  done;
  !a

let cube_of_twist t =
  let c = solved () and t = ref t and s = ref 0 in
  for i = 0 to 6 do c.co.(i) <- !t mod 3; s := !s + c.co.(i); t := !t / 3 done;
  c.co.(7) <- (3 - !s mod 3) mod 3; c

let cube_of_flip f =
  let c = solved () and f = ref f and s = ref 0 in
  for i = 0 to 10 do c.eo.(i) <- !f land 1; s := !s + c.eo.(i); f := !f lsr 1 done;
  c.eo.(11) <- !s land 1; c

let cube_of_slice s =
  let c = solved () in
  let a = ref s and x = ref 4 in
  let pos = Array.make 12 0 in
  for j = 0 to 11 do
    if !x > 0 && !a >= cnk.(11 - j).(!x) then begin
      a := !a - cnk.(11 - j).(!x); decr x; pos.(j) <- 1
    end
  done;
  let ns = ref 8 and no = ref 0 in
  for j = 0 to 11 do
    if pos.(j) = 1 then begin c.ep.(j) <- !ns; incr ns end
    else begin c.ep.(j) <- !no; incr no end
  done;
  c

let mk_move_table n of_coord coord =
  let t = Array.make_matrix n 18 0 in
  for i = 0 to n - 1 do
    let c = of_coord i in
    for m = 0 to 17 do t.(i).(m) <- coord (mult c moves.(m)) done
  done; t

(* ---- the row's own numbers ---------------------------------------------- *)

(* 8! corner permutations, 8! permutations of the eight edges outside the
   middle layer, 4! of the four inside it.  A position of H has the same
   parity on its corners as on its edges, which halves the count. *)
let fact8 = 40320
let fact4 = 24
let rowsize = fact8 * fact8 * fact4 / 2

(* One page a corner permutation, one bit an edge permutation. *)
let pagebits = fact8 * fact4 / 2
let pagebytes = pagebits / 8

(* Where a permutation stands among the permutations of its own kind, by the
   usual count of how many later entries are smaller. *)
let rank8 a off =
  let r = ref 0 in
  for i = 0 to 7 do
    let c = ref 0 in
    for j = i + 1 to 7 do if a.(off + j) < a.(off + i) then incr c done;
    r := !r * (8 - i) + !c
  done; !r

let rank4 a off =
  let r = ref 0 in
  for i = 0 to 3 do
    let c = ref 0 in
    for j = i + 1 to 3 do if a.(off + j) < a.(off + i) then incr c done;
    r := !r * (4 - i) + !c
  done; !r

(* ---- the moves, written the usual way ----------------------------------- *)

let faces = "URFDLB"

let parse_moves s =
  let l = ref [] and i = ref 0 and n = String.length s in
  while !i < n do
    if s.[!i] = ' ' then incr i
    else begin
      let f = String.index_opt faces s.[!i] in
      (match f with
       | None -> prerr_endline ("bad move at " ^ string_of_int !i); exit 1
       | Some f ->
         incr i;
         let t =
           if !i < n && s.[!i] = '2' then (incr i; 1)
           else if !i < n && (s.[!i] = '\'' || s.[!i] = '3') then (incr i; 2)
           else if !i < n && s.[!i] = '1' then (incr i; 0)
           else 0 in
         l := (3 * f + t) :: !l)
    end
  done;
  List.rev !l

(* ---- the checks, which need no table ------------------------------------ *)

(* The ten moves of H: the two faces turned any way, the four sides turned
   twice.  Faces are U R F D L B and a move is 3 * face + amount, the amounts
   being a quarter turn, a half turn and a quarter turn back. *)
let hmoves = [| 0; 1; 2; 9; 10; 11; 4; 7; 13; 16 |]

let in_h c = twist c = 0 && flip c = 0 && slice c = 0

let parity a n off =
  let p = ref 0 in
  for i = 0 to n - 1 do
    for j = i + 1 to n - 1 do
      if a.(off + j) < a.(off + i) then p := !p lxor 1
    done
  done; !p

let check () =
  let bad = ref 0 in
  let fail s = incr bad; print_string ("FAILED: " ^ s ^ "\n") in

  (* the ranks number each kind of permutation once each *)
  let seen = Array.make fact8 0 in
  let a = Array.make 8 0 in
  let rec perm8 k =
    if k = 8 then seen.(rank8 a 0) <- seen.(rank8 a 0) + 1
    else for v = 0 to 7 do
      let free = ref true in
      for i = 0 to k - 1 do if a.(i) = v then free := false done;
      if !free then begin a.(k) <- v; perm8 (k + 1) end
    done in
  perm8 0;
  if Array.exists (fun x -> x <> 1) seen then fail "rank8 is not a bijection";

  let seen4 = Array.make fact4 0 in
  let b = Array.make 12 0 in
  let rec perm4 k =
    if k = 4 then seen4.(rank4 b 8) <- seen4.(rank4 b 8) + 1
    else for v = 8 to 11 do
      let free = ref true in
      for i = 0 to k - 1 do if b.(8 + i) = v then free := false done;
      if !free then begin b.(8 + k) <- v; perm4 (k + 1) end
    done in
  perm4 0;
  if Array.exists (fun x -> x <> 1) seen4 then fail "rank4 is not a bijection";

  (* two middle permutations whose ranks differ only in the last place have
     opposite parity, which is what lets the last place be dropped *)
  let par4 = Array.make fact4 0 in
  let rec par k =
    if k = 4 then par4.(rank4 b 8) <- parity b 4 8
    else for v = 8 to 11 do
      let free = ref true in
      for i = 0 to k - 1 do if b.(8 + i) = v then free := false done;
      if !free then begin b.(8 + k) <- v; par (k + 1) end
    done in
  par 0;
  for r = 0 to fact4 / 2 - 1 do
    if par4.(2 * r) = par4.(2 * r + 1) then fail "the middle pairs agree"
  done;

  (* the ten moves keep a position in H, and no other move does *)
  for m = 0 to 17 do
    let there = Array.exists (fun x -> x = m) hmoves in
    if in_h moves.(m) <> there then fail (Printf.sprintf "move %d in H" m)
  done;

  (* a member of H keeps the two kinds of edge apart, its corners and its
     edges have the same parity, and its index is in range and one to one *)
  Random.self_init ();
  let tbl = Hashtbl.create 100003 in
  let seenpos = Hashtbl.create 100003 in
  let c = ref (solved ()) in
  for _ = 1 to 200000 do
    c := mult !c moves.(hmoves.(Random.int 10));
    let p = !c in
    if not (in_h p) then fail "a word of H left H";
    for j = 0 to 7 do if p.ep.(j) > 7 then fail "a middle edge came out" done;
    for j = 8 to 11 do if p.ep.(j) < 8 then fail "an outer edge went in" done;
    let pc = parity p.cp 8 0 in
    let pe = parity p.ep 8 0 lxor parity p.ep 4 8 in
    if pc <> pe then fail "the two parities differ";
    let page = rank8 p.cp 0 in
    let off = rank8 p.ep 0 * 12 + (rank4 p.ep 8 lsr 1) in
    if page < 0 || page >= fact8 || off < 0 || off >= pagebits then
      fail "the index is out of range";
    let key = page * pagebits + off in
    let sig_ = (Array.to_list p.cp, Array.to_list p.ep) in
    (match Hashtbl.find_opt tbl key with
     | Some s when s <> sig_ -> fail "two positions share an index"
     | _ -> Hashtbl.replace tbl key sig_);
    (match Hashtbl.find_opt seenpos sig_ with
     | Some k when k <> key -> fail "one position has two indices"
     | _ -> Hashtbl.replace seenpos sig_ key)
  done;
  (* the move rule counts the canonical sequences, which Canseq.v proves are
     18, 243, 3240, 43254 and 577368 *)
  let opp f = (f + 3) mod 6 in
  let rec count d prev =
    if d = 0 then 1L
    else begin
      let n = ref 0L in
      for m = 0 to 17 do
        let f = m / 3 in
        if prev < 0 || not (f = prev || (f = opp prev && f > prev)) then
          n := Int64.add !n (count (d - 1) f)
      done; !n
    end in
  let want = [| 18L; 243L; 3240L; 43254L; 577368L |] in
  for d = 1 to 5 do
    let got = count d (-1) in
    if got <> want.(d - 1) then
      fail (Printf.sprintf "canonical sequences of %d: %Ld, not %Ld"
              d got want.(d - 1))
  done;

  Printf.printf "row size %d, %d pages of %d bits\n" rowsize fact8 pagebits;
  Printf.printf "%d distinct members of H sampled\n" (Hashtbl.length tbl);
  if !bad = 0 then print_string "all checks passed\n"
  else Printf.printf "%d checks FAILED\n" !bad;
  exit (if !bad = 0 then 0 else 1)

let () =
  if Array.length Sys.argv > 1 && Sys.argv.(1) = "check" then check ();
  let cap = int_of_string Sys.argv.(1) in
  let maxdepth = int_of_string Sys.argv.(2) in
  let arg = if Array.length Sys.argv > 3 then Sys.argv.(3) else "" in
  let build_only = (arg = "build") in

  let mt_twist = mk_move_table n_twist cube_of_twist twist in
  let mt_flip  = mk_move_table n_flip  cube_of_flip  flip  in
  let mt_slice = mk_move_table n_slice cube_of_slice slice in

  (* the pruning table, shared through the file system *)
  let n_all = n_twist * n_flip * n_slice in
  let path = Printf.sprintf "phase1_cap%d.tbl" cap in
  let fresh = not (Sys.file_exists path) in
  let fd = Unix.openfile path
      (if fresh then [Unix.O_RDWR; Unix.O_CREAT] else [Unix.O_RDONLY]) 0o644 in
  let p_all = Bigarray.array1_of_genarray
      (Unix.map_file fd Bigarray.char Bigarray.c_layout fresh [| n_all |]) in
  Unix.close fd;
  if fresh then begin
    Printf.printf "building phase-1 table (%d states, cap %d)...\n%!" n_all cap;
    let t0 = Unix.gettimeofday () in
    Bigarray.Array1.fill p_all (Char.chr (cap + 1));
    Bigarray.Array1.unsafe_set p_all 0 '\000';
    for cur = 0 to cap - 1 do
      let added = ref 0 in
      for t = 0 to n_twist - 1 do
        let mtt = mt_twist.(t) in
        for f = 0 to n_flip - 1 do
          let mtf = mt_flip.(f) in
          let base = (t * n_flip + f) * n_slice in
          for s = 0 to n_slice - 1 do
            if Char.code (Bigarray.Array1.unsafe_get p_all (base + s)) = cur then begin
              let mts = mt_slice.(s) in
              for m = 0 to 17 do
                let j = (mtt.(m) * n_flip + mtf.(m)) * n_slice + mts.(m) in
                if Char.code (Bigarray.Array1.unsafe_get p_all j) > cur + 1 then begin
                  Bigarray.Array1.unsafe_set p_all j (Char.chr (cur + 1)); incr added end
              done
            end
          done
        done
      done;
      Printf.printf "   depth %d -> %d states (%.0f s)\n%!" (cur + 1) !added
        (Unix.gettimeofday () -. t0)
    done
  end;
  if build_only then exit 0;

  (* the row's representative *)
  let repseq = parse_moves arg in
  let rep = ref (solved ()) in
  List.iter (fun m -> rep := mult !rep moves.(m)) repseq;
  let rep = !rep in

  (* one bit a member of the row *)
  let bits = Bigarray.Array1.create Bigarray.char Bigarray.c_layout
      (fact8 * pagebytes) in
  Bigarray.Array1.fill bits '\000';
  let uniq = ref 0 in

  let maxd = 32 in
  let cps = Array.init maxd (fun _ -> Array.make 8 0) in
  let eps = Array.init maxd (fun _ -> Array.make 12 0) in
  let tw = Array.make maxd 0 in
  let fl = Array.make maxd 0 in
  let sl = Array.make maxd 0 in
  let nodes = ref 0L and probes = ref 0L in

  let heur d =
    Char.code (Bigarray.Array1.unsafe_get p_all
                 ((tw.(d) * n_flip + fl.(d)) * n_slice + sl.(d))) in

  let step d m =
    let d' = d + 1 in
    let mcp = moves.(m).cp and mep = moves.(m).ep in
    for i = 0 to 7 do cps.(d').(i) <- cps.(d).(mcp.(i)) done;
    for i = 0 to 11 do eps.(d').(i) <- eps.(d).(mep.(i)) done;
    tw.(d') <- mt_twist.(tw.(d)).(m);
    fl.(d') <- mt_flip.(fl.(d)).(m);
    sl.(d') <- mt_slice.(sl.(d)).(m) in

  (* A member of H is a corner permutation, a permutation of the eight outer
     edges and one of the four middle ones.  The parity of the middle four is
     settled by the other two, and two permutations whose ranks differ only in
     the last place have opposite parity, so dropping that place numbers the
     twelve that are left. *)
  let mark d =
    let page = rank8 cps.(d) 0 in
    let off = rank8 eps.(d) 0 * 12 + (rank4 eps.(d) 8 lsr 1) in
    let i = page * pagebytes + (off lsr 3) in
    let b = Char.code (Bigarray.Array1.unsafe_get bits i) in
    let m = 1 lsl (off land 7) in
    if b land m = 0 then begin
      Bigarray.Array1.unsafe_set bits i (Char.unsafe_chr (b lor m));
      incr uniq
    end in

  let opp f = (f + 3) mod 6 in

  let rec dfs d togo prev =
    nodes := Int64.add !nodes 1L;
    if heur d <= togo then begin
      if togo = 0 then begin
        probes := Int64.add !probes 1L;
        mark d
      end else
        for m = 0 to 17 do
          let f = m / 3 in
          if prev < 0 || not (f = prev || (f = opp prev && f > prev)) then begin
            step d m; dfs (d + 1) (togo - 1) f
          end
        done
    end in

  for i = 0 to 7 do cps.(0).(i) <- rep.cp.(i) done;
  for i = 0 to 11 do eps.(0).(i) <- rep.ep.(i) done;
  tw.(0) <- twist rep; fl.(0) <- flip rep; sl.(0) <- slice rep;

  Printf.printf "row \"%s\", %d members, table cap %d, first depth %d\n%!"
    arg rowsize cap (heur 0);
  let t0 = Unix.gettimeofday () in
  let d = ref (heur 0) in
  while !uniq < rowsize && !d <= maxdepth do
    let before = !uniq in
    nodes := 0L; probes := 0L;
    let t1 = Unix.gettimeofday () in
    dfs 0 !d (-1);
    Printf.printf
      "depth %2d : %Ld nodes, %Ld solutions, %d new, %d done, %.1f s\n%!"
      !d !nodes !probes (!uniq - before) !uniq (Unix.gettimeofday () -. t1);
    incr d
  done;
  Printf.printf "row \"%s\": %d of %d after depth %d, %.1f s\n%!"
    arg !uniq rowsize (!d - 1) (Unix.gettimeofday () -. t0)
