#!/usr/bin/env python3
"""Writes ExpTable.v, the constants of ../exp100_table.h as Rocq lists.

The limbs are copied as they are, in hexadecimal, least significant
first, so that the Rocq lists are the C arrays.  Usage:
  ./gen_v.py ../exp100_table.h > ExpTable.v
"""
import re
import sys

src = open(sys.argv[1]).read()

# the text between the braces of the declaration of name
def body(name):
    m = re.search(r'static const uint64_t ' + name + r'\b[^=]*=\s*(\{.*?\});',
                  src, re.S)
    if not m:
        sys.exit('no constant ' + name)
    return m.group(1)

# a row {a, b, ...} of hexadecimal limbs
def row(text):
    limbs = re.findall(r'0x[0-9a-fA-F]+', text)
    return '[' + '; '.join(limbs) + ']'

def table(name):
    rows = re.findall(r'\{[^{}]*\}', body(name)[1:-1])
    return '[\n  ' + ';\n  '.join(row(r) for r in rows) + ']'

inv = re.search(r'static const uint64_t INV\s*=\s*(0x[0-9a-fA-F]+)UL;', src)
if not inv:
    sys.exit('no constant INV')

print('''(** * The constants of exp100, copied from exp100_table.h

    Generated by gen_v.py from ../exp100_table.h, do not edit.  Each
    number is a list of limbs of 32 bits, least significant first, as in
    the C arrays. *)

From Stdlib Require Import ZArith List.
Import ListNotations.

Open Scope Z_scope.
''')
print('(** [T[j]], to nearest 2^(j/64) 2^160. *)')
print('Definition T : list (list Z) := ' + table('T') + '.\n')
print('(** [C[i]], 2^160 / i! rounded down. *)')
print('Definition C : list (list Z) := ' + table('C') + '.\n')
print('(** [LN2], to nearest ln2/64 2^192. *)')
print('Definition LN2 : list Z := ' + row(body('LN2')) + '.\n')
print('(** [RMAX], ceil(ln2/64 2^160) + 3. *)')
print('Definition RMAX : list Z := ' + row(body('RMAX')) + '.\n')
print('(** [INV], 64/ln2 2^25 rounded down (not certified: n is checked). *)')
print('Definition INV : Z := ' + inv.group(1) + '.')
