// Produces tang_table.h, the constants of htr2_fix.c, with MPFR.
// The producer is not trusted: each constant is to be certified in Rocq.

#include <stdio.h>
#include <gmp.h>
#include <mpfr.h>
#include "tang.h"

// print z, 0 <= z < 2^(32 TG_NL), as TG_NL limbs of 32 bits, lowest first
static void
print_limbs (mpz_t z)
{
  mpz_t q;
  mpz_init_set (q, z);
  printf ("{");
  for (int k = 0; k < TG_NL; k++) {
    printf ("0x%08lx%s", mpz_get_ui (q) & 0xffffffffUL,
            k < TG_NL - 1 ? ", " : "");
    mpz_fdiv_q_2exp (q, q, 32);
  }
  printf ("}");
  mpz_clear (q);
}

int
main (void)
{
  mpfr_t t;
  mpz_t z;
  mpfr_init2 (t, 2 * TG_P);
  mpz_init (z);
  printf ("// generated by gen_tang.c, do not edit\n");
  // T[j] = 2^(j/256), with TG_P bits after the point, rounded to nearest
  printf ("static const uint32_t tg_T[TG_TAB][TG_NL] = {\n");
  for (int j = 0; j < TG_TAB; j++) {
    mpfr_set_ui (t, j, MPFR_RNDN);
    mpfr_div_ui (t, t, TG_TAB, MPFR_RNDN);
    mpfr_exp2 (t, t, MPFR_RNDN);
    mpfr_mul_2ui (t, t, TG_P, MPFR_RNDN);
    mpfr_get_z (z, t, MPFR_RNDN);
    printf ("  ");
    print_limbs (z);
    printf (",\n");
  }
  printf ("};\n");
  // ln 2 / 256, with TG_P + TG_LG bits after the point
  mpfr_const_log2 (t, MPFR_RNDN);
  mpfr_div_ui (t, t, TG_TAB, MPFR_RNDN);
  mpfr_mul_2ui (t, t, TG_P + TG_LG, MPFR_RNDN);
  mpfr_get_z (z, t, MPFR_RNDN);
  printf ("static const uint32_t tg_ln2[TG_NL] = ");
  print_limbs (z);
  printf (";\n");
  // 256 / ln 2, with TG_LG bits after the point
  mpfr_const_log2 (t, MPFR_RNDN);
  mpfr_ui_div (t, TG_TAB, t, MPFR_RNDN);
  mpfr_mul_2ui (t, t, TG_LG, MPFR_RNDN);
  mpfr_get_z (z, t, MPFR_RNDN);
  printf ("static const uint32_t tg_inv[TG_NL] = ");
  print_limbs (z);
  printf (";\n");
  mpfr_clear (t);
  mpz_clear (z);
  return 0;
}
