(* =========================================================================  *)
(*  Far12_17.v                                                                *)
(*                                                                            *)
(*  GENERATED by mkfar12.sh -- do not edit.                                   *)
(*                                                                            *)
(*  One of the eighteen independent pieces of the depth 12 search: the second *)
(*  move is fixed to 17, and both root moves are covered.  Far12main.v glues  *)
(*  the eighteen together.                                                    *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import Tabi Coordfsi Fstab FsTable Toy Far12.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

Lemma searchj_17 :
  all (fun i => ~~ searchi 47 mtis Dti12 droot (prefixi i 17)) (iota 0 nroot).
Proof. Time by vm_compute. Qed.
