(* =========================================================================  *)
(*  Far12_13.v                                                                *)
(*                                                                            *)
(*  GENERATED by mkfar.sh -- do not edit.                                   *)
(*                                                                            *)
(*  One of the eighteen independent pieces of the search: the second *)
(*  move is fixed to 13, and both root moves are covered.  Farmain.v glues  *)
(*  the eighteen together.                                                    *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import Redun Far.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

Lemma searchd_13 :
  all (fun i => ~~ searchz5 droot (prefixi i 13)
                              (init5 (prefixi i 13)) nfcube)
      (iota 0 nroot).
(* native_cast_no_check, not "by vm_compute": the latter evaluates twice,
   once in the tactic and once when the kernel rechecks the cast at Qed.
   This evaluates once, and natively.  If the native compiler is not
   available, vm_cast_no_check (erefl true) is the fallback.               *)
Proof. Time native_cast_no_check (erefl true). Qed.
