(* =========================================================================  *)
(*  Foldslc_19.v                                                             *)
(*                                                                            *)
(*  GENERATED by mkfoldslc.sh -- do not edit.                                 *)
(*                                                                            *)
(*  One of the twenty seven slices of the orbit certificate: eighty one of    *)
(*  the 2187 twists, at every one of the 64 430 orbit representatives.        *)
(*  Foldrun.v glues them.                                                     *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsTable Diameter Moves
        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1
        Fold P1Fold Foldtab P1FTable.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

(* native_cast_no_check, not "by vm_compute": the latter evaluates twice,
   once in the tactic and once when the kernel rechecks the cast at Qed.
   If the native compiler is not available, vm_cast_no_check (erefl true)
   is the fallback.                                                        *)
Lemma foldchk_19 :
  all (fun t => foldcheckOrb p1ftab frepi fsymi repsi twsymi actfsr (of_nat t))
      (iota 1539 81).
Proof. Time native_cast_no_check (erefl true). Qed.
