(* =========================================================================  *)
(*  FoldOrbit_05.v -- GENERATED by mkfoldorbit.sh, do not edit.                  *)
(*                                                                            *)
(*  Eighty one of the 2187 twists of the orbit certificate.  See fold.md.     *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsTable Diameter Moves
        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1
        Fold P1Fold FoldTables P1FTable.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

Lemma foldorb_05 :
  all (fun t => foldcheckOrb p1ftab frepi fsymi repsi twsymi actfsr (of_nat t))
      (iota 405 81).
Proof. Time native_cast_no_check (erefl true). Qed.
