(* =========================================================================  *)
(*  Fs_00.v -- GENERATED by mkfs.sh, do not edit                               *)
(*                                                                            *)
(*  Slice 0 of sixteen of checkStep: the 1 048 576 coordinates starting at    *)
(*  cstart 0.  About four and a half minutes.  Fsmain.v glues the sixteen.    *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
From Rubik Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root.
From Rubik Require Import Coord Coordfs Coordfsi Fstab FsTable Diameter Moves.
From Rubik Require Import Fspar.

Lemma fschk_00 : all_pow cbits (cstart 0) chunkF.
Proof. Time native_cast_no_check (erefl true). Qed.
