(* =========================================================================  *)
(*  Fs_13.v -- GENERATED by mkfs.sh, do not edit Slice 13 of sixteen of       *)
(*     checkStep: the 1 048 576 coordinates starting at cstart 13.            *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.

From Rubik Require Import Fstab.
From Rubik Require Import Fspar.

Lemma fschk_13 : all_pow cbits (cstart 13) chunkF.
Proof. Time native_cast_no_check (erefl true). Qed.
