(* =========================================================================  *)
(*  FsTable.v                                                                 *)
(*                                                                            *)
(*  The pruning table, and the two checks it has to pass.                     *)
(*                                                                            *)
(*  Fstab.v takes the table as a Variable and says what it has to satisfy.    *)
(*  This file supplies it, and it is the only file the table appears in:      *)
(*  fstab_len, fstab_def, check0 and checkStep are all stated against fstab   *)
(*  without mentioning its contents.                                          *)
(*                                                                            *)
(*  WHERE IT COMES FROM.  FsData.v, generated by                              *)
(*                                                                            *)
(*      ./rubik_lb dumpfs 9 > FsData.v                                        *)
(*                                                                            *)
(*  a breadth first search over the 2 ^ 24 packed summaries -- flip in the    *)
(*  low twelve bits, slice mask in the high twelve, positions in eprim's      *)
(*  order.  These are the MASK summaries, not the ranked ones: 16 777 216     *)
(*  indices of which 1 013 760 are reachable.  The waste costs memory and     *)
(*  nothing else.                                                             *)
(*                                                                            *)
(*  The search is its own check that the Rocq and OCaml encodings agree: its  *)
(*  levels sum to exactly 1 013 760 = 2048 x 495, and everything is reached   *)
(*  by depth 9, so the cap truncates nothing.                                 *)
(*                                                                            *)
(*  WHAT IS IN THE UNREACHABLE ENTRIES.  cap + 1, not 0.  A reachable state   *)
(*  next to an unreachable one still has to satisfy D x <= D (act x m) + 1,   *)
(*  and cap + 1 keeps that true where 0 would not.  The array's DEFAULT is a  *)
(*  different thing and is 0: that is what Dfs_oob uses for indices past the  *)
(*  end of the array, where 0 <= _.+1 holds for nothing.                      *)
(*                                                                            *)
(*  THE COST.  25 MB of literals, six minutes to compile, and a 25 MB .vo --  *)
(*  the array survives evaluated, which is what bench/Store.v measured and    *)
(*  what makes the Eval worth it: nothing is rebuilt on Require.  That is the *)
(*  price of never proving the table correct, and it is the right trade.      *)
(*                                                                            *)
(*  fstab_len, fstab_def and check0 are one read of a literal array each.     *)
(*  fstab_checkStep is the one admit left here, and it is not a proof: it is  *)
(*  the local certificate, 16 777 216 summaries times eighteen moves.         *)
(* =========================================================================  *)

From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From mathcomp Require Import all_ssreflect all_fingroup.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsData.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

Notation arr := (PArray.array int).

(* ---- The table ----------------------------------------------------------- *)

(* FsData.v holds the 2 097 152 words; this is the only place they become an
   array.  The Eval matters: without it the fold is redone on every Require. *)
Definition mkarr (l : seq int) : arr :=
  (fix go (a : arr) (i : int) (l : seq int) {struct l} : arr :=
     if l is x :: l' then go (PArray.set a i x) (i + 1)%uint63 l' else a)
    (PArray.make nwordsi 0%uint63) 0%uint63 l.

Definition fstab : arr := Eval vm_compute in mkarr fsdata.

(* ---- What Fstab.v asks of it --------------------------------------------- *)

(* Both are now one read of a literal array rather than an induction.        *)
Lemma fstab_len : PArray.length fstab = nwordsi.
Proof. by vm_compute. Qed.

Lemma fstab_def : PArray.default fstab = 0%uint63.
Proof. by vm_compute. Qed.

(* ---- The two checks ------------------------------------------------------ *)

(* One lookup: the summary of the identity has to hold 0.                    *)
Lemma fstab_check0 : check0 fstab.
Proof. by vm_compute. Qed.

(* THE SECOND COMPUTATION.  16 777 216 summaries times eighteen moves, each
   a dozen bit operations and two reads -- the local certificate, and the
   only thing this table is ever asked to satisfy.  Not run here.           *)
Lemma fstab_checkStep mtabs : checkStep fstab mtabs.
Proof. Admitted.
