(* =========================================================================  *)
(*  FsTable.v                                                                 *)
(*                                                                            *)
(*  The pruning table, and the two checks it has to pass.                     *)
(*                                                                            *)
(*  Fstab.v takes the table as a Variable and says what it has to satisfy.    *)
(*  This file supplies it, and it is the only file the table appears in:      *)
(*  fstab_len, fstab_def, check0 and checkStep are all stated against fstab   *)
(*  without mentioning its contents.                                          *)
(*                                                                            *)
(*  WHERE IT COMES FROM.  FsData.v, generated by                              *)
(*                                                                            *)
(*      ./rubik_lb dumpfs 9 > FsData.v                                        *)
(*                                                                            *)
(*  a breadth first search over the 2 ^ 24 packed summaries -- flip in the    *)
(*  low twelve bits, slice mask in the high twelve, positions in eprim's      *)
(*  order.  These are the MASK summaries, not the ranked ones: 16 777 216     *)
(*  indices of which 1 013 760 are reachable.  The waste costs memory and     *)
(*  nothing else.                                                             *)
(*                                                                            *)
(*  The search is its own check that the Rocq and OCaml encodings agree: its  *)
(*  levels sum to exactly 1 013 760 = 2048 x 495, and everything is reached   *)
(*  by depth 9, so the cap truncates nothing.                                 *)
(*                                                                            *)
(*  WHAT IS IN THE UNREACHABLE ENTRIES.  cap + 1, not 0.  A reachable state   *)
(*  next to an unreachable one still has to satisfy D x <= D (act x m) + 1,   *)
(*  and cap + 1 keeps that true where 0 would not.  The array's DEFAULT is a  *)
(*  different thing and is 0: that is what Dfs_oob uses for indices past the  *)
(*  end of the array, where 0 <= _.+1 holds for nothing.                      *)
(*                                                                            *)
(*  THE COST.  25 MB of literals, six minutes to compile, and a 25 MB .vo --  *)
(*  the array survives evaluated, which is what bench/Store.v measured and    *)
(*  what makes the Eval worth it: nothing is rebuilt on Require.  That is the *)
(*  price of never proving the table correct, and it is the right trade.      *)
(*                                                                            *)
(*  fstab_len, fstab_def and check0 are one read of a literal array each.     *)
(*  fstab_checkStep is the one admit left here, and it is not a proof: it is  *)
(*  the local certificate, 16 777 216 summaries times eighteen moves.         *)
(* =========================================================================  *)

From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From mathcomp Require Import all_ssreflect all_fingroup.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsData.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

Notation arr := (PArray.array int).

(* ---- The table ----------------------------------------------------------- *)

(* FsData.v holds the 2 097 152 words; this is the only place they become an
   array.  The Eval matters: without it the fold is redone on every Require. *)
Definition mkarr (l : seq int) : arr :=
  (fix go (a : arr) (i : int) (l : seq int) {struct l} : arr :=
     if l is x :: l' then go (PArray.set a i x) (i + 1)%uint63 l' else a)
    (PArray.make nwordsi 0%uint63) 0%uint63 l.

(* NO Eval vm_compute HERE, ON PURPOSE, FOR NOW.  With it, the .vo holds the
   evaluated 2 097 152 entry array and nothing is rebuilt on Require -- which
   is what we want -- but the native compiler then has to emit that array and
   never produces NRubik_FsTable.cmxs, so every file requiring this one dies
   with "Unbound module NRubik_FsTable".  FsData.v's list compiles natively
   fine; it is the array value that it cannot do.

   And the Eval was never worth much anyway, native or not.  The fold is a
   second; the search it precedes is minutes at depth 12 and hours at depth
   19.  It is paid once per vm_compute -- not per node, not per Require, not
   per array access -- so even with one worker per root prefix it is 36
   seconds against hours.  Storing the table twice to save that was the wrong
   trade; the native failure only made us notice.

   It would start to matter if the work per vm_compute were itself about a
   second, i.e. if the search were split into thousands of tiny files.  At 36
   prefixes we are nowhere near that, and the fix then would be bigger
   chunks, not a second copy of the table.                                  *)
Definition fstab : arr := mkarr fsdata.

(* ---- What Fstab.v asks of it --------------------------------------------- *)

(* Both are now one read of a literal array rather than an induction.        *)
Lemma fstab_len : PArray.length fstab = nwordsi.
Proof. by vm_compute. Qed.

Lemma fstab_def : PArray.default fstab = 0%uint63.
Proof. by vm_compute. Qed.

(* ---- The two checks ------------------------------------------------------ *)

(* One lookup: the summary of the identity has to hold 0.                    *)
Lemma fstab_check0 : check0 fstab.
Proof. by vm_compute. Qed.

(* THE SECOND COMPUTATION lives in Fsmain.v, not here.
                                                                            *)
(* It used to be admitted here as                                           *)
(*                                                                          *)
(*    Lemma fstab_checkStep mtabs : checkStep fstab mtabs.                   *)
(*                                                                          *)
(* quantified over every table list.  That is FALSE -- for                  *)
(* mtabs = [:: comp_tab U R ] the check fails inside the first 2 ^ 20       *)
(* coordinates, since a two move composition cuts the flip x slice          *)
(* distance by two and breaks the local certificate -- and it was not       *)
(* something a computation could discharge either, mtabs being a variable.  *)
(* Far.v took it as the justification of Dfsd_step, so the depth 12         *)
(* theorem rested on a false axiom.                                         *)
(*                                                                          *)
(* The honest statement is at the concrete moves, and needs Moves.v, which  *)
(* this file must not depend on -- it would drag the move tables into the   *)
(* 55 MB table file.  So it lives in Fsmain.v, where the sixteen slices     *)
(* are glued.                                                               *)
