(* ================================================================== *)
(*  HAll.v -- GENERATED by mkhall.sh, do not edit.                    *)
(* ================================================================== *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Table Tabi Tsearch Rubik333 Sym Ball Moves Coordfs
        Coordfsi Phase1 HRoot HCoord HReid HProp2 HSearch HBridge
        HBound HCanon HSound HEdge HRunS HCorner HSweep HSweepC HGlue
        HPok HPrefix HCut HTables HFoldAll HSweepAll HSweepCAll
        HRun_0_00
        HRun_0_01
        HRun_0_02
        HRun_0_03
        HRun_0_04
        HRun_0_05
        HRun_0_06
        HRun_0_07
        HRun_0_08
        HRun_0_09
        HRun_0_10
        HRun_0_11
        HRun_1_00
        HRun_1_01
        HRun_1_02
        HRun_1_03
        HRun_1_04
        HRun_1_05
        HRun_1_06
        HRun_1_07
        HRun_1_08
        HRun_1_09
        HRun_1_10
        HRun_1_11
        HRun_2_00
        HRun_2_01
        HRun_2_02
        HRun_2_03
        HRun_2_04
        HRun_2_05
        HRun_2_06
        HRun_2_07
        HRun_2_08
        HRun_2_09
        HRun_2_10
        HRun_2_11
        HRun_3_00
        HRun_3_01
        HRun_3_02
        HRun_3_03
        HRun_3_04
        HRun_3_05
        HRun_3_06
        HRun_3_07
        HRun_3_08
        HRun_3_09
        HRun_3_10
        HRun_3_11
        HRun_4_00
        HRun_4_01
        HRun_4_02
        HRun_4_03
        HRun_4_04
        HRun_4_05
        HRun_4_06
        HRun_4_07
        HRun_4_08
        HRun_4_09
        HRun_4_10
        HRun_4_11
        HRun_5_00
        HRun_5_01
        HRun_5_02
        HRun_5_03
        HRun_5_04
        HRun_5_05
        HRun_5_06
        HRun_5_07
        HRun_5_08
        HRun_5_09
        HRun_5_10
        HRun_5_11
        .

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

Notation arr := (PArray.array int).

(* ---- the two lookups the cut needs ---------------------------- *)

(* the table is zero at the solved coset, which is what makes the
   bound n rather than h 1 + n *)
Lemma hzero :
  hget h_which h_fam h_sym_cl h_sym_ct hfoldall h0i = 0%uint63.
Proof. by vm_compute. Qed.

Lemma n_eiE : to_nat n_ei = n_e.
Proof. by vm_compute. Qed.

Lemma n_cliE : to_nat n_cli = n_cl.
Proof. by vm_compute. Qed.

Lemma n_ctiE : to_nat n_cti = n_ct.
Proof. by vm_compute. Qed.

(* the coordinates a position shows are rows of the tables *)
Lemma hcoord (a : arr) e c t : tabi_ok flast a ->
  cubt (ti2t flast a) -> cubct (ti2t flast a) ->
  ctsum (inv_tabi flast a) -> htriple a = (e, c, t) ->
  [/\ (to_nat e < n_e)%N, (to_nat c < n_cl)%N & (to_nat t < n_ct)%N].
Proof.
move=> aok ca cca cta; rewrite /htriple => [] [] <- <- <-.
have uok := HPok.tabi_ok_invi aok.
split.
- rewrite -n_eiE; apply/nltbP.
  by apply: (ecoord_lt hechk uok (cubt_invi aok ca)).
- rewrite -n_cliE; apply/nltbP.
  by apply: (clcoord_lt hclchk uok (cubct_invi aok cca)).
rewrite -n_ctiE; apply/nltbP.
by apply: (ctcoord_lt _ hctchk).
Qed.

(* ---- obligation D read through the coordinates ----------------- *)

Lemma hcut (a : arr) (v : seq nat) (n : nat) :
  pok a -> qw v -> (seq.size v <= n)%N -> (n <= 24)%N ->
  eq_tabi flast (aw a v) idi ->
  hle h_which h_fam h_sym_cl h_sym_ct hfoldall (stt a) (of_nat n).
Proof.
apply: (stt_cut hsweep_all _ hzero hcoord).
by apply: hsweeps.
Qed.

(* ---- what the seventy two run files say ------------------------ *)

Lemma hj k w : (k < seq.size rpfx)%N -> w \in hpres ->
  hrun h_mt_e h_mt_cl h_mt_ct h_which h_fam h_sym_cl h_sym_ct hfoldall
    k w (hdepth k) = false.
Proof.
move=> kL wp; have [j jL wj] := hslice_mem wp.
apply: negbTE; move: wj.
case: k kL => [|[|[|[|[|[|k]]]]]] // _;
  case: j jL => [|[|[|[|[|[|[|[|[|[|[|[|j]]]]]]]]]]]] // _.
- exact: (allP hrun_0_00 w).
- exact: (allP hrun_0_01 w).
- exact: (allP hrun_0_02 w).
- exact: (allP hrun_0_03 w).
- exact: (allP hrun_0_04 w).
- exact: (allP hrun_0_05 w).
- exact: (allP hrun_0_06 w).
- exact: (allP hrun_0_07 w).
- exact: (allP hrun_0_08 w).
- exact: (allP hrun_0_09 w).
- exact: (allP hrun_0_10 w).
- exact: (allP hrun_0_11 w).
- exact: (allP hrun_1_00 w).
- exact: (allP hrun_1_01 w).
- exact: (allP hrun_1_02 w).
- exact: (allP hrun_1_03 w).
- exact: (allP hrun_1_04 w).
- exact: (allP hrun_1_05 w).
- exact: (allP hrun_1_06 w).
- exact: (allP hrun_1_07 w).
- exact: (allP hrun_1_08 w).
- exact: (allP hrun_1_09 w).
- exact: (allP hrun_1_10 w).
- exact: (allP hrun_1_11 w).
- exact: (allP hrun_2_00 w).
- exact: (allP hrun_2_01 w).
- exact: (allP hrun_2_02 w).
- exact: (allP hrun_2_03 w).
- exact: (allP hrun_2_04 w).
- exact: (allP hrun_2_05 w).
- exact: (allP hrun_2_06 w).
- exact: (allP hrun_2_07 w).
- exact: (allP hrun_2_08 w).
- exact: (allP hrun_2_09 w).
- exact: (allP hrun_2_10 w).
- exact: (allP hrun_2_11 w).
- exact: (allP hrun_3_00 w).
- exact: (allP hrun_3_01 w).
- exact: (allP hrun_3_02 w).
- exact: (allP hrun_3_03 w).
- exact: (allP hrun_3_04 w).
- exact: (allP hrun_3_05 w).
- exact: (allP hrun_3_06 w).
- exact: (allP hrun_3_07 w).
- exact: (allP hrun_3_08 w).
- exact: (allP hrun_3_09 w).
- exact: (allP hrun_3_10 w).
- exact: (allP hrun_3_11 w).
- exact: (allP hrun_4_00 w).
- exact: (allP hrun_4_01 w).
- exact: (allP hrun_4_02 w).
- exact: (allP hrun_4_03 w).
- exact: (allP hrun_4_04 w).
- exact: (allP hrun_4_05 w).
- exact: (allP hrun_4_06 w).
- exact: (allP hrun_4_07 w).
- exact: (allP hrun_4_08 w).
- exact: (allP hrun_4_09 w).
- exact: (allP hrun_4_10 w).
- exact: (allP hrun_4_11 w).
- exact: (allP hrun_5_00 w).
- exact: (allP hrun_5_01 w).
- exact: (allP hrun_5_02 w).
- exact: (allP hrun_5_03 w).
- exact: (allP hrun_5_04 w).
- exact: (allP hrun_5_05 w).
- exact: (allP hrun_5_06 w).
- exact: (allP hrun_5_07 w).
- exact: (allP hrun_5_08 w).
- exact: (allP hrun_5_09 w).
- exact: (allP hrun_5_10 w).
- exact: (allP hrun_5_11 w).
Qed.

(* ---- and the bound, with nothing left ------------------------- *)

Theorem targ_far25 : targ \notin ball Sq 25.
Proof. by apply: (targ_far_runP hsweep_e hsweep_cl hsweep_ct hcut hj). Qed.

Theorem targ_dist25 : targ \in ball Sq 26 /\ targ \notin ball Sq 25.
Proof. by split; [apply: targ_near | apply: targ_far25]. Qed.

(* the position is a maneuver, so it is in the group at all *)
Lemma targ_gen : targ \in generated Sq.
Proof.
have := wp_ball targw_qw.
by rewrite wp_targw; apply: (subsetP (ball_sub_gen Sq 40)).
Qed.

(* THE QUARTER TURN DIAMETER IS MORE THAN TWENTY FIVE *)
Theorem qdiam25 : ~ diam_le Sq 25.
Proof.
move=> /subsetP hsub.
have := hsub _ targ_gen.
by apply/negP; apply: targ_far25.
Qed.
