(* =========================================================================  *)
(*  HSweep_06.v -- GENERATED by mkhsweep.sh, do not edit.                    *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Table Tabi Rubik333 Moves Coordfs Phase1 HRoot HCoord HSearch
        HSweep HTables HFoldAll.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

(* 15840 of the e coordinates from 95040 on, all 70 cl, all 2187 ct and twelve
   turns each: job 06 of 12.                                              *)
Lemma hsweep_06 :
  adm h_mt_e h_mt_cl h_mt_ct h_which h_fam h_sym_cl h_sym_ct hfoldall
      95040%uint63 15840.
Proof. Time native_cast_no_check (erefl true). Qed.
