(* ====================================================================== *)
(*  HSweepAll.v -- GENERATED by mkhsweep.sh, do not edit.                 *)
(* ====================================================================== *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Table Tabi Rubik333 Moves Coordfs Phase1 HRoot HCoord
        HSearch HSweep HTables HFoldAll
        HSweep_00
        HSweep_01
        HSweep_02
        HSweep_03
        HSweep_04
        HSweep_05
        HSweep_06
        HSweep_07
        HSweep_08
        HSweep_09
        HSweep_10
        HSweep_11
        .

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

(* the sweep of the whole table, out of the 12 jobs *)
Lemma hsweep_all :
  admis h_mt_e h_mt_cl h_mt_ct h_which h_fam h_sym_cl h_sym_ct hfoldall.
Proof.
have hn : n_e = (15840 + (15840 + (15840 + (15840 + (15840 + (15840 + (15840 + (15840 + (15840 + (15840 + (15840 + (15840))))))))))))%N by [].
rewrite /admis hn.
apply: (adm_split (y := 15840%uint63)); [by vm_compute | exact: hsweep_00 |].
apply: (adm_split (y := 31680%uint63)); [by vm_compute | exact: hsweep_01 |].
apply: (adm_split (y := 47520%uint63)); [by vm_compute | exact: hsweep_02 |].
apply: (adm_split (y := 63360%uint63)); [by vm_compute | exact: hsweep_03 |].
apply: (adm_split (y := 79200%uint63)); [by vm_compute | exact: hsweep_04 |].
apply: (adm_split (y := 95040%uint63)); [by vm_compute | exact: hsweep_05 |].
apply: (adm_split (y := 110880%uint63)); [by vm_compute | exact: hsweep_06 |].
apply: (adm_split (y := 126720%uint63)); [by vm_compute | exact: hsweep_07 |].
apply: (adm_split (y := 142560%uint63)); [by vm_compute | exact: hsweep_08 |].
apply: (adm_split (y := 158400%uint63)); [by vm_compute | exact: hsweep_09 |].
apply: (adm_split (y := 174240%uint63)); [by vm_compute | exact: hsweep_10 |].
exact: hsweep_11.
Qed.
