(* =========================================================================  *)
(*  HSweepE_04.v -- GENERATED by mkhsweepc.sh, do not edit.                  *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Table Tabi Rubik333 Sym Moves Coordfs Coordfsi Phase1
        HRoot HCoord HReid HProp2 HSearch HEdge HCorner HSweepC HTables.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

(* 4 of the twenty four first slots from 16 on, and for each of them all
   the second, third and fourth slots and twelve turns: job 04 of 6.   *)
Lemma hechk_04 : echk_from h_mt_e 16 4.
Proof. Time native_cast_no_check (erefl true). Qed.
