(* ============================================================== *)
(*  HSweepCAll.v -- GENERATED by mkhsweepc.sh, do not edit.       *)
(* ============================================================== *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Table Tabi Rubik333 Sym Moves Coordfs Coordfsi Phase1
        HRoot HCoord HReid HProp2 HSearch HEdge HCorner HSweepC HTables
        HSweepE_00
        HSweepE_01
        HSweepE_02
        HSweepE_03
        HSweepE_04
        HSweepE_05
        .

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

(* the edge sweep, out of the 6 jobs *)
Lemma hechk : echk h_mt_e.
Proof.
have hn : (2 * nedge)%N = (4 + (4 + (4 + (4 + (4 + (4))))))%N by [].
rewrite /echk hn.
apply: echk_split; first exact: hechk_00.
apply: echk_split; first exact: hechk_01.
apply: echk_split; first exact: hechk_02.
apply: echk_split; first exact: hechk_03.
apply: echk_split; first exact: hechk_04.
exact: hechk_05.
Qed.

(* the two corner sweeps, which are small enough to stand here *)
Lemma hclchk : clchk h_mt_cl.
Proof. Time native_cast_no_check (erefl true). Qed.

Lemma hctchk : ctchk h_mt_ct.
Proof. Time native_cast_no_check (erefl true). Qed.

(* ---- and the three obligations -------------------------------- *)

Lemma hsweep_e : sweep_e h_mt_e.
Proof. exact: sweep_e_of_chk hechk. Qed.

Lemma hsweep_cl : sweep_cl h_mt_cl.
Proof. exact: sweep_cl_of_chk hclchk. Qed.

Lemma hsweep_ct : sweep_ct h_mt_ct.
Proof. exact: sweep_ct_of_chk hctchk. Qed.

(* the three side by side, which is what the search takes *)
Lemma hsweeps : forall (a : arr) m,
  tabi_ok flast a -> cubt (ti2t flast a) -> cubct (ti2t flast a) ->
  ctsum (inv_tabi flast a) -> (m < nq)%N ->
  htriple (comp_tabi flast a (mvq m))
    = stepa h_mt_e h_mt_cl h_mt_ct (htriple a) (of_nat m).
Proof. exact: sweeps_agree hsweep_e hsweep_cl hsweep_ct. Qed.
