#!/bin/sh
# =========================================================================
#  Write the thirteen checks as THREE files, FoldRun_00.v .. FoldRun_02.v.
#
#  They are independent lemmas over the emitted tables, so the wall time is
#  the largest FILE and not their sum.  Three is where splitting stops
#  paying.  MEASURED at n = 16: msymRC 106 s, ractAC 69 s, the eleven
#  others 70 s together, against ~4 s to load the chain in each file --
#  one file ~190 s, two ~135, three 106, and thirteen 106 as well.
#
#  DEAREST FIRST: xargs starts them in this order.
#
#  FoldChecksRun.v re-exports them, so what requires it sees no change.
# =========================================================================
cd "$(dirname "$0")"

# file : name : statement
set -- \
  "0:msymRCP:msymRC ractab actfsri" \
  "1:ractACP:ractAC ractab" \
  "2:fsymECP:fsymEC ractab frepi fsymi repsi" \
  "2:ractLCP:ractLC ractab" \
  "2:actrLCP:actrLC actfsr" \
  "2:frepSCP:frepSC ractab frepi" \
  "2:fsymLCP:fsymLC fsymi" \
  "2:smulCP:smulC" \
  "2:acttwiLCP:acttwiLC" \
  "2:twsymLCP:twsymLC twsymi" \
  "2:twsymACP:twsymAC twsymi" \
  "2:msymTCP:msymTC twsymi" \
  "2:msymiCP:msymiC"

bar='(* =========================================================================  *)'

changed=0
for g in 0 1 2; do
  nn=$(printf "%02d" "$g")
  case "$g" in
    0) what="msymRC, the dearest at 106 s";;
    1) what="ractAC, at 69 s";;
    *) what="the eleven cheap ones, 70 s together";;
  esac
  { echo "$bar"
    printf '(*  %-72s*)\n' "FoldRun_$nn.v -- $what."
    printf '(*  %-72s*)\n' "   GENERATED by mkfoldrun.sh, do not edit."
    echo "$bar"
    echo ""
    echo "From mathcomp Require Import all_ssreflect all_fingroup."
    echo "From Stdlib Require Import Uint63."
    echo "From Stdlib Require Import -(notations) PArray."
    echo "From Rubik Require Import ssrint63."
    echo "Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord"
    echo "        Coordfs Coordfsi Fstab FsTable Diameter Moves"
    echo "        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1"
    echo "        Fold P1Fold FoldTables Sym16 P1RTable FoldChecks."
    echo ""
    echo "Set Implicit Arguments."
    echo "Unset Strict Implicit."
    echo "Unset Printing Implicit Defensive."
    for e in "$@"; do
      case "$e" in
        "$g:"*)
          rest=${e#"$g":}
          echo ""
          echo "Lemma ${rest%%:*} : ${rest#*:}."
          echo "Proof. Time native_cast_no_check (erefl true). Qed."
          ;;
      esac
    done
  } > "FoldRun_$nn.v.new"
  # only when it changed: a rewritten file with the same bytes still gets a
  # new mtime, and that is a check re-run for nothing
  if cmp -s "FoldRun_$nn.v.new" "FoldRun_$nn.v"; then
    rm -f "FoldRun_$nn.v.new"
  else
    mv "FoldRun_$nn.v.new" "FoldRun_$nn.v"
    changed=$((changed + 1))
  fi
done

if [ "$changed" = 0 ]; then echo "  the three check files are current"
else echo "  wrote $changed of the three check files"; fi
