#!/bin/sh
# =========================================================================
#  Write the twelve checks as twelve files, FoldRun_00.v .. FoldRun_11.v.
#
#  They are independent lemmas over the emitted tables, so one file each
#  makes the wall time the largest of them instead of their sum -- as one
#  file they were 528 s in a single process, MEASURED at n = 16.
#
#  ORDERED BY COST, dearest first: xargs starts them in this order, and the
#  last one to start is the one that sets the makespan.
#
#  FoldChecksRun.v re-exports the twelve, so what requires it sees no change.
# =========================================================================
cd "$(dirname "$0")"

# name : statement
set -- \
  "ractACP:ractAC ractab" \
  "msymRCP:msymRC ractab actfsr" \
  "fsymECP:fsymEC ractab frepi fsymi repsi" \
  "ractLCP:ractLC ractab" \
  "actrLCP:actrLC actfsr" \
  "frepSCP:frepSC ractab frepi" \
  "fsymLCP:fsymLC fsymi" \
  "smulCP:smulC" \
  "acttwiLCP:acttwiLC" \
  "twsymLCP:twsymLC twsymi" \
  "twsymACP:twsymAC twsymi" \
  "msymTCP:msymTC twsymi"

bar='(* =========================================================================  *)'

n=0
changed=0
for e in "$@"; do
  name=${e%%:*}
  stmt=${e#*:}
  nn=$(printf "%02d" "$n")
  n=$((n + 1))
  { echo "$bar"
    printf '(*  %-72s*)\n' "FoldRun_$nn.v -- the check $name, GENERATED by mkfoldrun.sh."
    echo "$bar"
    echo ""
    echo "From mathcomp Require Import all_ssreflect all_fingroup."
    echo "From Stdlib Require Import Uint63."
    echo "From Stdlib Require Import -(notations) PArray."
    echo "From Rubik Require Import ssrint63."
    echo "Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord"
    echo "        Coordfs Coordfsi Fstab FsTable Diameter Moves"
    echo "        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1"
    echo "        Fold P1Fold FoldTables Sym16 P1RTable FoldChecks."
    echo ""
    echo "Set Implicit Arguments."
    echo "Unset Strict Implicit."
    echo "Unset Printing Implicit Defensive."
    echo ""
    echo "Lemma $name : $stmt."
    echo "Proof. Time native_cast_no_check (erefl true). Qed."
  } > "FoldRun_$nn.v.new"
  # only when it changed: a rewritten file with the same bytes still gets a
  # new mtime, and that is a check re-run for nothing
  if cmp -s "FoldRun_$nn.v.new" "FoldRun_$nn.v"; then
    rm -f "FoldRun_$nn.v.new"
  else
    mv "FoldRun_$nn.v.new" "FoldRun_$nn.v"
    changed=$((changed + 1))
  fi
done

if [ "$changed" = 0 ]; then echo "  the twelve check files are current"
else echo "  wrote $changed of the twelve check files"; fi
