#!/bin/sh
# =========================================================================
#  Write the thirteen checks as TWO files, FoldRun_00.v and FoldRun_01.v.
#
#  They are independent lemmas over the emitted tables, so the wall time is
#  the largest FILE and not their sum.  MEASURED at n = 16: msymRC 101 s,
#  ractAC 63 s, and the eleven others 18 s TOGETHER -- they share the ~4 s
#  chain load, so each is about a second of work.  One file is ~174 s; two
#  are 101, and so are three and thirteen.  msymRC alone sets the wall, so
#  everything else goes in one file with it left on its own.
#
#  DEAREST FIRST: xargs starts them in this order.
#
#  FoldChecksRun.v re-exports them, so what requires it sees no change.
# =========================================================================
cd "$(dirname "$0")"

# file : name : statement
set -- \
  "0:msymRCP:msymRC ractab actfsri" \
  "1:ractACP:ractAC ractab" \
  "1:fsymECP:fsymEC ractab frepi fsymi repsi" \
  "1:ractLCP:ractLC ractab" \
  "1:actrLCP:actrLC actfsr" \
  "1:frepSCP:frepSC ractab frepi" \
  "1:fsymLCP:fsymLC fsymi" \
  "1:smulCP:smulC" \
  "1:acttwiLCP:acttwiLC" \
  "1:twsymLCP:twsymLC twsymi" \
  "1:twsymACP:twsymAC twsymi" \
  "1:msymTCP:msymTC twsymi" \
  "1:msymiCP:msymiC"

bar='(* =========================================================================  *)'

changed=0
for g in 0 1; do
  nn=$(printf "%02d" "$g")
  case "$g" in
    0) what="msymRC alone, the dearest at 101 s";;
    *) what="the twelve others, 81 s together";;
  esac
  { echo "$bar"
    printf '(*  %-72s*)\n' "FoldRun_$nn.v -- $what."
    printf '(*  %-72s*)\n' "   GENERATED by mkfoldrun.sh, do not edit."
    echo "$bar"
    echo ""
    echo "From mathcomp Require Import all_ssreflect all_fingroup."
    echo "From Stdlib Require Import Uint63."
    echo "From Stdlib Require Import -(notations) PArray."
    echo "From Rubik Require Import ssrint63."
    echo "Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord"
    echo "        Coordfs Coordfsi Fstab FsTable Diameter Moves"
    echo "        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1"
    echo "        Fold P1Fold FoldTables Sym16 P1RTable FoldChecks."
    echo ""
    echo "Set Implicit Arguments."
    echo "Unset Strict Implicit."
    echo "Unset Printing Implicit Defensive."
    for e in "$@"; do
      case "$e" in
        "$g:"*)
          rest=${e#"$g":}
          echo ""
          echo "Lemma ${rest%%:*} : ${rest#*:}."
          echo "Proof. Time native_cast_no_check (erefl true). Qed."
          ;;
      esac
    done
  } > "FoldRun_$nn.v.new"
  # only when it changed: a rewritten file with the same bytes still gets a
  # new mtime, and that is a check re-run for nothing
  if cmp -s "FoldRun_$nn.v.new" "FoldRun_$nn.v"; then
    rm -f "FoldRun_$nn.v.new"
  else
    mv "FoldRun_$nn.v.new" "FoldRun_$nn.v"
    changed=$((changed + 1))
  fi
done

if [ "$changed" = 0 ]; then echo "  the two check files are current"
else echo "  wrote $changed of the two check files"; fi
