#!/bin/sh
# Write HAll.v: everything at the real tables, so the bound stands with no
# hypothesis left.  The seventy two run files are named hrun_K_JJ, one per
# position and slice, and this is the only place they are all mentioned.
#
#   ./mkhall.sh          twelve slices, as mkhrun.sh writes them
#   ./mkhall.sh 12
cd "$(dirname "$0")"

NJ=${1:-12}
NK=6
case "$NJ" in ''|*[!0-9]*) echo "usage: ./mkhall.sh [slices]" >&2; exit 1;; esac

replace () {
  if [ -f "$2" ] && cmp -s "$1" "$2"; then rm -f "$1"; return 1; fi
  mv "$1" "$2"
}

{
  echo "(* ================================================================== *)"
  echo "(*  HAll.v -- GENERATED by mkhall.sh, do not edit.                    *)"
  echo "(* ================================================================== *)"
  echo
  echo "From mathcomp Require Import all_ssreflect all_fingroup."
  echo "From Stdlib Require Import Uint63."
  echo "From Stdlib Require Import -(notations) PArray."
  echo "From Rubik Require Import ssrint63."
  echo "Require Import Table Tabi Tsearch Rubik333 Sym Ball Moves Coordfs"
  echo "        Coordfsi Phase1 HRoot HCoord HReid HProp2 HSearch HBridge"
  echo "        HBound HCanon HSound HEdge HRunS HCorner HSweep HSweepC HGlue"
  echo "        HPok HPrefix HCut HTables HFoldAll HSweepAll HSweepCAll"
  k=0
  while [ "$k" -lt "$NK" ]; do
    j=0
    while [ "$j" -lt "$NJ" ]; do
      printf '        HRun_%d_%02d\n' "$k" "$j"; j=$((j + 1))
    done
    k=$((k + 1))
  done
  echo "        ."
  echo
  echo "Set Implicit Arguments."
  echo "Unset Strict Implicit."
  echo "Unset Printing Implicit Defensive."
  echo
  echo "Import GroupScope."
  echo
  echo "Notation arr := (PArray.array int)."
  echo
  echo "(* ---- the two lookups the cut needs ---------------------------- *)"
  echo
  echo "(* the table is zero at the solved coset, which is what makes the"
  echo "   bound n rather than h 1 + n *)"
  echo "Lemma hzero :"
  echo "  hget h_which h_fam h_sym_cl h_sym_ct hfoldall h0i = 0%uint63."
  echo "Proof. by vm_compute. Qed."
  echo
  echo "Lemma n_eiE : to_nat n_ei = n_e."
  echo "Proof. by vm_compute. Qed."
  echo
  echo "Lemma n_cliE : to_nat n_cli = n_cl."
  echo "Proof. by vm_compute. Qed."
  echo
  echo "Lemma n_ctiE : to_nat n_cti = n_ct."
  echo "Proof. by vm_compute. Qed."
  echo
  echo "(* the coordinates a position shows are rows of the tables *)"
  echo "Lemma hcoord (a : arr) e c t : tabi_ok flast a ->"
  echo "  cubt (ti2t flast a) -> cubct (ti2t flast a) ->"
  echo "  ctsum (inv_tabi flast a) -> htriple a = (e, c, t) ->"
  echo "  [/\\ (to_nat e < n_e)%N, (to_nat c < n_cl)%N & (to_nat t < n_ct)%N]."
  echo "Proof."
  echo "move=> aok ca cca cta; rewrite /htriple => [] [] <- <- <-."
  echo "have uok := HPok.tabi_ok_invi aok."
  echo "split."
  echo "- rewrite -n_eiE; apply/nltbP."
  echo "  by apply: (ecoord_lt hechk uok (cubt_invi aok ca))."
  echo "- rewrite -n_cliE; apply/nltbP."
  echo "  by apply: (clcoord_lt hclchk uok (cubct_invi aok cca))."
  echo "rewrite -n_ctiE; apply/nltbP."
  echo "by apply: (ctcoord_lt _ hctchk)."
  echo "Qed."
  echo
  echo "(* ---- obligation D read through the coordinates ----------------- *)"
  echo
  echo "Lemma hcut (a : arr) (v : seq nat) (n : nat) :"
  echo "  pok a -> qw v -> (seq.size v <= n)%N -> (n <= 24)%N ->"
  echo "  eq_tabi flast (aw a v) idi ->"
  echo "  hle h_which h_fam h_sym_cl h_sym_ct hfoldall (stt a) (of_nat n)."
  echo "Proof."
  echo "apply: (stt_cut hsweep_all _ hzero hcoord)."
  echo "by apply: hsweeps."
  echo "Qed."
  echo
  echo "(* ---- what the seventy two run files say ------------------------ *)"
  echo
  echo "Lemma hj k w : (k < seq.size rpfx)%N -> w \\in hpres ->"
  echo "  hrun h_mt_e h_mt_cl h_mt_ct h_which h_fam h_sym_cl h_sym_ct hfoldall"
  echo "    k w (hdepth k) = false."
  echo "Proof."
  echo "move=> kL wp; have [j jL wj] := hslice_mem wp."
  echo "apply: negbTE; move: wj."
  echo "case: k kL => [|[|[|[|[|[|k]]]]]] // _;"
  echo "  case: j jL => [|[|[|[|[|[|[|[|[|[|[|[|j]]]]]]]]]]]] // _."
  k=0
  while [ "$k" -lt "$NK" ]; do
    j=0
    while [ "$j" -lt "$NJ" ]; do
      printf '%s\n' "- exact: (allP hrun_${k}_$(printf %02d $j) w)." 
      j=$((j + 1))
    done
    k=$((k + 1))
  done
  echo "Qed."
  echo
  echo "(* ---- and the bound, with nothing left ------------------------- *)"
  echo
  echo "Theorem targ_far25 : targ \\notin ball Sq 25."
  echo "Proof. by apply: (targ_far_runP hsweep_e hsweep_cl hsweep_ct hcut hj). Qed."
  echo
  echo "Theorem targ_dist25 : targ \\in ball Sq 26 /\\ targ \\notin ball Sq 25."
  echo "Proof. by split; [apply: targ_near | apply: targ_far25]. Qed."
  echo
  echo "(* the position is a maneuver, so it is in the group at all *)"
  echo "Lemma targ_gen : targ \\in generated Sq."
  echo "Proof."
  echo "have := wp_ball targw_qw."
  echo "by rewrite wp_targw; apply: (subsetP (ball_sub_gen Sq 40))."
  echo "Qed."
  echo
  echo "(* THE QUARTER TURN DIAMETER IS MORE THAN TWENTY FIVE *)"
  echo "Theorem qdiam25 : ~ diam_le Sq 25."
  echo "Proof."
  echo "move=> /subsetP hsub."
  echo "have := hsub _ targ_gen."
  echo "by apply/negP; apply: targ_far25."
  echo "Qed."
} > HAll.v.new
replace HAll.v.new HAll.v && echo "HAll.v written" || echo "HAll.v unchanged"
