#!/bin/sh
# Write the pieces of the three sweeps obligation C asks for.  The corner
# sweeps are one file, the edge sweep is the twenty four first slots cut
# into NJ jobs, each its own file.
#
#   ./mkhsweepc.sh         six jobs
#   ./mkhsweepc.sh 12      twelve jobs
#
# SIX, because the edge sweep is 190080 data times twelve turns and the same
# sweep in nat with vm_compute took 254 s (HEdgeChk, on roquableu); six jobs
# is a minute each, which is enough to watch.  The corner sweeps are 70 and
# 2187 data, a moment each, and go in the glue.
cd "$(dirname "$0")"

NS=24
NJ=${1:-6}
case "$NJ" in ''|*[!0-9]*)
  echo "usage: ./mkhsweepc.sh [jobs]" >&2; exit 1;; esac
[ "$NJ" -ge 1 ] && [ "$NJ" -le "$NS" ] || {
  echo "jobs must be between one and $NS" >&2; exit 1; }

# WRITE ONLY WHAT CHANGED: a file rewritten with the same content still gets a
# new mtime, and make reads that as a sweep to run again.
replace () {
  if [ -f "$2" ] && cmp -s "$1" "$2"; then rm -f "$1"; return 1; fi
  mv "$1" "$2"
}

changed=0
j=0
while [ "$j" -lt "$NJ" ]; do
  n=$(printf "%02d" "$j")
  lo=$(( j * NS / NJ ))
  hi=$(( (j + 1) * NS / NJ ))
  sed -e "s/@N@/$n/g" -e "s/@LO@/$lo/g" -e "s/@CNT@/$(( hi - lo ))/g" \
      -e "s/@NJ@/$NJ/g" HSweepE_task.v.in > "HSweepE_$n.v.new"
  replace "HSweepE_$n.v.new" "HSweepE_$n.v" && changed=$((changed + 1))
  j=$((j + 1))
done

# THE GLUE.  One job stops where the next starts, and echk_split is told so by
# the count the next job was written with -- the indices are numbers, so the
# joint holds by conversion and there is nothing to compute.
{
  echo "(* ============================================================== *)"
  echo "(*  HSweepCAll.v -- GENERATED by mkhsweepc.sh, do not edit.       *)"
  echo "(* ============================================================== *)"
  echo
  echo "From mathcomp Require Import all_ssreflect all_fingroup."
  echo "From Stdlib Require Import Uint63."
  echo "From Stdlib Require Import -(notations) PArray."
  echo "From Rubik Require Import ssrint63."
  echo "Require Import Table Tabi Rubik333 Sym Moves Coordfs Coordfsi Phase1"
  echo "        HRoot HCoord HReid HProp2 HSearch HEdge HCorner HSweepC HTables"
  j=0
  while [ "$j" -lt "$NJ" ]; do
    printf '        HSweepE_%02d\n' "$j"; j=$((j + 1))
  done
  echo "        ."
  echo
  echo "Set Implicit Arguments."
  echo "Unset Strict Implicit."
  echo "Unset Printing Implicit Defensive."
  echo
  echo "Import GroupScope."
  echo
  echo "(* the edge sweep, out of the $NJ jobs *)"
  echo "Lemma hechk : echk h_mt_e."
  echo "Proof."
  printf 'have hn : (2 * nedge)%%N = ('
  j=0
  while [ "$j" -lt "$NJ" ]; do
    lo=$(( j * NS / NJ )); hi=$(( (j + 1) * NS / NJ ))
    if [ "$j" -eq 0 ]; then printf '%d' $(( hi - lo ));
    else printf ' + (%d' $(( hi - lo )); fi
    j=$((j + 1))
  done
  j=1
  while [ "$j" -lt "$NJ" ]; do printf ')'; j=$((j + 1)); done
  echo ')%N by [].'
  echo "rewrite /echk hn."
  j=0
  while [ "$j" -lt $(( NJ - 1 )) ]; do
    printf 'apply: echk_split; first exact: hechk_%02d.\n' "$j"
    j=$((j + 1))
  done
  printf 'exact: hechk_%02d.\n' $(( NJ - 1 ))
  echo "Qed."
  echo
  echo "(* the two corner sweeps, which are small enough to stand here *)"
  echo "Lemma hclchk : clchk h_mt_cl."
  echo "Proof. Time native_cast_no_check (erefl true). Qed."
  echo
  echo "Lemma hctchk : ctchk h_mt_ct."
  echo "Proof. Time native_cast_no_check (erefl true). Qed."
  echo
  echo "(* ---- and the three obligations -------------------------------- *)"
  echo
  echo "Lemma hsweep_e : sweep_e h_mt_e."
  echo "Proof. exact: sweep_e_of_chk hechk. Qed."
  echo
  echo "Lemma hsweep_cl : sweep_cl h_mt_cl."
  echo "Proof. exact: sweep_cl_of_chk hclchk. Qed."
  echo
  echo "Lemma hsweep_ct : sweep_ct h_mt_ct."
  echo "Proof. exact: sweep_ct_of_chk hctchk. Qed."
  echo
  # THE forall IS NOT DECORATION.  Written with a and m as binders the goal
  # is already introduced, exact: falls back on apply and then done, and done
  # sets about computing ctsum of an abstract array.
  echo "(* the three side by side, which is what the search takes *)"
  echo "Lemma hsweeps : forall (a : arr) m,"
  echo "  tabi_ok flast a -> cubt (ti2t flast a) -> cubct (ti2t flast a) ->"
  echo "  ctsum (inv_tabi flast a) -> (m < nq)%N ->"
  echo "  htriple (comp_tabi flast a (mvq m))"
  echo "    = stepa h_mt_e h_mt_cl h_mt_ct (htriple a) (of_nat m)."
  echo "Proof. exact: sweeps_agree hsweep_e hsweep_cl hsweep_ct. Qed."
} > HSweepCAll.v.new
replace HSweepCAll.v.new HSweepCAll.v && changed=$((changed + 1))

echo "$NJ edge pieces plus the glue, $changed rewritten"
echo "run them with, say:"
# rocqtime.sh takes the BASE NAME, not the file name.
echo "  ls HSweepE_*.v | sed 's/[.]v\$//' | xargs -P 6 -I{} ./rocqtime.sh {}"
