#!/bin/sh
# Write the pieces of the sweep obligation D asks for: the 190080 e
# coordinates cut into NJ jobs, each its own file.
#
#   ./mkhsweep.sh          twelve jobs
#   ./mkhsweep.sh 18       eighteen jobs
#
# TWELVE, for the same reason the run used twelve: every job loads the whole
# folded table, measured at 3.86 GiB, so the 62 GB machine holds about twelve.
#
# PRICE ONE FIRST.  HSweepP.v runs the same sweep over 1, 8 and 64 of the
# 190080 e coordinates; until it has been timed nobody knows what the whole
# sweep costs in Rocq, and the search's node rate does not say -- a sweep
# reads the table in order and a search reads it at random.
cd "$(dirname "$0")"

NE=190080
NJ=${1:-12}
case "$NJ" in ''|*[!0-9]*) echo "usage: ./mkhsweep.sh [jobs]" >&2; exit 1;; esac
[ "$NJ" -ge 1 ] || { echo "jobs must be at least one" >&2; exit 1; }

# WRITE ONLY WHAT CHANGED: a file rewritten with the same content still gets a
# new mtime, and make reads that as a sweep to run again.
replace () {
  if [ -f "$2" ] && cmp -s "$1" "$2"; then rm -f "$1"; return 1; fi
  mv "$1" "$2"
}

changed=0
j=0
while [ "$j" -lt "$NJ" ]; do
  n=$(printf "%02d" "$j")
  lo=$(( j * NE / NJ ))
  hi=$(( (j + 1) * NE / NJ ))
  cnt=$(( hi - lo ))
  sed -e "s/@N@/$n/g" -e "s/@LO@/$lo/g" -e "s/@CNT@/$cnt/g" -e "s/@NJ@/$NJ/g" \
      HSweep_task.v.in > "HSweep_$n.v.new"
  replace "HSweep_$n.v.new" "HSweep_$n.v" && changed=$((changed + 1))
  j=$((j + 1))
done

# THE GLUE.  One job stops where the next starts, and adm_split is told so by
# the literal the next job was written with; the premise is a computation.
{
  echo "(* ====================================================================== *)"
  echo "(*  HSweepAll.v -- GENERATED by mkhsweep.sh, do not edit.                 *)"
  echo "(* ====================================================================== *)"
  echo
  echo "From mathcomp Require Import all_ssreflect all_fingroup."
  echo "From Stdlib Require Import Uint63."
  echo "From Stdlib Require Import -(notations) PArray."
  echo "From Rubik Require Import ssrint63."
  echo "Require Import Table Tabi Rubik333 Moves Coordfs Phase1 HRoot HCoord"
  echo "        HSearch HSweep HTables HFoldAll"
  j=0
  while [ "$j" -lt "$NJ" ]; do
    printf '        HSweep_%02d\n' "$j"; j=$((j + 1))
  done
  echo "        ."
  echo
  echo "Set Implicit Arguments."
  echo "Unset Strict Implicit."
  echo "Unset Printing Implicit Defensive."
  echo
  echo "Import GroupScope."
  echo
  echo "(* the sweep of the whole table, out of the $NJ jobs *)"
  echo "Lemma hsweep_all :"
  echo "  admis h_mt_e h_mt_cl h_mt_ct h_which h_fam h_sym_cl h_sym_ct hfoldall."
  echo "Proof."
  printf 'have hn : n_e = ('
  j=0
  while [ "$j" -lt "$NJ" ]; do
    lo=$(( j * NE / NJ )); hi=$(( (j + 1) * NE / NJ ))
    if [ "$j" -eq 0 ]; then printf '%d' $(( hi - lo ));
    else printf ' + (%d' $(( hi - lo )); fi
    j=$((j + 1))
  done
  j=1
  while [ "$j" -lt "$NJ" ]; do printf ')'; j=$((j + 1)); done
  echo ')%N by [].'
  echo "rewrite /admis hn."
  j=0
  while [ "$j" -lt $(( NJ - 1 )) ]; do
    hi=$(( (j + 1) * NE / NJ ))
    printf 'apply: (adm_split (y := %d%%uint63)); [by vm_compute | exact: hsweep_%02d |].\n' \
      "$hi" "$j"
    j=$((j + 1))
  done
  printf 'exact: hsweep_%02d.\n' $(( NJ - 1 ))
  echo "Qed."
} > HSweepAll.v.new
replace HSweepAll.v.new HSweepAll.v && changed=$((changed + 1))

echo "$NJ pieces plus the glue, $changed rewritten"
echo "run them with, say:"
# rocqtime.sh takes the BASE NAME, not the file name.
echo "  ls HSweep_*.v | sed 's/[.]v$//' | xargs -P 12 -I{} ./rocqtime.sh {}"
