#!/usr/bin/env python3
# mkmintab.py -- RowMinTab.v: the tables the folded run reads from mathcomp
# seq files, written again as array literals that need Stdlib only, padded
# to the size each mkarr gives them.  The numbers are read, not recomputed.
import re

def read_def(file, name):
    txt = open(file).read()
    i = txt.index('Definition %s ' % name)
    j = txt.index('[::', i) + 3
    k = txt.index(']', j)
    return [int(t) for t in re.findall(r'\d+', txt[j:k])]

TABS = [  # name in RowMinTab, file, name there, size mkarr gives it
    ('e8num_m',  'RowTabL.v',   'e8num_data', 40320),
    ('e4bit_m',  'RowTabL.v',   'e4bit_data', 24),
    ('mgr_m',    'RowTabP.v',   'mgr_data',   201600),
    ('msw_m',    'RowTabP.v',   'msw_data',   10),
    ('mlo_m',    'RowTabP.v',   'mlo_data',   40960),
    ('mhi_m',    'RowTabP.v',   'mhi_data',   40960),
    ('twmove_m', 'P1Small.v',   'twmove_data', 39366),
    ('fpg_m',    'RowTabF48.v', 'fpg_data',   40320),
    ('fsrc_m',   'RowTabF48.v', 'fsrc_data',  14960),
    ('fsrc2_m',  'RowTabF48.v', 'fsrc2_data', 14960),
    ('ffull_m',  'RowTabF48.v', 'ffull_data', 1496),
    ('fsgr_m',   'RowTabF48.v', 'fsgr_data',  645120),
    ('fslo_m',   'RowTabF48.v', 'fslo_data',  65536),
    ('fshi_m',   'RowTabF48.v', 'fshi_data',  65536),
    ('fsbt_m',   'RowTabF48.v', 'fsbt_data',  384),
    ('forb_m',   'RowTabF48.v', 'forb_data',  1496),
    ('fpop_m',   'RowTabF48.v', 'fpop_data',  4096),
]

out = open('RowMinTab.v', 'w')
out.write('''(* GENERATED by mkmintab.py -- do not edit.                                  *)
(* The folded run's tables that live in mathcomp seq files, as array        *)
(* literals needing Stdlib only, for RowMin.v.  Same numbers, padded with 0 *)
(* to the size mkarr gives each one.                                        *)

From Stdlib Require Import Uint63.
From Stdlib Require Import PArray.

Local Open Scope uint63_scope.

''')
for (name, file, src, size) in TABS:
    l = read_def(file, src)
    assert len(l) <= size, (name, len(l), size)
    l = l + [0] * (size - len(l))
    out.write('Definition %s : array int := [|\n' % name)
    for i, v in enumerate(l):
        out.write('%d%s' % (v, '' if i == size - 1 else (';\n' if i % 8 == 7 else '; ')))
    out.write('\n| 0 |].\n\n')
    print('%-9s %7d entries from %s (%d read)' % (name, size, file, len(l)))
out.close()
