#!/bin/sh
# =========================================================================
#  Regenerate the phase 1 step certificate, split across files.
#
#    ./mkp1chk.sh            27 slices of 81 twists, native
#    ./mkp1chk.sh 9          9 slices of 243
#    EVAL=vm ./mkp1chk.sh    vm_cast_no_check instead
#
#  p1checkStep is `all (fun t => p1checkTw (of_nat t)) (iota 0 2187)', and
#  each twist is an all_pow over 2 ^ 24 packed values -- 2187 x 2 ^ 24
#  conditions in total, which is the largest computation in the project.
#  2187 = 3 ^ 7, so it splits evenly 3, 9, 27, 81, 243 or 729 ways.
#
#  Phase1.p1checkStep_of_slices is what glues them: it takes ANY seq s with
#  s = iota 0 ntwist, so the slices are concatenated and that equation is
#  settled by vm_compute on 2187 elements, which is nothing.
#
#  MEMORY: each slice loads the whole phase 1 table, 3 GB since the chunks
#  became array literals.  DO NOT choose the -j yourself: say `make p1chk',
#  with no -j, and Makefile.local takes it from the RAM present.
# =========================================================================

NSLICE=${1:-27}
NTWIST=2187
LEN=$((NTWIST / NSLICE))

[ $((LEN * NSLICE)) -eq $NTWIST ] || {
  echo "$NSLICE does not divide $NTWIST (2187 = 3^7: use 3 9 27 81 243 729)" >&2
  exit 1; }

case "${EVAL:-native}" in
  native) CAST="native_cast_no_check (erefl true)";;
  vm)     CAST="vm_cast_no_check (erefl true)";;
  *)      echo "EVAL must be native or vm" >&2; exit 1;;
esac

i=0
while [ $i -lt $NSLICE ]; do
  n=$(printf "%02d" $i)
  lo=$((i * LEN))
  cat > "P1Chk_$n.v" <<EOF
(* =========================================================================  *)
(*  P1Chk_$n.v                                                                *)
(*                                                                            *)
(*  GENERATED by mkp1chk.sh -- do not edit.                                   *)
(*                                                                            *)
(*  Twists $lo .. $((lo + LEN - 1)) of the phase 1 step certificate: $LEN twists, each   *)
(*  an all_pow over 2 ^ 24 packed values.  P1ChkAll.v glues the slices.       *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsTable Diameter Moves
        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1
        P1Table.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

(* p1checkTwr, NOT p1checkTw: it reads the emitted fsmove table where
   p1checkTw recomputes the action with actf.  MEASURED: actf 6.2 us,
   actfsr 0.12 us, and there are eighteen of them for each of the
   1 013 760 summaries in each twist.  Farp1.p1checkStepr_ok turns the
   cheap check into the real one, using fsmoveC -- which is a 2 ^ 24
   certificate that has to be discharged anyway. *)
Lemma p1chk_$n :
  all (fun t => p1checkTwr p1tab (of_nat t)) (iota $lo $LEN).
Proof. Time $CAST. Qed.
EOF
  i=$((i + 1))
done

# ---- the glue -------------------------------------------------------------
{
cat <<EOF
(* =========================================================================  *)
(*  P1ChkAll.v                                                                *)
(*                                                                            *)
(*  GENERATED by mkp1chk.sh -- do not edit.                                   *)
(*                                                                            *)
(*  The $NSLICE slices glued into p1checkStep, via                            *)
(*  Phase1.p1checkStep_of_slices: it takes any seq s with s = iota 0 ntwist,  *)
(*  so the slices are concatenated and that equation is a vm_compute over     *)
(*  2187 elements.  The slices themselves arrive as opaque Qed constants,     *)
(*  so nothing is recomputed here.                                            *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsTable Diameter Moves
        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1
        P1Table FsmChk.
EOF
i=0
while [ $i -lt $NSLICE ]; do
  printf "Require Import P1Chk_%02d.\n" $i
  i=$((i + 1))
done
cat <<'EOF'

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

Definition slices : seq nat :=
EOF
i=0
while [ $i -lt $NSLICE ]; do
  lo=$((i * LEN))
  if [ $i -eq $((NSLICE - 1)) ]; then
    printf "  iota %d %d.\n" $lo $LEN
  else
    printf "  iota %d %d ++\n" $lo $LEN
  fi
  i=$((i + 1))
done
cat <<'EOF'

Lemma slicesE : slices = iota 0 ntwist.
Proof. by vm_compute. Qed.

Lemma p1checkSteprP : p1checkStepr p1tab.
Proof.
apply: (p1checkStepr_of_slices slicesE).
EOF
printf "by rewrite /slices !all_cat"
i=0
while [ $i -lt $NSLICE ]; do
  printf " p1chk_%02d" $i
  i=$((i + 1))
done
printf ".\nQed.\n\n"
printf "Lemma p1checkStepP : p1checkStep p1tab.\n"
printf "Proof. exact: (p1checkStepr_ok fsmoveCP p1checkSteprP). Qed.\n"
} > P1ChkAll.v

# ---- and _CoqProject, or make has no rule for any of them ----------------
# The slice count is an argument, so the entries cannot just be checked in:
# the old ones are dropped and the new ones added on every run.
grep -v '^P1Chk_' _CoqProject | grep -v '^P1ChkAll\.v$' > _CoqProject.new
i=0
while [ $i -lt $NSLICE ]; do
  printf "P1Chk_%02d.v\n" $i >> _CoqProject.new
  i=$((i + 1))
done
echo "P1ChkAll.v" >> _CoqProject.new
mv _CoqProject.new _CoqProject

echo "wrote P1Chk_00 .. P1Chk_$(printf "%02d" $((NSLICE - 1))).v and P1ChkAll.v"
echo "  and listed them in _CoqProject, so make has rules for them"
echo "  $NSLICE slices of $LEN twists, $CAST"
echo ""
echo "  now say   make p1chk   -- with NO -j: it is a memory question, and"
echo "  Makefile.local computes the job count from the RAM present."
