#!/usr/bin/env python3
"""Turn the leftovers of a row into the witness list RowFinal.v asks for.

The row prints one line per member it could not reach:

    LEFT <page> <group> <bit> <n> <m1> ... <mn>   # U R2 F ...

and this reads them off a log and writes the Rocq list.  A move number is
three times the face plus the amount, the faces U R F D L B, which is the
numbering the whole development uses -- so the numbers go through unchanged.

Nothing here has to be right.  Every word is played back by `wok' before it
is believed, so a mistake in this script makes the check fail, never the
theorem false.

    ./mkwits.py < superflip-row.log > RowWits.v
"""

import sys


def main() -> int:
    wits = []
    nowords = []
    for line in sys.stdin:
        if not line.startswith("LEFT "):
            continue
        body = line.split("#")[0].split()
        if len(body) < 5 or body[4] == "NONE":
            nowords.append(line.strip())
            continue
        pg, gr, bt, n = (int(x) for x in body[1:5])
        word = [int(x) for x in body[5:]]
        if len(word) != n or n > 20:
            print("a word of the wrong length: " + line.strip(), file=sys.stderr)
            return 1
        if any(m < 0 or m > 17 for m in word):
            print("a move out of range: " + line.strip(), file=sys.stderr)
            return 1
        wits.append((pg, gr, bt, word))

    # every one of them, not just the first: a place with no word is a place
    # to attack on its own with ROWPLACE, and it is worth seeing them all
    if nowords:
        for l in nowords:
            print(l, file=sys.stderr)
        print("%d leftover(s) with no word of twenty, %d with one"
              % (len(nowords), len(wits)), file=sys.stderr)
        return 1

    if not wits:
        print("no leftover in the log", file=sys.stderr)
        return 1

    out = sys.stdout
    out.write("(* ====================================================="
              "====================  *)\n")
    out.write("(*  RowWits.v -- the members the row left over, one word each."
              "                *)\n")
    out.write("(* ====================================================="
              "====================  *)\n\n")
    out.write("(* GENERATED by mkwits.py from a row's own output.  Every word "
              "here is\n")
    out.write("   played back by RowFinal.wok before it is believed, so what "
              "produced it is\n")
    out.write("   never trusted: a mistake makes the check fail, never the "
              "theorem false.\n")
    out.write("   A move is three times the face plus the amount, the faces "
              "U R F D L B.  *)\n\n")
    out.write("From mathcomp Require Import all_ssreflect.\n")
    out.write("From Stdlib Require Import Uint63.\n")
    out.write("From Rubik Require Import ssrint63.\n\n")
    out.write("Definition rowwits : seq (int * int * int * seq nat) :=\n")
    for i, (pg, gr, bt, word) in enumerate(wits):
        head = "  [:: " if i == 0 else "      "
        moves = "; ".join(str(m) for m in word)
        out.write("%s(%d%%uint63, %d%%uint63, %d%%uint63,\n" % (head, pg, gr, bt))
        out.write("       [:: %s]%%N)%s\n" % (moves, "" if i + 1 == len(wits) else ";"))
    out.write("  ].\n")
    print("%d witnesses" % len(wits), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
