(* GENERATED by bench/p1gen.ml -- do not edit.                    *)
(* DUMMY -- empty stand in for P1Data_real.v.  Swap it in only when the certificate is being checked. *)

From Stdlib Require Import Uint63.
From mathcomp Require Import all_ssreflect.

Definition srank_data : seq int := [::
]%uint63.

Definition twmove_data : seq int := [::
]%uint63.

Definition p1_chunk_00 : seq int := [::
]%uint63.

