(* GENERATED by bench/p1gen.ml -- do not edit.                             *)
(* DUMMY stand in for the flip x slice move table.  Regenerate the real one *)
(* with `bench/p1gen 9 small': it is 116 MB and ~20 min to compile, and     *)
(* NOTHING in the development depends on its contents -- the search is      *)
(* certified rather than trusted, so every proof goes through with this.    *)

From Stdlib Require Import Uint63.
From mathcomp Require Import all_ssreflect.

Definition fsmove_data : seq int := [::
]%uint63.
