(* =========================================================================  *)
(*  Runp1_09b.v -- GENERATED by mkrunp1.sh, do not edit.                   *)
(*     Half a piece: one root move instead of both, for the two second        *)
(*     moves that set the makespan.                                           *)
(* =========================================================================  *)

From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsTable Diameter Moves
        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Fsparity
        Farp1 P1FTable Runp1 Fast FastP FsmChk.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Import GroupScope.

Lemma p1searchd_09b :
  ~~ searchz3 p1ftab 14 (prefixi 1 9)
              (init3 (prefixi 1 9)) (fcpos 9).
(* p1searchd_bridge1 runs the fast search and gives this statement. fcpos 9 *)
(* is the face of the second move: the search starts guarded against it, so   *)
(* the third move is one of about thirteen and not one of eighteen.           *)
Proof.
(* every argument given: `done' would unfold an all_pow at ncoord = 24        *)
apply: (@p1searchd_bridge1 p1ftab 14 9 (fcpos 9) 1 isT isT isT isT
                           fsmoveCP).
Time native_cast_no_check (erefl true).
Qed.
