#!/bin/sh
# Run the three view search at depth N -- rubik_par's experiment, in Rocq.
#
#   ./runp1.sh          depth 14
#   ./runp1.sh 15       depth 15
#
# Needs the phase 1 table built first (./mkp1.sh).  Everything else it does
# itself.  NO PROOF IS INVOLVED: this is the computation.  What would make
# its answer a theorem is Farp1.far_of_searchz3, still admitted.
set -e
cd "$(dirname "$0")"
#   ./runp1.sh prepare   build the two remaining tables, run nothing
#   ./runp1.sh 14        run depth 14 -- and if prepare was done first, this
#                        command does NOTHING BUT THE SEARCH
N=${1:-14}
#   ./runp1.sh count 14 0   node count for piece 0 at depth 14, to compare
#                           against `bench/p1gen 9 pieces 14 0'
#   ./runp1.sh count "13 14 15 16" 0   the same, several depths in one go,
#                           sequentially
#   EVAL=native ./runp1.sh count 16 0  the same under native_compute
# vm (default) or native.  EVAL=native to compare footprints.
case "${EVAL:-vm}" in
  vm)     EVALC=vm_compute;;
  native) EVALC=native_compute;;
  *)      echo "EVAL must be vm or native" >&2; exit 1;;
esac

COUNT=0
if [ "$1" = "count" ]; then COUNT=1; shift; N=${1:-14}; J=${2:-0}; fi
if [ "$N" = "prepare" ]; then PREPARE=1; N=14; else PREPARE=0; fi
# in count mode N may be a list of depths, so each word is checked instead
for w in $N; do
  case "$w" in ''|*[!0-9]*)
    echo "usage: ./runp1.sh [prepare|depth] | count \"d1 d2 ...\" [piece]" >&2
    exit 1;;
  esac
done

[ -f P1_70.vo ] || { echo "run ./mkp1.sh first (the phase 1 table)" >&2; exit 1; }

ulimit -s unlimited

# P1Fsm.v is checked in as a DUMMY -- 116 MB is too big for git -- so the real
# one has to be regenerated.  With the dummy every fsmove read is 0 and the
# search is nonsense, so this is not optional.
# P1Fsm.v is NOT in git -- it used to be checked in as a dummy under the same
# name, and every git pull then restored the dummy over the real table, so the
# search ran with every fsmove read returning 0.  That cost a day.
# SIZE IS NOT ENOUGH.  The pre-chunking table is 121 MB and defines a single
# fsmove_data, so it passes any size test yet Farp1.v fails on it with
# "fsm_chunk_00 was not found".  Test the FORMAT too, on the definition name
# (structural), not on a data line.
if [ ! -f P1Fsm.v ] || [ "$(wc -c < P1Fsm.v)" -lt 1000000 ] ||
   ! grep -q "^Definition fsm_chunk_02" P1Fsm.v; then
  echo "regenerating the real P1Fsm.v (116 MB)"
  # rebuild if the source is NEWER, not merely if the binary is absent: a
  # stale p1gen silently emits the old set of tables
  (cd bench && { [ -x p1gen ] && [ p1gen -nt p1gen.ml ]; } || ocamlfind \
     ocamlopt -package unix -linkpkg cubedata.ml p1gen.ml -o p1gen)
  (cd bench && ./p1gen 9 small)
  echo "compiling P1Fsm.v (~20 min)"
  rocq compile -R . Rubik P1Fsm.v
fi

# TIMED SEPARATELY, so the search's own cost is visible.  Building the glue
# is a one-off; loading it is paid per run; the search itself is the
# `Time Eval' line inside RunReal.v and is neither.
# the glue is regenerable in milliseconds and needs no BFS
[ -f P1Table.v ] || (cd bench && ./p1gen 9 table)

# FRESHNESS, not mere existence.  P1Table.v requires Phase1, so a change to
# Phase1.v makes P1Table.vo stale -- and a stale .vo does not fall back, it
# fails the digest check when the count file loads it.
newer_than_vo () { [ ! -f "$2" ] || [ "$1" -nt "$2" ]; }

# the proof files FIRST: P1Table requires Phase1, and Runp1 requires Farp1
for f in Phase1 Far Farp1; do
  if newer_than_vo "$f.v" "$f.vo"; then
    echo "=== compiling $f.v ==="
    rocq compile -R . Rubik "$f.v"
  fi
done

if newer_than_vo P1Table.v P1Table.vo || newer_than_vo Phase1.vo P1Table.vo; then
  echo "=== compiling P1Table.v (one-off, 4.5 GB of chunks) ==="
  time rocq compile -R . Rubik P1Table.v
fi

if newer_than_vo Runp1.v Runp1.vo || newer_than_vo Farp1.vo Runp1.vo; then
  echo "=== compiling Runp1.v ==="
  rocq compile -R . Rubik Runp1.v
fi

if [ "$PREPARE" = "1" ]; then
  echo "tables ready -- ./runp1.sh N now measures the search alone"
  exit 0
fi

if [ "$COUNT" = "1" ]; then
 for D in $N; do
  R=$((D - 2))
  # PER RUN FILENAME.  This used to be a fixed CountReal.v, so two runs
  # started at once overwrote each other's source, .vo and .glob -- seven
  # concurrent depths all compiled whichever file won the race, and the
  # numbers meant nothing.  MEASURED: each run holds 8.5-10 GB resident, so
  # 64 GB caps roquableu at about five of these at once anyway.
  F="CountReal_${D}_${J}"
  cat > "$F.v" <<EOF2
(* GENERATED by runp1.sh -- do not edit.                                      *)
From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsTable Diameter Moves
        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1
        P1Table Runp1.
Set Implicit Arguments.
Import GroupScope.

(* (solution found, nodes) -- compare with bench/p1gen 9 pieces $D $J.        *)
(* The count is an int63: a unary nat counter costs O(subtree) per            *)
(* addition and was reporting itself as well as the search.                   *)
Time Eval $EVALC in countp1 p1tab $R $J.
EOF2
  echo "=== counting nodes, depth $D, piece $J, $EVALC ==="
  time rocq compile -R . Rubik "$F.v"
 done
 exit 0
fi

cat > RunReal.v <<EOF
(* GENERATED by runp1.sh -- do not edit.                                      *)
From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsTable Diameter Moves
        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1
        P1Table Runp1.
Set Implicit Arguments.
Import GroupScope.

(* false = no solution at this depth, which the superflip must give           *)
Time Eval vm_compute in runp1 p1tab $N.
EOF
echo "=== running depth $N ==="
echo "(the Time Eval below is the SEARCH alone; the total after it is that"
echo " plus loading the 8 GB table into the process)"
time rocq compile -R . Rubik RunReal.v
