#!/bin/sh
# Run the three view search at depth N -- rubik_par's experiment, in Rocq.
#
#   ./runp1.sh          depth 14
#   ./runp1.sh 15       depth 15
#
# Needs the phase 1 table built first (./mkp1.sh).  Everything else it does
# itself.  NO PROOF IS INVOLVED: this is the computation.  What would make
# its answer a theorem is Farp1.far_of_searchz3, still admitted.
set -e
cd "$(dirname "$0")"
N=${1:-14}
case "$N" in ''|*[!0-9]*) echo "usage: ./runp1.sh [depth]" >&2; exit 1;; esac

[ -f P1_70.vo ] || { echo "run ./mkp1.sh first (the phase 1 table)" >&2; exit 1; }

ulimit -s unlimited

# P1Fsm.v is checked in as a DUMMY -- 116 MB is too big for git -- so the real
# one has to be regenerated.  With the dummy every fsmove read is 0 and the
# search is nonsense, so this is not optional.
if ! grep -q "^0; " P1Fsm.v 2>/dev/null; then
  echo "regenerating the real P1Fsm.v (116 MB)"
  (cd bench && [ -x p1gen ] || ocamlfind ocamlopt -package unix -linkpkg \
     cubedata.ml p1gen.ml -o p1gen)
  (cd bench && ./p1gen 9 small)
  echo "compiling P1Fsm.v (~20 min)"
  rocq compile -R . Rubik P1Fsm.v
fi

# TIMED SEPARATELY, so the search's own cost is visible.  Building the glue
# is a one-off; loading it is paid per run; the search itself is the
# `Time Eval' line inside RunReal.v and is neither.
if [ ! -f P1Table.vo ]; then
  echo "=== compiling P1Table.v (one-off, 4.5 GB of chunks) ==="
  time rocq compile -R . Rubik P1Table.v
fi

cat > RunReal.v <<EOF
(* GENERATED by runp1.sh -- do not edit. *)
From mathcomp Require Import all_ssreflect all_fingroup.
From Stdlib Require Import Uint63.
From Stdlib Require Import -(notations) PArray.
From Rubik Require Import ssrint63.
Require Import Cyc Ball Table Search Tsearch Tabi Rubik333 Sym Root Coord
        Coordfs Coordfsi Fstab FsTable Diameter Moves
        Searchr Redun Searchir P1Small P1Ts P1Fs P1Fsm Phase1 Far Farp1
        P1Table Runp1.
Set Implicit Arguments.
Import GroupScope.

(* false = no solution at this depth, which is what the superflip must give *)
Time Eval vm_compute in runp1 p1tab $N.
EOF
echo "=== running depth $N ==="
echo "(the Time Eval below is the SEARCH alone; the total after it is that"
echo " plus loading the 8 GB table into the process)"
time rocq compile -R . Rubik RunReal.v
