// The test inputs of ExpModel.v: for each input xb, what exp100.c returns,
// written as a Rocq file.  ../../exp100.c is included so that the counts
// of the corrections of guess_n can be printed too.
//
//   gen_tests CHUNK NCHUNKS   writes the lines of chunk CHUNK (0-based)
//                             of NCHUNKS to stdout, as Tests<CHUNK>.v
//   gen_tests stats           prints how often each path is taken

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "../../exp100.c"

static uint64_t *inputs;
static long n_inputs, cap_inputs;

static void add(uint64_t u) {
  if (n_inputs == cap_inputs) {
    cap_inputs = cap_inputs ? 2 * cap_inputs : 1024;
    inputs = realloc(inputs, cap_inputs * sizeof(uint64_t));
  }
  inputs[n_inputs++] = u;
}

union bits { double d; uint64_t u; };

static uint64_t to_bits(double x) {
  union bits b;
  b.d = x;
  return b.u;
}

static uint64_t rnd64(void) {
  static uint64_t st = 0x9e3779b97f4a7c15UL;   // xorshift64*, fixed seed
  st ^= st >> 12; st ^= st << 25; st ^= st >> 27;
  return st * 0x2545f4914f6cdd1dUL;
}

// random bits with biased exponent in [lo, hi], random sign
static uint64_t rnd_expo(int lo, int hi) {
  uint64_t be = lo + rnd64() % (hi - lo + 1);
  return (rnd64() & 0x800fffffffffffffUL) | (be << 52);
}

// x and its neighbours, 8 bit patterns on each side
static void around(double x) {
  uint64_t u = to_bits(x);
  for (int d = -8; d <= 8; d++) add(u + d);
}

static void make_inputs(void) {
  // the special values and the edges of the decoding
  uint64_t sp[] = {
    0, 0x8000000000000000UL, 1, 0x8000000000000001UL,
    0x000fffffffffffffUL, 0x800fffffffffffffUL,
    0x0010000000000000UL, 0x8010000000000000UL,
    0x7ff0000000000000UL, 0xfff0000000000000UL,   // infinities
    0x7ff8000000000000UL, 0xfff8000000000001UL,   // NaN
    0x4090000000000000UL, 0xc090000000000000UL,   // +-1024
    0x408fffffffffffffUL, 0xc08fffffffffffffUL,   // just below 1024
    0x7fefffffffffffffUL, 0xffffffffffffffffUL };
  for (unsigned i = 0; i < sizeof sp / sizeof sp[0]; i++) add(sp[i]);
  around(-745.14); around(-0x1.74910d52d3051p+9);
  around(-0x1.6232bdd7abcd2p+9); around(0x1.62e42fefa39efp+9);
  around(709.79); around(1.0); around(-1.0);
  around(0x1p-53); around(-0x1p-53); around(0x1p-1022);
  // the doubles nearest k ln2/64: the corrections of the guess of n
  for (long k = -94600; k <= 94600; k += (k > -70 && k < 70) ? 1 : 997)
    if (k != 0) around(k * 0.693147180559945309417232 / 64);
  // random: every binade below 1024, |x| in [2^-60, 2^10), any bits
  for (int i = 0; i < 1500; i++) add(rnd_expo(0, 1032));
  for (int i = 0; i < 1500; i++) add(rnd_expo(1023 - 60, 1032));
  for (int i = 0; i < 300; i++) add(rnd64());
}

static void stats(void) {
  long lowered = 0, raised = 0, rc[4] = {0}, mh = 0;
  for (long i = 0; i < n_inputs; i++) {
    uint64_t xb = inputs[i], y[NL], X[NL], q[NL], q1[NL];
    int64_t s;
    int c = exp_core(xb, y, &s);
    rc[c]++;
    mh += maybe_hard_bits(xb);
    int be = (int) ((xb >> 52) & 0x7ff);
    if (be >= 1033) continue;
    uint64_t mx = xb & (((uint64_t) 1 << 52) - 1);
    if (be == 0) be = 1; else mx |= (uint64_t) 1 << 52;
    num_scale(X, mx, be - 1075 + P);
    uint64_t n = guess_n(X);
    mul_ln2(q, n);
    if (num_lt(X, q) && n > 0) { n--; lowered++; }
    mul_ln2(q1, n + 1);
    if (!num_lt(X, q1)) raised++;
  }
  printf("inputs %ld: rc0 %ld rc1 %ld rc2 %ld rc3 %ld, guess lowered %ld "
         "raised %ld, maybe_hard 1: %ld\n", n_inputs, rc[0], rc[1], rc[2],
         rc[3], lowered, raised, mh);
}

static void chunk(long c, long nc) {
  long lo = n_inputs * c / nc, hi = n_inputs * (c + 1) / nc;
  printf("(* Generated by gen_tests.c from ../../exp100.c, do not edit.\n"
         "   (xb, rc, M, s, maybe_hard) for inputs %ld to %ld. *)\n\n"
         "From Stdlib Require Import ZArith List.\n"
         "From Exp100 Require Import ExpModel.\n"
         "From Exp100Test Require Import Check.\n"
         "Import ListNotations.\nOpen Scope Z_scope.\n\n"
         "Definition tests : list test := [\n", lo, hi - 1);
  for (long i = lo; i < hi; i++) {
    uint64_t M[3] = {0, 0, 0};
    int64_t s = 0;
    int rc = exp_encl_bits(inputs[i], M, &s);
    if (rc) s = 0;
    printf("  (0x%016lx, %d, 0x%016lx%016lx%016lx, %ld, %d)%s\n",
           (unsigned long) inputs[i], rc, (unsigned long) M[2],
           (unsigned long) M[1], (unsigned long) M[0], (long) s,
           maybe_hard_bits(inputs[i]), i + 1 < hi ? ";" : "");
  }
  printf("].\n\nLemma tests_ok : forallb ok tests = true.\n"
         "Proof. vm_compute. reflexivity. Qed.\n");
}

int main(int argc, char **argv) {
  make_inputs();
  if (argc == 2 && !strcmp(argv[1], "stats")) stats();
  else if (argc == 3) chunk(atol(argv[1]), atol(argv[2]));
  else { fprintf(stderr, "usage: gen_tests stats | CHUNK NCHUNKS\n"); return 1; }
  return 0;
}
